/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChainConfig implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String network;
    private String rpcUrl;
    private String programIdDevnet;
    private String programIdMainnet;
    private String anchorProgramName;
    private String anchorScaffoldPath;
    private String anchorIdlVersion;
    private String anchorIdlHash;
    private String instructionRegistryJson;
    private LocalDateTime programDeployedAt;
    private String usdcMint;
    private String envNetworkKey;
    private String envRpcKey;
    private String envProgramIdDevnetKey;
    private String envProgramIdMainnetKey;
    private String bagsApiBase;
    private String watcherUrl;
    private String squadsMultisig;
    private String ownerWalletPubkey;
    private Integer protocolFeeBps;
    private Byte isActive;

    public ChainConfig() {}

    public ChainConfig(ChainConfig value) {
        this.id = value.id;
        this.network = value.network;
        this.rpcUrl = value.rpcUrl;
        this.programIdDevnet = value.programIdDevnet;
        this.programIdMainnet = value.programIdMainnet;
        this.anchorProgramName = value.anchorProgramName;
        this.anchorScaffoldPath = value.anchorScaffoldPath;
        this.anchorIdlVersion = value.anchorIdlVersion;
        this.anchorIdlHash = value.anchorIdlHash;
        this.instructionRegistryJson = value.instructionRegistryJson;
        this.programDeployedAt = value.programDeployedAt;
        this.usdcMint = value.usdcMint;
        this.envNetworkKey = value.envNetworkKey;
        this.envRpcKey = value.envRpcKey;
        this.envProgramIdDevnetKey = value.envProgramIdDevnetKey;
        this.envProgramIdMainnetKey = value.envProgramIdMainnetKey;
        this.bagsApiBase = value.bagsApiBase;
        this.watcherUrl = value.watcherUrl;
        this.squadsMultisig = value.squadsMultisig;
        this.ownerWalletPubkey = value.ownerWalletPubkey;
        this.protocolFeeBps = value.protocolFeeBps;
        this.isActive = value.isActive;
    }

    public ChainConfig(
        Long id,
        String network,
        String rpcUrl,
        String programIdDevnet,
        String programIdMainnet,
        String anchorProgramName,
        String anchorScaffoldPath,
        String anchorIdlVersion,
        String anchorIdlHash,
        String instructionRegistryJson,
        LocalDateTime programDeployedAt,
        String usdcMint,
        String envNetworkKey,
        String envRpcKey,
        String envProgramIdDevnetKey,
        String envProgramIdMainnetKey,
        String bagsApiBase,
        String watcherUrl,
        String squadsMultisig,
        String ownerWalletPubkey,
        Integer protocolFeeBps,
        Byte isActive
    ) {
        this.id = id;
        this.network = network;
        this.rpcUrl = rpcUrl;
        this.programIdDevnet = programIdDevnet;
        this.programIdMainnet = programIdMainnet;
        this.anchorProgramName = anchorProgramName;
        this.anchorScaffoldPath = anchorScaffoldPath;
        this.anchorIdlVersion = anchorIdlVersion;
        this.anchorIdlHash = anchorIdlHash;
        this.instructionRegistryJson = instructionRegistryJson;
        this.programDeployedAt = programDeployedAt;
        this.usdcMint = usdcMint;
        this.envNetworkKey = envNetworkKey;
        this.envRpcKey = envRpcKey;
        this.envProgramIdDevnetKey = envProgramIdDevnetKey;
        this.envProgramIdMainnetKey = envProgramIdMainnetKey;
        this.bagsApiBase = bagsApiBase;
        this.watcherUrl = watcherUrl;
        this.squadsMultisig = squadsMultisig;
        this.ownerWalletPubkey = ownerWalletPubkey;
        this.protocolFeeBps = protocolFeeBps;
        this.isActive = isActive;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.network</code>.
     */
    public String getNetwork() {
        return this.network;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.network</code>.
     */
    public void setNetwork(String network) {
        this.network = network;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.rpc_url</code>.
     */
    public String getRpcUrl() {
        return this.rpcUrl;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.rpc_url</code>.
     */
    public void setRpcUrl(String rpcUrl) {
        this.rpcUrl = rpcUrl;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.program_id_devnet</code>.
     */
    public String getProgramIdDevnet() {
        return this.programIdDevnet;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.program_id_devnet</code>.
     */
    public void setProgramIdDevnet(String programIdDevnet) {
        this.programIdDevnet = programIdDevnet;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.program_id_mainnet</code>.
     */
    public String getProgramIdMainnet() {
        return this.programIdMainnet;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.program_id_mainnet</code>.
     */
    public void setProgramIdMainnet(String programIdMainnet) {
        this.programIdMainnet = programIdMainnet;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.anchor_program_name</code>.
     */
    public String getAnchorProgramName() {
        return this.anchorProgramName;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.anchor_program_name</code>.
     */
    public void setAnchorProgramName(String anchorProgramName) {
        this.anchorProgramName = anchorProgramName;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.anchor_scaffold_path</code>.
     */
    public String getAnchorScaffoldPath() {
        return this.anchorScaffoldPath;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.anchor_scaffold_path</code>.
     */
    public void setAnchorScaffoldPath(String anchorScaffoldPath) {
        this.anchorScaffoldPath = anchorScaffoldPath;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.anchor_idl_version</code>.
     */
    public String getAnchorIdlVersion() {
        return this.anchorIdlVersion;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.anchor_idl_version</code>.
     */
    public void setAnchorIdlVersion(String anchorIdlVersion) {
        this.anchorIdlVersion = anchorIdlVersion;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.anchor_idl_hash</code>.
     */
    public String getAnchorIdlHash() {
        return this.anchorIdlHash;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.anchor_idl_hash</code>.
     */
    public void setAnchorIdlHash(String anchorIdlHash) {
        this.anchorIdlHash = anchorIdlHash;
    }

    /**
     * Getter for
     * <code>eh8s_onchain.chain_config.instruction_registry_json</code>.
     */
    public String getInstructionRegistryJson() {
        return this.instructionRegistryJson;
    }

    /**
     * Setter for
     * <code>eh8s_onchain.chain_config.instruction_registry_json</code>.
     */
    public void setInstructionRegistryJson(String instructionRegistryJson) {
        this.instructionRegistryJson = instructionRegistryJson;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.program_deployed_at</code>.
     */
    public LocalDateTime getProgramDeployedAt() {
        return this.programDeployedAt;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.program_deployed_at</code>.
     */
    public void setProgramDeployedAt(LocalDateTime programDeployedAt) {
        this.programDeployedAt = programDeployedAt;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.usdc_mint</code>.
     */
    public String getUsdcMint() {
        return this.usdcMint;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.usdc_mint</code>.
     */
    public void setUsdcMint(String usdcMint) {
        this.usdcMint = usdcMint;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.env_network_key</code>.
     */
    public String getEnvNetworkKey() {
        return this.envNetworkKey;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.env_network_key</code>.
     */
    public void setEnvNetworkKey(String envNetworkKey) {
        this.envNetworkKey = envNetworkKey;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.env_rpc_key</code>.
     */
    public String getEnvRpcKey() {
        return this.envRpcKey;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.env_rpc_key</code>.
     */
    public void setEnvRpcKey(String envRpcKey) {
        this.envRpcKey = envRpcKey;
    }

    /**
     * Getter for
     * <code>eh8s_onchain.chain_config.env_program_id_devnet_key</code>.
     */
    public String getEnvProgramIdDevnetKey() {
        return this.envProgramIdDevnetKey;
    }

    /**
     * Setter for
     * <code>eh8s_onchain.chain_config.env_program_id_devnet_key</code>.
     */
    public void setEnvProgramIdDevnetKey(String envProgramIdDevnetKey) {
        this.envProgramIdDevnetKey = envProgramIdDevnetKey;
    }

    /**
     * Getter for
     * <code>eh8s_onchain.chain_config.env_program_id_mainnet_key</code>.
     */
    public String getEnvProgramIdMainnetKey() {
        return this.envProgramIdMainnetKey;
    }

    /**
     * Setter for
     * <code>eh8s_onchain.chain_config.env_program_id_mainnet_key</code>.
     */
    public void setEnvProgramIdMainnetKey(String envProgramIdMainnetKey) {
        this.envProgramIdMainnetKey = envProgramIdMainnetKey;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.bags_api_base</code>.
     */
    public String getBagsApiBase() {
        return this.bagsApiBase;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.bags_api_base</code>.
     */
    public void setBagsApiBase(String bagsApiBase) {
        this.bagsApiBase = bagsApiBase;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.watcher_url</code>.
     */
    public String getWatcherUrl() {
        return this.watcherUrl;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.watcher_url</code>.
     */
    public void setWatcherUrl(String watcherUrl) {
        this.watcherUrl = watcherUrl;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.squads_multisig</code>.
     */
    public String getSquadsMultisig() {
        return this.squadsMultisig;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.squads_multisig</code>.
     */
    public void setSquadsMultisig(String squadsMultisig) {
        this.squadsMultisig = squadsMultisig;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.owner_wallet_pubkey</code>.
     */
    public String getOwnerWalletPubkey() {
        return this.ownerWalletPubkey;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.owner_wallet_pubkey</code>.
     */
    public void setOwnerWalletPubkey(String ownerWalletPubkey) {
        this.ownerWalletPubkey = ownerWalletPubkey;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.protocol_fee_bps</code>.
     */
    public Integer getProtocolFeeBps() {
        return this.protocolFeeBps;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.protocol_fee_bps</code>.
     */
    public void setProtocolFeeBps(Integer protocolFeeBps) {
        this.protocolFeeBps = protocolFeeBps;
    }

    /**
     * Getter for <code>eh8s_onchain.chain_config.is_active</code>.
     */
    public Byte getIsActive() {
        return this.isActive;
    }

    /**
     * Setter for <code>eh8s_onchain.chain_config.is_active</code>.
     */
    public void setIsActive(Byte isActive) {
        this.isActive = isActive;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChainConfig other = (ChainConfig) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.network == null) {
            if (other.network != null)
                return false;
        }
        else if (!this.network.equals(other.network))
            return false;
        if (this.rpcUrl == null) {
            if (other.rpcUrl != null)
                return false;
        }
        else if (!this.rpcUrl.equals(other.rpcUrl))
            return false;
        if (this.programIdDevnet == null) {
            if (other.programIdDevnet != null)
                return false;
        }
        else if (!this.programIdDevnet.equals(other.programIdDevnet))
            return false;
        if (this.programIdMainnet == null) {
            if (other.programIdMainnet != null)
                return false;
        }
        else if (!this.programIdMainnet.equals(other.programIdMainnet))
            return false;
        if (this.anchorProgramName == null) {
            if (other.anchorProgramName != null)
                return false;
        }
        else if (!this.anchorProgramName.equals(other.anchorProgramName))
            return false;
        if (this.anchorScaffoldPath == null) {
            if (other.anchorScaffoldPath != null)
                return false;
        }
        else if (!this.anchorScaffoldPath.equals(other.anchorScaffoldPath))
            return false;
        if (this.anchorIdlVersion == null) {
            if (other.anchorIdlVersion != null)
                return false;
        }
        else if (!this.anchorIdlVersion.equals(other.anchorIdlVersion))
            return false;
        if (this.anchorIdlHash == null) {
            if (other.anchorIdlHash != null)
                return false;
        }
        else if (!this.anchorIdlHash.equals(other.anchorIdlHash))
            return false;
        if (this.instructionRegistryJson == null) {
            if (other.instructionRegistryJson != null)
                return false;
        }
        else if (!this.instructionRegistryJson.equals(other.instructionRegistryJson))
            return false;
        if (this.programDeployedAt == null) {
            if (other.programDeployedAt != null)
                return false;
        }
        else if (!this.programDeployedAt.equals(other.programDeployedAt))
            return false;
        if (this.usdcMint == null) {
            if (other.usdcMint != null)
                return false;
        }
        else if (!this.usdcMint.equals(other.usdcMint))
            return false;
        if (this.envNetworkKey == null) {
            if (other.envNetworkKey != null)
                return false;
        }
        else if (!this.envNetworkKey.equals(other.envNetworkKey))
            return false;
        if (this.envRpcKey == null) {
            if (other.envRpcKey != null)
                return false;
        }
        else if (!this.envRpcKey.equals(other.envRpcKey))
            return false;
        if (this.envProgramIdDevnetKey == null) {
            if (other.envProgramIdDevnetKey != null)
                return false;
        }
        else if (!this.envProgramIdDevnetKey.equals(other.envProgramIdDevnetKey))
            return false;
        if (this.envProgramIdMainnetKey == null) {
            if (other.envProgramIdMainnetKey != null)
                return false;
        }
        else if (!this.envProgramIdMainnetKey.equals(other.envProgramIdMainnetKey))
            return false;
        if (this.bagsApiBase == null) {
            if (other.bagsApiBase != null)
                return false;
        }
        else if (!this.bagsApiBase.equals(other.bagsApiBase))
            return false;
        if (this.watcherUrl == null) {
            if (other.watcherUrl != null)
                return false;
        }
        else if (!this.watcherUrl.equals(other.watcherUrl))
            return false;
        if (this.squadsMultisig == null) {
            if (other.squadsMultisig != null)
                return false;
        }
        else if (!this.squadsMultisig.equals(other.squadsMultisig))
            return false;
        if (this.ownerWalletPubkey == null) {
            if (other.ownerWalletPubkey != null)
                return false;
        }
        else if (!this.ownerWalletPubkey.equals(other.ownerWalletPubkey))
            return false;
        if (this.protocolFeeBps == null) {
            if (other.protocolFeeBps != null)
                return false;
        }
        else if (!this.protocolFeeBps.equals(other.protocolFeeBps))
            return false;
        if (this.isActive == null) {
            if (other.isActive != null)
                return false;
        }
        else if (!this.isActive.equals(other.isActive))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.network == null) ? 0 : this.network.hashCode());
        result = prime * result + ((this.rpcUrl == null) ? 0 : this.rpcUrl.hashCode());
        result = prime * result + ((this.programIdDevnet == null) ? 0 : this.programIdDevnet.hashCode());
        result = prime * result + ((this.programIdMainnet == null) ? 0 : this.programIdMainnet.hashCode());
        result = prime * result + ((this.anchorProgramName == null) ? 0 : this.anchorProgramName.hashCode());
        result = prime * result + ((this.anchorScaffoldPath == null) ? 0 : this.anchorScaffoldPath.hashCode());
        result = prime * result + ((this.anchorIdlVersion == null) ? 0 : this.anchorIdlVersion.hashCode());
        result = prime * result + ((this.anchorIdlHash == null) ? 0 : this.anchorIdlHash.hashCode());
        result = prime * result + ((this.instructionRegistryJson == null) ? 0 : this.instructionRegistryJson.hashCode());
        result = prime * result + ((this.programDeployedAt == null) ? 0 : this.programDeployedAt.hashCode());
        result = prime * result + ((this.usdcMint == null) ? 0 : this.usdcMint.hashCode());
        result = prime * result + ((this.envNetworkKey == null) ? 0 : this.envNetworkKey.hashCode());
        result = prime * result + ((this.envRpcKey == null) ? 0 : this.envRpcKey.hashCode());
        result = prime * result + ((this.envProgramIdDevnetKey == null) ? 0 : this.envProgramIdDevnetKey.hashCode());
        result = prime * result + ((this.envProgramIdMainnetKey == null) ? 0 : this.envProgramIdMainnetKey.hashCode());
        result = prime * result + ((this.bagsApiBase == null) ? 0 : this.bagsApiBase.hashCode());
        result = prime * result + ((this.watcherUrl == null) ? 0 : this.watcherUrl.hashCode());
        result = prime * result + ((this.squadsMultisig == null) ? 0 : this.squadsMultisig.hashCode());
        result = prime * result + ((this.ownerWalletPubkey == null) ? 0 : this.ownerWalletPubkey.hashCode());
        result = prime * result + ((this.protocolFeeBps == null) ? 0 : this.protocolFeeBps.hashCode());
        result = prime * result + ((this.isActive == null) ? 0 : this.isActive.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChainConfig (");

        sb.append(id);
        sb.append(", ").append(network);
        sb.append(", ").append(rpcUrl);
        sb.append(", ").append(programIdDevnet);
        sb.append(", ").append(programIdMainnet);
        sb.append(", ").append(anchorProgramName);
        sb.append(", ").append(anchorScaffoldPath);
        sb.append(", ").append(anchorIdlVersion);
        sb.append(", ").append(anchorIdlHash);
        sb.append(", ").append(instructionRegistryJson);
        sb.append(", ").append(programDeployedAt);
        sb.append(", ").append(usdcMint);
        sb.append(", ").append(envNetworkKey);
        sb.append(", ").append(envRpcKey);
        sb.append(", ").append(envProgramIdDevnetKey);
        sb.append(", ").append(envProgramIdMainnetKey);
        sb.append(", ").append(bagsApiBase);
        sb.append(", ").append(watcherUrl);
        sb.append(", ").append(squadsMultisig);
        sb.append(", ").append(ownerWalletPubkey);
        sb.append(", ").append(protocolFeeBps);
        sb.append(", ").append(isActive);

        sb.append(")");
        return sb.toString();
    }
}
