/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GovernanceProposal implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long governanceId;
    private Long onchainProposalId;
    private String proposalPda;
    private Integer epoch;
    private String kind;
    private String proposerWallet;
    private BigDecimal amountUsdc;
    private String targetPubkey;
    private Byte permissions;
    private String agentCode;
    private String newSignersCsv;
    private Byte newThreshold;
    private String status;
    private String proposeTxSignature;
    private String executeTxSignature;
    private String executedByWallet;
    private LocalDateTime createdAt;
    private LocalDateTime executedAt;

    public GovernanceProposal() {}

    public GovernanceProposal(GovernanceProposal value) {
        this.id = value.id;
        this.governanceId = value.governanceId;
        this.onchainProposalId = value.onchainProposalId;
        this.proposalPda = value.proposalPda;
        this.epoch = value.epoch;
        this.kind = value.kind;
        this.proposerWallet = value.proposerWallet;
        this.amountUsdc = value.amountUsdc;
        this.targetPubkey = value.targetPubkey;
        this.permissions = value.permissions;
        this.agentCode = value.agentCode;
        this.newSignersCsv = value.newSignersCsv;
        this.newThreshold = value.newThreshold;
        this.status = value.status;
        this.proposeTxSignature = value.proposeTxSignature;
        this.executeTxSignature = value.executeTxSignature;
        this.executedByWallet = value.executedByWallet;
        this.createdAt = value.createdAt;
        this.executedAt = value.executedAt;
    }

    public GovernanceProposal(
        Long id,
        Long governanceId,
        Long onchainProposalId,
        String proposalPda,
        Integer epoch,
        String kind,
        String proposerWallet,
        BigDecimal amountUsdc,
        String targetPubkey,
        Byte permissions,
        String agentCode,
        String newSignersCsv,
        Byte newThreshold,
        String status,
        String proposeTxSignature,
        String executeTxSignature,
        String executedByWallet,
        LocalDateTime createdAt,
        LocalDateTime executedAt
    ) {
        this.id = id;
        this.governanceId = governanceId;
        this.onchainProposalId = onchainProposalId;
        this.proposalPda = proposalPda;
        this.epoch = epoch;
        this.kind = kind;
        this.proposerWallet = proposerWallet;
        this.amountUsdc = amountUsdc;
        this.targetPubkey = targetPubkey;
        this.permissions = permissions;
        this.agentCode = agentCode;
        this.newSignersCsv = newSignersCsv;
        this.newThreshold = newThreshold;
        this.status = status;
        this.proposeTxSignature = proposeTxSignature;
        this.executeTxSignature = executeTxSignature;
        this.executedByWallet = executedByWallet;
        this.createdAt = createdAt;
        this.executedAt = executedAt;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.governance_id</code>.
     */
    public Long getGovernanceId() {
        return this.governanceId;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.governance_id</code>.
     */
    public void setGovernanceId(Long governanceId) {
        this.governanceId = governanceId;
    }

    /**
     * Getter for
     * <code>eh8s_onchain.governance_proposal.onchain_proposal_id</code>.
     */
    public Long getOnchainProposalId() {
        return this.onchainProposalId;
    }

    /**
     * Setter for
     * <code>eh8s_onchain.governance_proposal.onchain_proposal_id</code>.
     */
    public void setOnchainProposalId(Long onchainProposalId) {
        this.onchainProposalId = onchainProposalId;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.proposal_pda</code>.
     */
    public String getProposalPda() {
        return this.proposalPda;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.proposal_pda</code>.
     */
    public void setProposalPda(String proposalPda) {
        this.proposalPda = proposalPda;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.epoch</code>.
     */
    public Integer getEpoch() {
        return this.epoch;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.epoch</code>.
     */
    public void setEpoch(Integer epoch) {
        this.epoch = epoch;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.kind</code>.
     */
    public String getKind() {
        return this.kind;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.kind</code>.
     */
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.proposer_wallet</code>.
     */
    public String getProposerWallet() {
        return this.proposerWallet;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.proposer_wallet</code>.
     */
    public void setProposerWallet(String proposerWallet) {
        this.proposerWallet = proposerWallet;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.amount_usdc</code>.
     */
    public BigDecimal getAmountUsdc() {
        return this.amountUsdc;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.amount_usdc</code>.
     */
    public void setAmountUsdc(BigDecimal amountUsdc) {
        this.amountUsdc = amountUsdc;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.target_pubkey</code>.
     */
    public String getTargetPubkey() {
        return this.targetPubkey;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.target_pubkey</code>.
     */
    public void setTargetPubkey(String targetPubkey) {
        this.targetPubkey = targetPubkey;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.permissions</code>.
     */
    public Byte getPermissions() {
        return this.permissions;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.permissions</code>.
     */
    public void setPermissions(Byte permissions) {
        this.permissions = permissions;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.agent_code</code>.
     */
    public String getAgentCode() {
        return this.agentCode;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.agent_code</code>.
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.new_signers_csv</code>.
     */
    public String getNewSignersCsv() {
        return this.newSignersCsv;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.new_signers_csv</code>.
     */
    public void setNewSignersCsv(String newSignersCsv) {
        this.newSignersCsv = newSignersCsv;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.new_threshold</code>.
     */
    public Byte getNewThreshold() {
        return this.newThreshold;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.new_threshold</code>.
     */
    public void setNewThreshold(Byte newThreshold) {
        this.newThreshold = newThreshold;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for
     * <code>eh8s_onchain.governance_proposal.propose_tx_signature</code>.
     */
    public String getProposeTxSignature() {
        return this.proposeTxSignature;
    }

    /**
     * Setter for
     * <code>eh8s_onchain.governance_proposal.propose_tx_signature</code>.
     */
    public void setProposeTxSignature(String proposeTxSignature) {
        this.proposeTxSignature = proposeTxSignature;
    }

    /**
     * Getter for
     * <code>eh8s_onchain.governance_proposal.execute_tx_signature</code>.
     */
    public String getExecuteTxSignature() {
        return this.executeTxSignature;
    }

    /**
     * Setter for
     * <code>eh8s_onchain.governance_proposal.execute_tx_signature</code>.
     */
    public void setExecuteTxSignature(String executeTxSignature) {
        this.executeTxSignature = executeTxSignature;
    }

    /**
     * Getter for
     * <code>eh8s_onchain.governance_proposal.executed_by_wallet</code>.
     */
    public String getExecutedByWallet() {
        return this.executedByWallet;
    }

    /**
     * Setter for
     * <code>eh8s_onchain.governance_proposal.executed_by_wallet</code>.
     */
    public void setExecutedByWallet(String executedByWallet) {
        this.executedByWallet = executedByWallet;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.executed_at</code>.
     */
    public LocalDateTime getExecutedAt() {
        return this.executedAt;
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.executed_at</code>.
     */
    public void setExecutedAt(LocalDateTime executedAt) {
        this.executedAt = executedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GovernanceProposal other = (GovernanceProposal) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.governanceId == null) {
            if (other.governanceId != null)
                return false;
        }
        else if (!this.governanceId.equals(other.governanceId))
            return false;
        if (this.onchainProposalId == null) {
            if (other.onchainProposalId != null)
                return false;
        }
        else if (!this.onchainProposalId.equals(other.onchainProposalId))
            return false;
        if (this.proposalPda == null) {
            if (other.proposalPda != null)
                return false;
        }
        else if (!this.proposalPda.equals(other.proposalPda))
            return false;
        if (this.epoch == null) {
            if (other.epoch != null)
                return false;
        }
        else if (!this.epoch.equals(other.epoch))
            return false;
        if (this.kind == null) {
            if (other.kind != null)
                return false;
        }
        else if (!this.kind.equals(other.kind))
            return false;
        if (this.proposerWallet == null) {
            if (other.proposerWallet != null)
                return false;
        }
        else if (!this.proposerWallet.equals(other.proposerWallet))
            return false;
        if (this.amountUsdc == null) {
            if (other.amountUsdc != null)
                return false;
        }
        else if (!this.amountUsdc.equals(other.amountUsdc))
            return false;
        if (this.targetPubkey == null) {
            if (other.targetPubkey != null)
                return false;
        }
        else if (!this.targetPubkey.equals(other.targetPubkey))
            return false;
        if (this.permissions == null) {
            if (other.permissions != null)
                return false;
        }
        else if (!this.permissions.equals(other.permissions))
            return false;
        if (this.agentCode == null) {
            if (other.agentCode != null)
                return false;
        }
        else if (!this.agentCode.equals(other.agentCode))
            return false;
        if (this.newSignersCsv == null) {
            if (other.newSignersCsv != null)
                return false;
        }
        else if (!this.newSignersCsv.equals(other.newSignersCsv))
            return false;
        if (this.newThreshold == null) {
            if (other.newThreshold != null)
                return false;
        }
        else if (!this.newThreshold.equals(other.newThreshold))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.proposeTxSignature == null) {
            if (other.proposeTxSignature != null)
                return false;
        }
        else if (!this.proposeTxSignature.equals(other.proposeTxSignature))
            return false;
        if (this.executeTxSignature == null) {
            if (other.executeTxSignature != null)
                return false;
        }
        else if (!this.executeTxSignature.equals(other.executeTxSignature))
            return false;
        if (this.executedByWallet == null) {
            if (other.executedByWallet != null)
                return false;
        }
        else if (!this.executedByWallet.equals(other.executedByWallet))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.executedAt == null) {
            if (other.executedAt != null)
                return false;
        }
        else if (!this.executedAt.equals(other.executedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.governanceId == null) ? 0 : this.governanceId.hashCode());
        result = prime * result + ((this.onchainProposalId == null) ? 0 : this.onchainProposalId.hashCode());
        result = prime * result + ((this.proposalPda == null) ? 0 : this.proposalPda.hashCode());
        result = prime * result + ((this.epoch == null) ? 0 : this.epoch.hashCode());
        result = prime * result + ((this.kind == null) ? 0 : this.kind.hashCode());
        result = prime * result + ((this.proposerWallet == null) ? 0 : this.proposerWallet.hashCode());
        result = prime * result + ((this.amountUsdc == null) ? 0 : this.amountUsdc.hashCode());
        result = prime * result + ((this.targetPubkey == null) ? 0 : this.targetPubkey.hashCode());
        result = prime * result + ((this.permissions == null) ? 0 : this.permissions.hashCode());
        result = prime * result + ((this.agentCode == null) ? 0 : this.agentCode.hashCode());
        result = prime * result + ((this.newSignersCsv == null) ? 0 : this.newSignersCsv.hashCode());
        result = prime * result + ((this.newThreshold == null) ? 0 : this.newThreshold.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.proposeTxSignature == null) ? 0 : this.proposeTxSignature.hashCode());
        result = prime * result + ((this.executeTxSignature == null) ? 0 : this.executeTxSignature.hashCode());
        result = prime * result + ((this.executedByWallet == null) ? 0 : this.executedByWallet.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.executedAt == null) ? 0 : this.executedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GovernanceProposal (");

        sb.append(id);
        sb.append(", ").append(governanceId);
        sb.append(", ").append(onchainProposalId);
        sb.append(", ").append(proposalPda);
        sb.append(", ").append(epoch);
        sb.append(", ").append(kind);
        sb.append(", ").append(proposerWallet);
        sb.append(", ").append(amountUsdc);
        sb.append(", ").append(targetPubkey);
        sb.append(", ").append(permissions);
        sb.append(", ").append(agentCode);
        sb.append(", ").append(newSignersCsv);
        sb.append(", ").append(newThreshold);
        sb.append(", ").append(status);
        sb.append(", ").append(proposeTxSignature);
        sb.append(", ").append(executeTxSignature);
        sb.append(", ").append(executedByWallet);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(executedAt);

        sb.append(")");
        return sb.toString();
    }
}
