/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_role.tables;


import com.eh8s.eh8s.database.jooq.eh8s.tables.Account.AccountPath;
import com.eh8s.eh8s.database.jooq.eh8s_role.Eh8sRole;
import com.eh8s.eh8s.database.jooq.eh8s_role.Indexes;
import com.eh8s.eh8s.database.jooq.eh8s_role.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_role.tables.AccountRole.AccountRolePath;
import com.eh8s.eh8s.database.jooq.eh8s_role.tables.records.AccountRoleApplicationRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRoleApplication extends TableImpl<AccountRoleApplicationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_role.account_role_application</code>
     */
    public static final AccountRoleApplication ACCOUNT_ROLE_APPLICATION = new AccountRoleApplication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRoleApplicationRecord> getRecordType() {
        return AccountRoleApplicationRecord.class;
    }

    /**
     * The column <code>eh8s_role.account_role_application.id</code>.
     */
    public final TableField<AccountRoleApplicationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s_role.account_role_application.account_id</code>.
     */
    public final TableField<AccountRoleApplicationRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_role.account_role_application.wallet_pubkey</code>.
     */
    public final TableField<AccountRoleApplicationRecord, String> WALLET_PUBKEY = createField(DSL.name("wallet_pubkey"), SQLDataType.VARCHAR(44).nullable(false), this, "");

    /**
     * The column <code>eh8s_role.account_role_application.role</code>.
     */
    public final TableField<AccountRoleApplicationRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>eh8s_role.account_role_application.status</code>.
     */
    public final TableField<AccountRoleApplicationRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'pending'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_role.account_role_application.reason</code>.
     */
    public final TableField<AccountRoleApplicationRecord, String> REASON = createField(DSL.name("reason"), SQLDataType.VARCHAR(500).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>eh8s_role.account_role_application.reviewed_by_wallet</code>.
     */
    public final TableField<AccountRoleApplicationRecord, String> REVIEWED_BY_WALLET = createField(DSL.name("reviewed_by_wallet"), SQLDataType.VARCHAR(44).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_role.account_role_application.created_at</code>.
     */
    public final TableField<AccountRoleApplicationRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>eh8s_role.account_role_application.reviewed_at</code>.
     */
    public final TableField<AccountRoleApplicationRecord, LocalDateTime> REVIEWED_AT = createField(DSL.name("reviewed_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    private AccountRoleApplication(Name alias, Table<AccountRoleApplicationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AccountRoleApplication(Name alias, Table<AccountRoleApplicationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_role.account_role_application</code> table
     * reference
     */
    public AccountRoleApplication(String alias) {
        this(DSL.name(alias), ACCOUNT_ROLE_APPLICATION);
    }

    /**
     * Create an aliased <code>eh8s_role.account_role_application</code> table
     * reference
     */
    public AccountRoleApplication(Name alias) {
        this(alias, ACCOUNT_ROLE_APPLICATION);
    }

    /**
     * Create a <code>eh8s_role.account_role_application</code> table reference
     */
    public AccountRoleApplication() {
        this(DSL.name("account_role_application"), null);
    }

    public <O extends Record> AccountRoleApplication(Table<O> path, ForeignKey<O, AccountRoleApplicationRecord> childPath, InverseForeignKey<O, AccountRoleApplicationRecord> parentPath) {
        super(path, childPath, parentPath, ACCOUNT_ROLE_APPLICATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AccountRoleApplicationPath extends AccountRoleApplication implements Path<AccountRoleApplicationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AccountRoleApplicationPath(Table<O> path, ForeignKey<O, AccountRoleApplicationRecord> childPath, InverseForeignKey<O, AccountRoleApplicationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AccountRoleApplicationPath(Name alias, Table<AccountRoleApplicationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AccountRoleApplicationPath as(String alias) {
            return new AccountRoleApplicationPath(DSL.name(alias), this);
        }

        @Override
        public AccountRoleApplicationPath as(Name alias) {
            return new AccountRoleApplicationPath(alias, this);
        }

        @Override
        public AccountRoleApplicationPath as(Table<?> alias) {
            return new AccountRoleApplicationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sRole.EH8S_ROLE;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.ACCOUNT_ROLE_APPLICATION_IDX_ROLE_APP_STATUS, Indexes.ACCOUNT_ROLE_APPLICATION_IDX_ROLE_APP_WALLET);
    }

    @Override
    public Identity<AccountRoleApplicationRecord, Long> getIdentity() {
        return (Identity<AccountRoleApplicationRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AccountRoleApplicationRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_ROLE_APPLICATION_PRIMARY;
    }

    @Override
    public List<UniqueKey<AccountRoleApplicationRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ACCOUNT_ROLE_APPLICATION_UK_ROLE_APP_ACCOUNT_ROLE, Keys.KEY_ACCOUNT_ROLE_APPLICATION_UK_ROLE_APP_WALLET_ROLE);
    }

    @Override
    public List<ForeignKey<AccountRoleApplicationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_ROLE_APP_ACCOUNT);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>eh8s.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_ROLE_APP_ACCOUNT, null);

        return _account;
    }

    private transient AccountRolePath _accountRole;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s_role.account_role</code> table
     */
    public AccountRolePath accountRole() {
        if (_accountRole == null)
            _accountRole = new AccountRolePath(this, null, Keys.FK_ACCOUNT_ROLE_APPLICATION.getInverseKey());

        return _accountRole;
    }

    @Override
    public List<Check<AccountRoleApplicationRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("chk_role_app_role"), "`role` in ('student','musician','instructor','venue')", true),
            Internal.createCheck(this, DSL.name("chk_role_app_status"), "`status` in ('pending','approved','rejected')", true)
        );
    }

    @Override
    public AccountRoleApplication as(String alias) {
        return new AccountRoleApplication(DSL.name(alias), this);
    }

    @Override
    public AccountRoleApplication as(Name alias) {
        return new AccountRoleApplication(alias, this);
    }

    @Override
    public AccountRoleApplication as(Table<?> alias) {
        return new AccountRoleApplication(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRoleApplication rename(String name) {
        return new AccountRoleApplication(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRoleApplication rename(Name name) {
        return new AccountRoleApplication(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRoleApplication rename(Table<?> name) {
        return new AccountRoleApplication(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountRoleApplication where(Condition condition) {
        return new AccountRoleApplication(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountRoleApplication where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountRoleApplication where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountRoleApplication where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountRoleApplication where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountRoleApplication where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountRoleApplication where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AccountRoleApplication where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountRoleApplication whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AccountRoleApplication whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
