/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_ops.tables;


import com.eh8s.eh8s.database.jooq.eh8s_ops.Eh8sOps;
import com.eh8s.eh8s.database.jooq.eh8s_ops.Indexes;
import com.eh8s.eh8s.database.jooq.eh8s_ops.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_ops.tables.OpsAgent.OpsAgentPath;
import com.eh8s.eh8s.database.jooq.eh8s_ops.tables.records.AgentAuthorityRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentAuthority extends TableImpl<AgentAuthorityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_ops.agent_authority</code>
     */
    public static final AgentAuthority AGENT_AUTHORITY = new AgentAuthority();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AgentAuthorityRecord> getRecordType() {
        return AgentAuthorityRecord.class;
    }

    /**
     * The column <code>eh8s_ops.agent_authority.id</code>.
     */
    public final TableField<AgentAuthorityRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s_ops.agent_authority.ops_agent_id</code>.
     */
    public final TableField<AgentAuthorityRecord, Long> OPS_AGENT_ID = createField(DSL.name("ops_agent_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_ops.agent_authority.agent_wallet_pubkey</code>.
     */
    public final TableField<AgentAuthorityRecord, String> AGENT_WALLET_PUBKEY = createField(DSL.name("agent_wallet_pubkey"), SQLDataType.VARCHAR(44).nullable(false), this, "");

    /**
     * The column <code>eh8s_ops.agent_authority.permissions</code>.
     */
    public final TableField<AgentAuthorityRecord, Byte> PERMISSIONS = createField(DSL.name("permissions"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_ops.agent_authority.agent_authority_pda</code>.
     */
    public final TableField<AgentAuthorityRecord, String> AGENT_AUTHORITY_PDA = createField(DSL.name("agent_authority_pda"), SQLDataType.VARCHAR(44).nullable(false), this, "");

    /**
     * The column <code>eh8s_ops.agent_authority.owner_wallet_pubkey</code>.
     */
    public final TableField<AgentAuthorityRecord, String> OWNER_WALLET_PUBKEY = createField(DSL.name("owner_wallet_pubkey"), SQLDataType.VARCHAR(44).nullable(false), this, "");

    /**
     * The column <code>eh8s_ops.agent_authority.tx_signature</code>.
     */
    public final TableField<AgentAuthorityRecord, String> TX_SIGNATURE = createField(DSL.name("tx_signature"), SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>eh8s_ops.agent_authority.created_at</code>.
     */
    public final TableField<AgentAuthorityRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false), this, "");

    private AgentAuthority(Name alias, Table<AgentAuthorityRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AgentAuthority(Name alias, Table<AgentAuthorityRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_ops.agent_authority</code> table reference
     */
    public AgentAuthority(String alias) {
        this(DSL.name(alias), AGENT_AUTHORITY);
    }

    /**
     * Create an aliased <code>eh8s_ops.agent_authority</code> table reference
     */
    public AgentAuthority(Name alias) {
        this(alias, AGENT_AUTHORITY);
    }

    /**
     * Create a <code>eh8s_ops.agent_authority</code> table reference
     */
    public AgentAuthority() {
        this(DSL.name("agent_authority"), null);
    }

    public <O extends Record> AgentAuthority(Table<O> path, ForeignKey<O, AgentAuthorityRecord> childPath, InverseForeignKey<O, AgentAuthorityRecord> parentPath) {
        super(path, childPath, parentPath, AGENT_AUTHORITY);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class AgentAuthorityPath extends AgentAuthority implements Path<AgentAuthorityRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> AgentAuthorityPath(Table<O> path, ForeignKey<O, AgentAuthorityRecord> childPath, InverseForeignKey<O, AgentAuthorityRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private AgentAuthorityPath(Name alias, Table<AgentAuthorityRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public AgentAuthorityPath as(String alias) {
            return new AgentAuthorityPath(DSL.name(alias), this);
        }

        @Override
        public AgentAuthorityPath as(Name alias) {
            return new AgentAuthorityPath(alias, this);
        }

        @Override
        public AgentAuthorityPath as(Table<?> alias) {
            return new AgentAuthorityPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sOps.EH8S_OPS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.AGENT_AUTHORITY_IDX_AGENT_AUTHORITY_WALLET);
    }

    @Override
    public Identity<AgentAuthorityRecord, Long> getIdentity() {
        return (Identity<AgentAuthorityRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AgentAuthorityRecord> getPrimaryKey() {
        return Keys.KEY_AGENT_AUTHORITY_PRIMARY;
    }

    @Override
    public List<UniqueKey<AgentAuthorityRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_AGENT_AUTHORITY_UK_AGENT_AUTHORITY_TX);
    }

    @Override
    public List<ForeignKey<AgentAuthorityRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_AGENT_AUTHORITY_AGENT);
    }

    private transient OpsAgentPath _opsAgent;

    /**
     * Get the implicit join path to the <code>eh8s_ops.ops_agent</code> table.
     */
    public OpsAgentPath opsAgent() {
        if (_opsAgent == null)
            _opsAgent = new OpsAgentPath(this, Keys.FK_AGENT_AUTHORITY_AGENT, null);

        return _opsAgent;
    }

    @Override
    public AgentAuthority as(String alias) {
        return new AgentAuthority(DSL.name(alias), this);
    }

    @Override
    public AgentAuthority as(Name alias) {
        return new AgentAuthority(alias, this);
    }

    @Override
    public AgentAuthority as(Table<?> alias) {
        return new AgentAuthority(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentAuthority rename(String name) {
        return new AgentAuthority(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentAuthority rename(Name name) {
        return new AgentAuthority(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AgentAuthority rename(Table<?> name) {
        return new AgentAuthority(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentAuthority where(Condition condition) {
        return new AgentAuthority(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentAuthority where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentAuthority where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentAuthority where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentAuthority where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentAuthority where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentAuthority where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AgentAuthority where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentAuthority whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AgentAuthority whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
