/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BandMatchSuggestion implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long bandId;
    private Long musicianProfileId;
    private Byte score;
    private Byte instrumentPoints;
    private Byte levelPoints;
    private Byte countryPoints;
    private Byte genrePoints;
    private String reason;
    private String aiRationale;
    private String status;
    private LocalDateTime createdAt;

    public BandMatchSuggestion() {}

    public BandMatchSuggestion(BandMatchSuggestion value) {
        this.id = value.id;
        this.bandId = value.bandId;
        this.musicianProfileId = value.musicianProfileId;
        this.score = value.score;
        this.instrumentPoints = value.instrumentPoints;
        this.levelPoints = value.levelPoints;
        this.countryPoints = value.countryPoints;
        this.genrePoints = value.genrePoints;
        this.reason = value.reason;
        this.aiRationale = value.aiRationale;
        this.status = value.status;
        this.createdAt = value.createdAt;
    }

    public BandMatchSuggestion(
        Long id,
        Long bandId,
        Long musicianProfileId,
        Byte score,
        Byte instrumentPoints,
        Byte levelPoints,
        Byte countryPoints,
        Byte genrePoints,
        String reason,
        String aiRationale,
        String status,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.bandId = bandId;
        this.musicianProfileId = musicianProfileId;
        this.score = score;
        this.instrumentPoints = instrumentPoints;
        this.levelPoints = levelPoints;
        this.countryPoints = countryPoints;
        this.genrePoints = genrePoints;
        this.reason = reason;
        this.aiRationale = aiRationale;
        this.status = status;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.band_id</code>.
     */
    public Long getBandId() {
        return this.bandId;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.band_id</code>.
     */
    public void setBandId(Long bandId) {
        this.bandId = bandId;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.musician_profile_id</code>.
     */
    public Long getMusicianProfileId() {
        return this.musicianProfileId;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.musician_profile_id</code>.
     */
    public void setMusicianProfileId(Long musicianProfileId) {
        this.musicianProfileId = musicianProfileId;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.score</code>.
     */
    public Byte getScore() {
        return this.score;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.score</code>.
     */
    public void setScore(Byte score) {
        this.score = score;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.instrument_points</code>.
     */
    public Byte getInstrumentPoints() {
        return this.instrumentPoints;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.instrument_points</code>.
     */
    public void setInstrumentPoints(Byte instrumentPoints) {
        this.instrumentPoints = instrumentPoints;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.level_points</code>.
     */
    public Byte getLevelPoints() {
        return this.levelPoints;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.level_points</code>.
     */
    public void setLevelPoints(Byte levelPoints) {
        this.levelPoints = levelPoints;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.country_points</code>.
     */
    public Byte getCountryPoints() {
        return this.countryPoints;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.country_points</code>.
     */
    public void setCountryPoints(Byte countryPoints) {
        this.countryPoints = countryPoints;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.genre_points</code>.
     */
    public Byte getGenrePoints() {
        return this.genrePoints;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.genre_points</code>.
     */
    public void setGenrePoints(Byte genrePoints) {
        this.genrePoints = genrePoints;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.reason</code>.
     */
    public String getReason() {
        return this.reason;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.reason</code>.
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.ai_rationale</code>.
     */
    public String getAiRationale() {
        return this.aiRationale;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.ai_rationale</code>.
     */
    public void setAiRationale(String aiRationale) {
        this.aiRationale = aiRationale;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>eh8s.band_match_suggestion.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>eh8s.band_match_suggestion.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BandMatchSuggestion other = (BandMatchSuggestion) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.bandId == null) {
            if (other.bandId != null)
                return false;
        }
        else if (!this.bandId.equals(other.bandId))
            return false;
        if (this.musicianProfileId == null) {
            if (other.musicianProfileId != null)
                return false;
        }
        else if (!this.musicianProfileId.equals(other.musicianProfileId))
            return false;
        if (this.score == null) {
            if (other.score != null)
                return false;
        }
        else if (!this.score.equals(other.score))
            return false;
        if (this.instrumentPoints == null) {
            if (other.instrumentPoints != null)
                return false;
        }
        else if (!this.instrumentPoints.equals(other.instrumentPoints))
            return false;
        if (this.levelPoints == null) {
            if (other.levelPoints != null)
                return false;
        }
        else if (!this.levelPoints.equals(other.levelPoints))
            return false;
        if (this.countryPoints == null) {
            if (other.countryPoints != null)
                return false;
        }
        else if (!this.countryPoints.equals(other.countryPoints))
            return false;
        if (this.genrePoints == null) {
            if (other.genrePoints != null)
                return false;
        }
        else if (!this.genrePoints.equals(other.genrePoints))
            return false;
        if (this.reason == null) {
            if (other.reason != null)
                return false;
        }
        else if (!this.reason.equals(other.reason))
            return false;
        if (this.aiRationale == null) {
            if (other.aiRationale != null)
                return false;
        }
        else if (!this.aiRationale.equals(other.aiRationale))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.bandId == null) ? 0 : this.bandId.hashCode());
        result = prime * result + ((this.musicianProfileId == null) ? 0 : this.musicianProfileId.hashCode());
        result = prime * result + ((this.score == null) ? 0 : this.score.hashCode());
        result = prime * result + ((this.instrumentPoints == null) ? 0 : this.instrumentPoints.hashCode());
        result = prime * result + ((this.levelPoints == null) ? 0 : this.levelPoints.hashCode());
        result = prime * result + ((this.countryPoints == null) ? 0 : this.countryPoints.hashCode());
        result = prime * result + ((this.genrePoints == null) ? 0 : this.genrePoints.hashCode());
        result = prime * result + ((this.reason == null) ? 0 : this.reason.hashCode());
        result = prime * result + ((this.aiRationale == null) ? 0 : this.aiRationale.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BandMatchSuggestion (");

        sb.append(id);
        sb.append(", ").append(bandId);
        sb.append(", ").append(musicianProfileId);
        sb.append(", ").append(score);
        sb.append(", ").append(instrumentPoints);
        sb.append(", ").append(levelPoints);
        sb.append(", ").append(countryPoints);
        sb.append(", ").append(genrePoints);
        sb.append(", ").append(reason);
        sb.append(", ").append(aiRationale);
        sb.append(", ").append(status);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
