/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConcertSetCheckin implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long concertId;
    private Long musicianProfileId;
    private LocalDateTime setStartedAt;
    private LocalDateTime setEndedAt;
    private Integer minutesPlayed;

    public ConcertSetCheckin() {}

    public ConcertSetCheckin(ConcertSetCheckin value) {
        this.id = value.id;
        this.concertId = value.concertId;
        this.musicianProfileId = value.musicianProfileId;
        this.setStartedAt = value.setStartedAt;
        this.setEndedAt = value.setEndedAt;
        this.minutesPlayed = value.minutesPlayed;
    }

    public ConcertSetCheckin(
        Long id,
        Long concertId,
        Long musicianProfileId,
        LocalDateTime setStartedAt,
        LocalDateTime setEndedAt,
        Integer minutesPlayed
    ) {
        this.id = id;
        this.concertId = concertId;
        this.musicianProfileId = musicianProfileId;
        this.setStartedAt = setStartedAt;
        this.setEndedAt = setEndedAt;
        this.minutesPlayed = minutesPlayed;
    }

    /**
     * Getter for <code>eh8s.concert_set_checkin.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.concert_set_checkin.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.concert_set_checkin.concert_id</code>.
     */
    public Long getConcertId() {
        return this.concertId;
    }

    /**
     * Setter for <code>eh8s.concert_set_checkin.concert_id</code>.
     */
    public void setConcertId(Long concertId) {
        this.concertId = concertId;
    }

    /**
     * Getter for <code>eh8s.concert_set_checkin.musician_profile_id</code>.
     */
    public Long getMusicianProfileId() {
        return this.musicianProfileId;
    }

    /**
     * Setter for <code>eh8s.concert_set_checkin.musician_profile_id</code>.
     */
    public void setMusicianProfileId(Long musicianProfileId) {
        this.musicianProfileId = musicianProfileId;
    }

    /**
     * Getter for <code>eh8s.concert_set_checkin.set_started_at</code>.
     */
    public LocalDateTime getSetStartedAt() {
        return this.setStartedAt;
    }

    /**
     * Setter for <code>eh8s.concert_set_checkin.set_started_at</code>.
     */
    public void setSetStartedAt(LocalDateTime setStartedAt) {
        this.setStartedAt = setStartedAt;
    }

    /**
     * Getter for <code>eh8s.concert_set_checkin.set_ended_at</code>.
     */
    public LocalDateTime getSetEndedAt() {
        return this.setEndedAt;
    }

    /**
     * Setter for <code>eh8s.concert_set_checkin.set_ended_at</code>.
     */
    public void setSetEndedAt(LocalDateTime setEndedAt) {
        this.setEndedAt = setEndedAt;
    }

    /**
     * Getter for <code>eh8s.concert_set_checkin.minutes_played</code>.
     */
    public Integer getMinutesPlayed() {
        return this.minutesPlayed;
    }

    /**
     * Setter for <code>eh8s.concert_set_checkin.minutes_played</code>.
     */
    public void setMinutesPlayed(Integer minutesPlayed) {
        this.minutesPlayed = minutesPlayed;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ConcertSetCheckin other = (ConcertSetCheckin) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.concertId == null) {
            if (other.concertId != null)
                return false;
        }
        else if (!this.concertId.equals(other.concertId))
            return false;
        if (this.musicianProfileId == null) {
            if (other.musicianProfileId != null)
                return false;
        }
        else if (!this.musicianProfileId.equals(other.musicianProfileId))
            return false;
        if (this.setStartedAt == null) {
            if (other.setStartedAt != null)
                return false;
        }
        else if (!this.setStartedAt.equals(other.setStartedAt))
            return false;
        if (this.setEndedAt == null) {
            if (other.setEndedAt != null)
                return false;
        }
        else if (!this.setEndedAt.equals(other.setEndedAt))
            return false;
        if (this.minutesPlayed == null) {
            if (other.minutesPlayed != null)
                return false;
        }
        else if (!this.minutesPlayed.equals(other.minutesPlayed))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.concertId == null) ? 0 : this.concertId.hashCode());
        result = prime * result + ((this.musicianProfileId == null) ? 0 : this.musicianProfileId.hashCode());
        result = prime * result + ((this.setStartedAt == null) ? 0 : this.setStartedAt.hashCode());
        result = prime * result + ((this.setEndedAt == null) ? 0 : this.setEndedAt.hashCode());
        result = prime * result + ((this.minutesPlayed == null) ? 0 : this.minutesPlayed.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConcertSetCheckin (");

        sb.append(id);
        sb.append(", ").append(concertId);
        sb.append(", ").append(musicianProfileId);
        sb.append(", ").append(setStartedAt);
        sb.append(", ").append(setEndedAt);
        sb.append(", ").append(minutesPlayed);

        sb.append(")");
        return sb.toString();
    }
}
