/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Concert implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long bookingId;
    private Long venueId;
    private Long bandId;
    private Long sppCycleId;
    private String status;
    private Integer showMinutes;
    private String concertSettlementPda;

    public Concert() {}

    public Concert(Concert value) {
        this.id = value.id;
        this.bookingId = value.bookingId;
        this.venueId = value.venueId;
        this.bandId = value.bandId;
        this.sppCycleId = value.sppCycleId;
        this.status = value.status;
        this.showMinutes = value.showMinutes;
        this.concertSettlementPda = value.concertSettlementPda;
    }

    public Concert(
        Long id,
        Long bookingId,
        Long venueId,
        Long bandId,
        Long sppCycleId,
        String status,
        Integer showMinutes,
        String concertSettlementPda
    ) {
        this.id = id;
        this.bookingId = bookingId;
        this.venueId = venueId;
        this.bandId = bandId;
        this.sppCycleId = sppCycleId;
        this.status = status;
        this.showMinutes = showMinutes;
        this.concertSettlementPda = concertSettlementPda;
    }

    /**
     * Getter for <code>eh8s.concert.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.concert.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.concert.booking_id</code>.
     */
    public Long getBookingId() {
        return this.bookingId;
    }

    /**
     * Setter for <code>eh8s.concert.booking_id</code>.
     */
    public void setBookingId(Long bookingId) {
        this.bookingId = bookingId;
    }

    /**
     * Getter for <code>eh8s.concert.venue_id</code>.
     */
    public Long getVenueId() {
        return this.venueId;
    }

    /**
     * Setter for <code>eh8s.concert.venue_id</code>.
     */
    public void setVenueId(Long venueId) {
        this.venueId = venueId;
    }

    /**
     * Getter for <code>eh8s.concert.band_id</code>.
     */
    public Long getBandId() {
        return this.bandId;
    }

    /**
     * Setter for <code>eh8s.concert.band_id</code>.
     */
    public void setBandId(Long bandId) {
        this.bandId = bandId;
    }

    /**
     * Getter for <code>eh8s.concert.spp_cycle_id</code>.
     */
    public Long getSppCycleId() {
        return this.sppCycleId;
    }

    /**
     * Setter for <code>eh8s.concert.spp_cycle_id</code>.
     */
    public void setSppCycleId(Long sppCycleId) {
        this.sppCycleId = sppCycleId;
    }

    /**
     * Getter for <code>eh8s.concert.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>eh8s.concert.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>eh8s.concert.show_minutes</code>.
     */
    public Integer getShowMinutes() {
        return this.showMinutes;
    }

    /**
     * Setter for <code>eh8s.concert.show_minutes</code>.
     */
    public void setShowMinutes(Integer showMinutes) {
        this.showMinutes = showMinutes;
    }

    /**
     * Getter for <code>eh8s.concert.concert_settlement_pda</code>.
     */
    public String getConcertSettlementPda() {
        return this.concertSettlementPda;
    }

    /**
     * Setter for <code>eh8s.concert.concert_settlement_pda</code>.
     */
    public void setConcertSettlementPda(String concertSettlementPda) {
        this.concertSettlementPda = concertSettlementPda;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Concert other = (Concert) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.bookingId == null) {
            if (other.bookingId != null)
                return false;
        }
        else if (!this.bookingId.equals(other.bookingId))
            return false;
        if (this.venueId == null) {
            if (other.venueId != null)
                return false;
        }
        else if (!this.venueId.equals(other.venueId))
            return false;
        if (this.bandId == null) {
            if (other.bandId != null)
                return false;
        }
        else if (!this.bandId.equals(other.bandId))
            return false;
        if (this.sppCycleId == null) {
            if (other.sppCycleId != null)
                return false;
        }
        else if (!this.sppCycleId.equals(other.sppCycleId))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.showMinutes == null) {
            if (other.showMinutes != null)
                return false;
        }
        else if (!this.showMinutes.equals(other.showMinutes))
            return false;
        if (this.concertSettlementPda == null) {
            if (other.concertSettlementPda != null)
                return false;
        }
        else if (!this.concertSettlementPda.equals(other.concertSettlementPda))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.bookingId == null) ? 0 : this.bookingId.hashCode());
        result = prime * result + ((this.venueId == null) ? 0 : this.venueId.hashCode());
        result = prime * result + ((this.bandId == null) ? 0 : this.bandId.hashCode());
        result = prime * result + ((this.sppCycleId == null) ? 0 : this.sppCycleId.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.showMinutes == null) ? 0 : this.showMinutes.hashCode());
        result = prime * result + ((this.concertSettlementPda == null) ? 0 : this.concertSettlementPda.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Concert (");

        sb.append(id);
        sb.append(", ").append(bookingId);
        sb.append(", ").append(venueId);
        sb.append(", ").append(bandId);
        sb.append(", ").append(sppCycleId);
        sb.append(", ").append(status);
        sb.append(", ").append(showMinutes);
        sb.append(", ").append(concertSettlementPda);

        sb.append(")");
        return sb.toString();
    }
}
