/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConcertExpense implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long concertId;
    private String label;
    private BigDecimal amountUsdc;

    public ConcertExpense() {}

    public ConcertExpense(ConcertExpense value) {
        this.id = value.id;
        this.concertId = value.concertId;
        this.label = value.label;
        this.amountUsdc = value.amountUsdc;
    }

    public ConcertExpense(
        Long id,
        Long concertId,
        String label,
        BigDecimal amountUsdc
    ) {
        this.id = id;
        this.concertId = concertId;
        this.label = label;
        this.amountUsdc = amountUsdc;
    }

    /**
     * Getter for <code>eh8s.concert_expense.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.concert_expense.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.concert_expense.concert_id</code>.
     */
    public Long getConcertId() {
        return this.concertId;
    }

    /**
     * Setter for <code>eh8s.concert_expense.concert_id</code>.
     */
    public void setConcertId(Long concertId) {
        this.concertId = concertId;
    }

    /**
     * Getter for <code>eh8s.concert_expense.label</code>.
     */
    public String getLabel() {
        return this.label;
    }

    /**
     * Setter for <code>eh8s.concert_expense.label</code>.
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * Getter for <code>eh8s.concert_expense.amount_usdc</code>.
     */
    public BigDecimal getAmountUsdc() {
        return this.amountUsdc;
    }

    /**
     * Setter for <code>eh8s.concert_expense.amount_usdc</code>.
     */
    public void setAmountUsdc(BigDecimal amountUsdc) {
        this.amountUsdc = amountUsdc;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ConcertExpense other = (ConcertExpense) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.concertId == null) {
            if (other.concertId != null)
                return false;
        }
        else if (!this.concertId.equals(other.concertId))
            return false;
        if (this.label == null) {
            if (other.label != null)
                return false;
        }
        else if (!this.label.equals(other.label))
            return false;
        if (this.amountUsdc == null) {
            if (other.amountUsdc != null)
                return false;
        }
        else if (!this.amountUsdc.equals(other.amountUsdc))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.concertId == null) ? 0 : this.concertId.hashCode());
        result = prime * result + ((this.label == null) ? 0 : this.label.hashCode());
        result = prime * result + ((this.amountUsdc == null) ? 0 : this.amountUsdc.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ConcertExpense (");

        sb.append(id);
        sb.append(", ").append(concertId);
        sb.append(", ").append(label);
        sb.append(", ").append(amountUsdc);

        sb.append(")");
        return sb.toString();
    }
}
