/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Instrument implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String code;
    private String name;

    public Instrument() {}

    public Instrument(Instrument value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
    }

    public Instrument(
        Long id,
        String code,
        String name
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
    }

    /**
     * Getter for <code>eh8s.instrument.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.instrument.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.instrument.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>eh8s.instrument.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>eh8s.instrument.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>eh8s.instrument.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Instrument other = (Instrument) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Instrument (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
