/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MusicianProfile implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long accountId;
    private Long instrumentId;
    private Long enigmaLevelId;
    private Byte enigmaScore;
    private String countryCode;
    private String genres;
    private String musicianProfilePda;

    public MusicianProfile() {}

    public MusicianProfile(MusicianProfile value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.instrumentId = value.instrumentId;
        this.enigmaLevelId = value.enigmaLevelId;
        this.enigmaScore = value.enigmaScore;
        this.countryCode = value.countryCode;
        this.genres = value.genres;
        this.musicianProfilePda = value.musicianProfilePda;
    }

    public MusicianProfile(
        Long id,
        Long accountId,
        Long instrumentId,
        Long enigmaLevelId,
        Byte enigmaScore,
        String countryCode,
        String genres,
        String musicianProfilePda
    ) {
        this.id = id;
        this.accountId = accountId;
        this.instrumentId = instrumentId;
        this.enigmaLevelId = enigmaLevelId;
        this.enigmaScore = enigmaScore;
        this.countryCode = countryCode;
        this.genres = genres;
        this.musicianProfilePda = musicianProfilePda;
    }

    /**
     * Getter for <code>eh8s.musician_profile.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.musician_profile.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.musician_profile.account_id</code>.
     */
    public Long getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>eh8s.musician_profile.account_id</code>.
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>eh8s.musician_profile.instrument_id</code>.
     */
    public Long getInstrumentId() {
        return this.instrumentId;
    }

    /**
     * Setter for <code>eh8s.musician_profile.instrument_id</code>.
     */
    public void setInstrumentId(Long instrumentId) {
        this.instrumentId = instrumentId;
    }

    /**
     * Getter for <code>eh8s.musician_profile.enigma_level_id</code>.
     */
    public Long getEnigmaLevelId() {
        return this.enigmaLevelId;
    }

    /**
     * Setter for <code>eh8s.musician_profile.enigma_level_id</code>.
     */
    public void setEnigmaLevelId(Long enigmaLevelId) {
        this.enigmaLevelId = enigmaLevelId;
    }

    /**
     * Getter for <code>eh8s.musician_profile.enigma_score</code>.
     */
    public Byte getEnigmaScore() {
        return this.enigmaScore;
    }

    /**
     * Setter for <code>eh8s.musician_profile.enigma_score</code>.
     */
    public void setEnigmaScore(Byte enigmaScore) {
        this.enigmaScore = enigmaScore;
    }

    /**
     * Getter for <code>eh8s.musician_profile.country_code</code>.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Setter for <code>eh8s.musician_profile.country_code</code>.
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for <code>eh8s.musician_profile.genres</code>.
     */
    public String getGenres() {
        return this.genres;
    }

    /**
     * Setter for <code>eh8s.musician_profile.genres</code>.
     */
    public void setGenres(String genres) {
        this.genres = genres;
    }

    /**
     * Getter for <code>eh8s.musician_profile.musician_profile_pda</code>.
     */
    public String getMusicianProfilePda() {
        return this.musicianProfilePda;
    }

    /**
     * Setter for <code>eh8s.musician_profile.musician_profile_pda</code>.
     */
    public void setMusicianProfilePda(String musicianProfilePda) {
        this.musicianProfilePda = musicianProfilePda;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final MusicianProfile other = (MusicianProfile) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.accountId == null) {
            if (other.accountId != null)
                return false;
        }
        else if (!this.accountId.equals(other.accountId))
            return false;
        if (this.instrumentId == null) {
            if (other.instrumentId != null)
                return false;
        }
        else if (!this.instrumentId.equals(other.instrumentId))
            return false;
        if (this.enigmaLevelId == null) {
            if (other.enigmaLevelId != null)
                return false;
        }
        else if (!this.enigmaLevelId.equals(other.enigmaLevelId))
            return false;
        if (this.enigmaScore == null) {
            if (other.enigmaScore != null)
                return false;
        }
        else if (!this.enigmaScore.equals(other.enigmaScore))
            return false;
        if (this.countryCode == null) {
            if (other.countryCode != null)
                return false;
        }
        else if (!this.countryCode.equals(other.countryCode))
            return false;
        if (this.genres == null) {
            if (other.genres != null)
                return false;
        }
        else if (!this.genres.equals(other.genres))
            return false;
        if (this.musicianProfilePda == null) {
            if (other.musicianProfilePda != null)
                return false;
        }
        else if (!this.musicianProfilePda.equals(other.musicianProfilePda))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.accountId == null) ? 0 : this.accountId.hashCode());
        result = prime * result + ((this.instrumentId == null) ? 0 : this.instrumentId.hashCode());
        result = prime * result + ((this.enigmaLevelId == null) ? 0 : this.enigmaLevelId.hashCode());
        result = prime * result + ((this.enigmaScore == null) ? 0 : this.enigmaScore.hashCode());
        result = prime * result + ((this.countryCode == null) ? 0 : this.countryCode.hashCode());
        result = prime * result + ((this.genres == null) ? 0 : this.genres.hashCode());
        result = prime * result + ((this.musicianProfilePda == null) ? 0 : this.musicianProfilePda.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MusicianProfile (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(instrumentId);
        sb.append(", ").append(enigmaLevelId);
        sb.append(", ").append(enigmaScore);
        sb.append(", ").append(countryCode);
        sb.append(", ").append(genres);
        sb.append(", ").append(musicianProfilePda);

        sb.append(")");
        return sb.toString();
    }
}
