/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PendingClaim implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long concertSettlementId;
    private Long musicianProfileId;
    private Integer shareBps;
    private BigDecimal amountUsdc;
    private String status;
    private String claimPda;
    private String txSignature;
    private LocalDateTime claimedAt;
    private String claimerWalletPubkey;
    private String onChainStatus;

    public PendingClaim() {}

    public PendingClaim(PendingClaim value) {
        this.id = value.id;
        this.concertSettlementId = value.concertSettlementId;
        this.musicianProfileId = value.musicianProfileId;
        this.shareBps = value.shareBps;
        this.amountUsdc = value.amountUsdc;
        this.status = value.status;
        this.claimPda = value.claimPda;
        this.txSignature = value.txSignature;
        this.claimedAt = value.claimedAt;
        this.claimerWalletPubkey = value.claimerWalletPubkey;
        this.onChainStatus = value.onChainStatus;
    }

    public PendingClaim(
        Long id,
        Long concertSettlementId,
        Long musicianProfileId,
        Integer shareBps,
        BigDecimal amountUsdc,
        String status,
        String claimPda,
        String txSignature,
        LocalDateTime claimedAt,
        String claimerWalletPubkey,
        String onChainStatus
    ) {
        this.id = id;
        this.concertSettlementId = concertSettlementId;
        this.musicianProfileId = musicianProfileId;
        this.shareBps = shareBps;
        this.amountUsdc = amountUsdc;
        this.status = status;
        this.claimPda = claimPda;
        this.txSignature = txSignature;
        this.claimedAt = claimedAt;
        this.claimerWalletPubkey = claimerWalletPubkey;
        this.onChainStatus = onChainStatus;
    }

    /**
     * Getter for <code>eh8s.pending_claim.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.pending_claim.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.pending_claim.concert_settlement_id</code>.
     */
    public Long getConcertSettlementId() {
        return this.concertSettlementId;
    }

    /**
     * Setter for <code>eh8s.pending_claim.concert_settlement_id</code>.
     */
    public void setConcertSettlementId(Long concertSettlementId) {
        this.concertSettlementId = concertSettlementId;
    }

    /**
     * Getter for <code>eh8s.pending_claim.musician_profile_id</code>.
     */
    public Long getMusicianProfileId() {
        return this.musicianProfileId;
    }

    /**
     * Setter for <code>eh8s.pending_claim.musician_profile_id</code>.
     */
    public void setMusicianProfileId(Long musicianProfileId) {
        this.musicianProfileId = musicianProfileId;
    }

    /**
     * Getter for <code>eh8s.pending_claim.share_bps</code>.
     */
    public Integer getShareBps() {
        return this.shareBps;
    }

    /**
     * Setter for <code>eh8s.pending_claim.share_bps</code>.
     */
    public void setShareBps(Integer shareBps) {
        this.shareBps = shareBps;
    }

    /**
     * Getter for <code>eh8s.pending_claim.amount_usdc</code>.
     */
    public BigDecimal getAmountUsdc() {
        return this.amountUsdc;
    }

    /**
     * Setter for <code>eh8s.pending_claim.amount_usdc</code>.
     */
    public void setAmountUsdc(BigDecimal amountUsdc) {
        this.amountUsdc = amountUsdc;
    }

    /**
     * Getter for <code>eh8s.pending_claim.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>eh8s.pending_claim.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>eh8s.pending_claim.claim_pda</code>.
     */
    public String getClaimPda() {
        return this.claimPda;
    }

    /**
     * Setter for <code>eh8s.pending_claim.claim_pda</code>.
     */
    public void setClaimPda(String claimPda) {
        this.claimPda = claimPda;
    }

    /**
     * Getter for <code>eh8s.pending_claim.tx_signature</code>.
     */
    public String getTxSignature() {
        return this.txSignature;
    }

    /**
     * Setter for <code>eh8s.pending_claim.tx_signature</code>.
     */
    public void setTxSignature(String txSignature) {
        this.txSignature = txSignature;
    }

    /**
     * Getter for <code>eh8s.pending_claim.claimed_at</code>.
     */
    public LocalDateTime getClaimedAt() {
        return this.claimedAt;
    }

    /**
     * Setter for <code>eh8s.pending_claim.claimed_at</code>.
     */
    public void setClaimedAt(LocalDateTime claimedAt) {
        this.claimedAt = claimedAt;
    }

    /**
     * Getter for <code>eh8s.pending_claim.claimer_wallet_pubkey</code>.
     */
    public String getClaimerWalletPubkey() {
        return this.claimerWalletPubkey;
    }

    /**
     * Setter for <code>eh8s.pending_claim.claimer_wallet_pubkey</code>.
     */
    public void setClaimerWalletPubkey(String claimerWalletPubkey) {
        this.claimerWalletPubkey = claimerWalletPubkey;
    }

    /**
     * Getter for <code>eh8s.pending_claim.on_chain_status</code>.
     */
    public String getOnChainStatus() {
        return this.onChainStatus;
    }

    /**
     * Setter for <code>eh8s.pending_claim.on_chain_status</code>.
     */
    public void setOnChainStatus(String onChainStatus) {
        this.onChainStatus = onChainStatus;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PendingClaim other = (PendingClaim) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.concertSettlementId == null) {
            if (other.concertSettlementId != null)
                return false;
        }
        else if (!this.concertSettlementId.equals(other.concertSettlementId))
            return false;
        if (this.musicianProfileId == null) {
            if (other.musicianProfileId != null)
                return false;
        }
        else if (!this.musicianProfileId.equals(other.musicianProfileId))
            return false;
        if (this.shareBps == null) {
            if (other.shareBps != null)
                return false;
        }
        else if (!this.shareBps.equals(other.shareBps))
            return false;
        if (this.amountUsdc == null) {
            if (other.amountUsdc != null)
                return false;
        }
        else if (!this.amountUsdc.equals(other.amountUsdc))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.claimPda == null) {
            if (other.claimPda != null)
                return false;
        }
        else if (!this.claimPda.equals(other.claimPda))
            return false;
        if (this.txSignature == null) {
            if (other.txSignature != null)
                return false;
        }
        else if (!this.txSignature.equals(other.txSignature))
            return false;
        if (this.claimedAt == null) {
            if (other.claimedAt != null)
                return false;
        }
        else if (!this.claimedAt.equals(other.claimedAt))
            return false;
        if (this.claimerWalletPubkey == null) {
            if (other.claimerWalletPubkey != null)
                return false;
        }
        else if (!this.claimerWalletPubkey.equals(other.claimerWalletPubkey))
            return false;
        if (this.onChainStatus == null) {
            if (other.onChainStatus != null)
                return false;
        }
        else if (!this.onChainStatus.equals(other.onChainStatus))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.concertSettlementId == null) ? 0 : this.concertSettlementId.hashCode());
        result = prime * result + ((this.musicianProfileId == null) ? 0 : this.musicianProfileId.hashCode());
        result = prime * result + ((this.shareBps == null) ? 0 : this.shareBps.hashCode());
        result = prime * result + ((this.amountUsdc == null) ? 0 : this.amountUsdc.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.claimPda == null) ? 0 : this.claimPda.hashCode());
        result = prime * result + ((this.txSignature == null) ? 0 : this.txSignature.hashCode());
        result = prime * result + ((this.claimedAt == null) ? 0 : this.claimedAt.hashCode());
        result = prime * result + ((this.claimerWalletPubkey == null) ? 0 : this.claimerWalletPubkey.hashCode());
        result = prime * result + ((this.onChainStatus == null) ? 0 : this.onChainStatus.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PendingClaim (");

        sb.append(id);
        sb.append(", ").append(concertSettlementId);
        sb.append(", ").append(musicianProfileId);
        sb.append(", ").append(shareBps);
        sb.append(", ").append(amountUsdc);
        sb.append(", ").append(status);
        sb.append(", ").append(claimPda);
        sb.append(", ").append(txSignature);
        sb.append(", ").append(claimedAt);
        sb.append(", ").append(claimerWalletPubkey);
        sb.append(", ").append(onChainStatus);

        sb.append(")");
        return sb.toString();
    }
}
