/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RehearsalCheckin implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long rehearsalSessionId;
    private Long musicianProfileId;
    private LocalDateTime arrivedAt;
    private Integer lateMinutes;
    private Integer attendancePoints;
    private Integer punctualityPoints;

    public RehearsalCheckin() {}

    public RehearsalCheckin(RehearsalCheckin value) {
        this.id = value.id;
        this.rehearsalSessionId = value.rehearsalSessionId;
        this.musicianProfileId = value.musicianProfileId;
        this.arrivedAt = value.arrivedAt;
        this.lateMinutes = value.lateMinutes;
        this.attendancePoints = value.attendancePoints;
        this.punctualityPoints = value.punctualityPoints;
    }

    public RehearsalCheckin(
        Long id,
        Long rehearsalSessionId,
        Long musicianProfileId,
        LocalDateTime arrivedAt,
        Integer lateMinutes,
        Integer attendancePoints,
        Integer punctualityPoints
    ) {
        this.id = id;
        this.rehearsalSessionId = rehearsalSessionId;
        this.musicianProfileId = musicianProfileId;
        this.arrivedAt = arrivedAt;
        this.lateMinutes = lateMinutes;
        this.attendancePoints = attendancePoints;
        this.punctualityPoints = punctualityPoints;
    }

    /**
     * Getter for <code>eh8s.rehearsal_checkin.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.rehearsal_checkin.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.rehearsal_checkin.rehearsal_session_id</code>.
     */
    public Long getRehearsalSessionId() {
        return this.rehearsalSessionId;
    }

    /**
     * Setter for <code>eh8s.rehearsal_checkin.rehearsal_session_id</code>.
     */
    public void setRehearsalSessionId(Long rehearsalSessionId) {
        this.rehearsalSessionId = rehearsalSessionId;
    }

    /**
     * Getter for <code>eh8s.rehearsal_checkin.musician_profile_id</code>.
     */
    public Long getMusicianProfileId() {
        return this.musicianProfileId;
    }

    /**
     * Setter for <code>eh8s.rehearsal_checkin.musician_profile_id</code>.
     */
    public void setMusicianProfileId(Long musicianProfileId) {
        this.musicianProfileId = musicianProfileId;
    }

    /**
     * Getter for <code>eh8s.rehearsal_checkin.arrived_at</code>.
     */
    public LocalDateTime getArrivedAt() {
        return this.arrivedAt;
    }

    /**
     * Setter for <code>eh8s.rehearsal_checkin.arrived_at</code>.
     */
    public void setArrivedAt(LocalDateTime arrivedAt) {
        this.arrivedAt = arrivedAt;
    }

    /**
     * Getter for <code>eh8s.rehearsal_checkin.late_minutes</code>.
     */
    public Integer getLateMinutes() {
        return this.lateMinutes;
    }

    /**
     * Setter for <code>eh8s.rehearsal_checkin.late_minutes</code>.
     */
    public void setLateMinutes(Integer lateMinutes) {
        this.lateMinutes = lateMinutes;
    }

    /**
     * Getter for <code>eh8s.rehearsal_checkin.attendance_points</code>.
     */
    public Integer getAttendancePoints() {
        return this.attendancePoints;
    }

    /**
     * Setter for <code>eh8s.rehearsal_checkin.attendance_points</code>.
     */
    public void setAttendancePoints(Integer attendancePoints) {
        this.attendancePoints = attendancePoints;
    }

    /**
     * Getter for <code>eh8s.rehearsal_checkin.punctuality_points</code>.
     */
    public Integer getPunctualityPoints() {
        return this.punctualityPoints;
    }

    /**
     * Setter for <code>eh8s.rehearsal_checkin.punctuality_points</code>.
     */
    public void setPunctualityPoints(Integer punctualityPoints) {
        this.punctualityPoints = punctualityPoints;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final RehearsalCheckin other = (RehearsalCheckin) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.rehearsalSessionId == null) {
            if (other.rehearsalSessionId != null)
                return false;
        }
        else if (!this.rehearsalSessionId.equals(other.rehearsalSessionId))
            return false;
        if (this.musicianProfileId == null) {
            if (other.musicianProfileId != null)
                return false;
        }
        else if (!this.musicianProfileId.equals(other.musicianProfileId))
            return false;
        if (this.arrivedAt == null) {
            if (other.arrivedAt != null)
                return false;
        }
        else if (!this.arrivedAt.equals(other.arrivedAt))
            return false;
        if (this.lateMinutes == null) {
            if (other.lateMinutes != null)
                return false;
        }
        else if (!this.lateMinutes.equals(other.lateMinutes))
            return false;
        if (this.attendancePoints == null) {
            if (other.attendancePoints != null)
                return false;
        }
        else if (!this.attendancePoints.equals(other.attendancePoints))
            return false;
        if (this.punctualityPoints == null) {
            if (other.punctualityPoints != null)
                return false;
        }
        else if (!this.punctualityPoints.equals(other.punctualityPoints))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.rehearsalSessionId == null) ? 0 : this.rehearsalSessionId.hashCode());
        result = prime * result + ((this.musicianProfileId == null) ? 0 : this.musicianProfileId.hashCode());
        result = prime * result + ((this.arrivedAt == null) ? 0 : this.arrivedAt.hashCode());
        result = prime * result + ((this.lateMinutes == null) ? 0 : this.lateMinutes.hashCode());
        result = prime * result + ((this.attendancePoints == null) ? 0 : this.attendancePoints.hashCode());
        result = prime * result + ((this.punctualityPoints == null) ? 0 : this.punctualityPoints.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RehearsalCheckin (");

        sb.append(id);
        sb.append(", ").append(rehearsalSessionId);
        sb.append(", ").append(musicianProfileId);
        sb.append(", ").append(arrivedAt);
        sb.append(", ").append(lateMinutes);
        sb.append(", ").append(attendancePoints);
        sb.append(", ").append(punctualityPoints);

        sb.append(")");
        return sb.toString();
    }
}
