/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Venue implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String code;
    private String name;
    private String city;
    private String countryCode;
    private Integer capacity;
    private BigDecimal suggestedTicketUsdc;
    private BigDecimal latitude;
    private BigDecimal longitude;
    private String pinStatus;
    private Byte isPartner;
    private Byte eh8sRating;
    private Byte soundIncluded;
    private String preferredGenres;
    private Long contractTypeId;
    private String venueListingPda;
    private String walletPubkey;
    private String listingStatus;
    private String registerTxSignature;
    private String approveTxSignature;
    private String approvedByWallet;

    public Venue() {}

    public Venue(Venue value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.city = value.city;
        this.countryCode = value.countryCode;
        this.capacity = value.capacity;
        this.suggestedTicketUsdc = value.suggestedTicketUsdc;
        this.latitude = value.latitude;
        this.longitude = value.longitude;
        this.pinStatus = value.pinStatus;
        this.isPartner = value.isPartner;
        this.eh8sRating = value.eh8sRating;
        this.soundIncluded = value.soundIncluded;
        this.preferredGenres = value.preferredGenres;
        this.contractTypeId = value.contractTypeId;
        this.venueListingPda = value.venueListingPda;
        this.walletPubkey = value.walletPubkey;
        this.listingStatus = value.listingStatus;
        this.registerTxSignature = value.registerTxSignature;
        this.approveTxSignature = value.approveTxSignature;
        this.approvedByWallet = value.approvedByWallet;
    }

    public Venue(
        Long id,
        String code,
        String name,
        String city,
        String countryCode,
        Integer capacity,
        BigDecimal suggestedTicketUsdc,
        BigDecimal latitude,
        BigDecimal longitude,
        String pinStatus,
        Byte isPartner,
        Byte eh8sRating,
        Byte soundIncluded,
        String preferredGenres,
        Long contractTypeId,
        String venueListingPda,
        String walletPubkey,
        String listingStatus,
        String registerTxSignature,
        String approveTxSignature,
        String approvedByWallet
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.city = city;
        this.countryCode = countryCode;
        this.capacity = capacity;
        this.suggestedTicketUsdc = suggestedTicketUsdc;
        this.latitude = latitude;
        this.longitude = longitude;
        this.pinStatus = pinStatus;
        this.isPartner = isPartner;
        this.eh8sRating = eh8sRating;
        this.soundIncluded = soundIncluded;
        this.preferredGenres = preferredGenres;
        this.contractTypeId = contractTypeId;
        this.venueListingPda = venueListingPda;
        this.walletPubkey = walletPubkey;
        this.listingStatus = listingStatus;
        this.registerTxSignature = registerTxSignature;
        this.approveTxSignature = approveTxSignature;
        this.approvedByWallet = approvedByWallet;
    }

    /**
     * Getter for <code>eh8s.venue.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s.venue.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s.venue.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>eh8s.venue.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>eh8s.venue.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>eh8s.venue.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>eh8s.venue.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>eh8s.venue.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>eh8s.venue.country_code</code>.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Setter for <code>eh8s.venue.country_code</code>.
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for <code>eh8s.venue.capacity</code>.
     */
    public Integer getCapacity() {
        return this.capacity;
    }

    /**
     * Setter for <code>eh8s.venue.capacity</code>.
     */
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }

    /**
     * Getter for <code>eh8s.venue.suggested_ticket_usdc</code>.
     */
    public BigDecimal getSuggestedTicketUsdc() {
        return this.suggestedTicketUsdc;
    }

    /**
     * Setter for <code>eh8s.venue.suggested_ticket_usdc</code>.
     */
    public void setSuggestedTicketUsdc(BigDecimal suggestedTicketUsdc) {
        this.suggestedTicketUsdc = suggestedTicketUsdc;
    }

    /**
     * Getter for <code>eh8s.venue.latitude</code>.
     */
    public BigDecimal getLatitude() {
        return this.latitude;
    }

    /**
     * Setter for <code>eh8s.venue.latitude</code>.
     */
    public void setLatitude(BigDecimal latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for <code>eh8s.venue.longitude</code>.
     */
    public BigDecimal getLongitude() {
        return this.longitude;
    }

    /**
     * Setter for <code>eh8s.venue.longitude</code>.
     */
    public void setLongitude(BigDecimal longitude) {
        this.longitude = longitude;
    }

    /**
     * Getter for <code>eh8s.venue.pin_status</code>.
     */
    public String getPinStatus() {
        return this.pinStatus;
    }

    /**
     * Setter for <code>eh8s.venue.pin_status</code>.
     */
    public void setPinStatus(String pinStatus) {
        this.pinStatus = pinStatus;
    }

    /**
     * Getter for <code>eh8s.venue.is_partner</code>.
     */
    public Byte getIsPartner() {
        return this.isPartner;
    }

    /**
     * Setter for <code>eh8s.venue.is_partner</code>.
     */
    public void setIsPartner(Byte isPartner) {
        this.isPartner = isPartner;
    }

    /**
     * Getter for <code>eh8s.venue.eh8s_rating</code>.
     */
    public Byte getEh8sRating() {
        return this.eh8sRating;
    }

    /**
     * Setter for <code>eh8s.venue.eh8s_rating</code>.
     */
    public void setEh8sRating(Byte eh8sRating) {
        this.eh8sRating = eh8sRating;
    }

    /**
     * Getter for <code>eh8s.venue.sound_included</code>.
     */
    public Byte getSoundIncluded() {
        return this.soundIncluded;
    }

    /**
     * Setter for <code>eh8s.venue.sound_included</code>.
     */
    public void setSoundIncluded(Byte soundIncluded) {
        this.soundIncluded = soundIncluded;
    }

    /**
     * Getter for <code>eh8s.venue.preferred_genres</code>.
     */
    public String getPreferredGenres() {
        return this.preferredGenres;
    }

    /**
     * Setter for <code>eh8s.venue.preferred_genres</code>.
     */
    public void setPreferredGenres(String preferredGenres) {
        this.preferredGenres = preferredGenres;
    }

    /**
     * Getter for <code>eh8s.venue.contract_type_id</code>.
     */
    public Long getContractTypeId() {
        return this.contractTypeId;
    }

    /**
     * Setter for <code>eh8s.venue.contract_type_id</code>.
     */
    public void setContractTypeId(Long contractTypeId) {
        this.contractTypeId = contractTypeId;
    }

    /**
     * Getter for <code>eh8s.venue.venue_listing_pda</code>.
     */
    public String getVenueListingPda() {
        return this.venueListingPda;
    }

    /**
     * Setter for <code>eh8s.venue.venue_listing_pda</code>.
     */
    public void setVenueListingPda(String venueListingPda) {
        this.venueListingPda = venueListingPda;
    }

    /**
     * Getter for <code>eh8s.venue.wallet_pubkey</code>.
     */
    public String getWalletPubkey() {
        return this.walletPubkey;
    }

    /**
     * Setter for <code>eh8s.venue.wallet_pubkey</code>.
     */
    public void setWalletPubkey(String walletPubkey) {
        this.walletPubkey = walletPubkey;
    }

    /**
     * Getter for <code>eh8s.venue.listing_status</code>.
     */
    public String getListingStatus() {
        return this.listingStatus;
    }

    /**
     * Setter for <code>eh8s.venue.listing_status</code>.
     */
    public void setListingStatus(String listingStatus) {
        this.listingStatus = listingStatus;
    }

    /**
     * Getter for <code>eh8s.venue.register_tx_signature</code>.
     */
    public String getRegisterTxSignature() {
        return this.registerTxSignature;
    }

    /**
     * Setter for <code>eh8s.venue.register_tx_signature</code>.
     */
    public void setRegisterTxSignature(String registerTxSignature) {
        this.registerTxSignature = registerTxSignature;
    }

    /**
     * Getter for <code>eh8s.venue.approve_tx_signature</code>.
     */
    public String getApproveTxSignature() {
        return this.approveTxSignature;
    }

    /**
     * Setter for <code>eh8s.venue.approve_tx_signature</code>.
     */
    public void setApproveTxSignature(String approveTxSignature) {
        this.approveTxSignature = approveTxSignature;
    }

    /**
     * Getter for <code>eh8s.venue.approved_by_wallet</code>.
     */
    public String getApprovedByWallet() {
        return this.approvedByWallet;
    }

    /**
     * Setter for <code>eh8s.venue.approved_by_wallet</code>.
     */
    public void setApprovedByWallet(String approvedByWallet) {
        this.approvedByWallet = approvedByWallet;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Venue other = (Venue) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        if (this.countryCode == null) {
            if (other.countryCode != null)
                return false;
        }
        else if (!this.countryCode.equals(other.countryCode))
            return false;
        if (this.capacity == null) {
            if (other.capacity != null)
                return false;
        }
        else if (!this.capacity.equals(other.capacity))
            return false;
        if (this.suggestedTicketUsdc == null) {
            if (other.suggestedTicketUsdc != null)
                return false;
        }
        else if (!this.suggestedTicketUsdc.equals(other.suggestedTicketUsdc))
            return false;
        if (this.latitude == null) {
            if (other.latitude != null)
                return false;
        }
        else if (!this.latitude.equals(other.latitude))
            return false;
        if (this.longitude == null) {
            if (other.longitude != null)
                return false;
        }
        else if (!this.longitude.equals(other.longitude))
            return false;
        if (this.pinStatus == null) {
            if (other.pinStatus != null)
                return false;
        }
        else if (!this.pinStatus.equals(other.pinStatus))
            return false;
        if (this.isPartner == null) {
            if (other.isPartner != null)
                return false;
        }
        else if (!this.isPartner.equals(other.isPartner))
            return false;
        if (this.eh8sRating == null) {
            if (other.eh8sRating != null)
                return false;
        }
        else if (!this.eh8sRating.equals(other.eh8sRating))
            return false;
        if (this.soundIncluded == null) {
            if (other.soundIncluded != null)
                return false;
        }
        else if (!this.soundIncluded.equals(other.soundIncluded))
            return false;
        if (this.preferredGenres == null) {
            if (other.preferredGenres != null)
                return false;
        }
        else if (!this.preferredGenres.equals(other.preferredGenres))
            return false;
        if (this.contractTypeId == null) {
            if (other.contractTypeId != null)
                return false;
        }
        else if (!this.contractTypeId.equals(other.contractTypeId))
            return false;
        if (this.venueListingPda == null) {
            if (other.venueListingPda != null)
                return false;
        }
        else if (!this.venueListingPda.equals(other.venueListingPda))
            return false;
        if (this.walletPubkey == null) {
            if (other.walletPubkey != null)
                return false;
        }
        else if (!this.walletPubkey.equals(other.walletPubkey))
            return false;
        if (this.listingStatus == null) {
            if (other.listingStatus != null)
                return false;
        }
        else if (!this.listingStatus.equals(other.listingStatus))
            return false;
        if (this.registerTxSignature == null) {
            if (other.registerTxSignature != null)
                return false;
        }
        else if (!this.registerTxSignature.equals(other.registerTxSignature))
            return false;
        if (this.approveTxSignature == null) {
            if (other.approveTxSignature != null)
                return false;
        }
        else if (!this.approveTxSignature.equals(other.approveTxSignature))
            return false;
        if (this.approvedByWallet == null) {
            if (other.approvedByWallet != null)
                return false;
        }
        else if (!this.approvedByWallet.equals(other.approvedByWallet))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        result = prime * result + ((this.countryCode == null) ? 0 : this.countryCode.hashCode());
        result = prime * result + ((this.capacity == null) ? 0 : this.capacity.hashCode());
        result = prime * result + ((this.suggestedTicketUsdc == null) ? 0 : this.suggestedTicketUsdc.hashCode());
        result = prime * result + ((this.latitude == null) ? 0 : this.latitude.hashCode());
        result = prime * result + ((this.longitude == null) ? 0 : this.longitude.hashCode());
        result = prime * result + ((this.pinStatus == null) ? 0 : this.pinStatus.hashCode());
        result = prime * result + ((this.isPartner == null) ? 0 : this.isPartner.hashCode());
        result = prime * result + ((this.eh8sRating == null) ? 0 : this.eh8sRating.hashCode());
        result = prime * result + ((this.soundIncluded == null) ? 0 : this.soundIncluded.hashCode());
        result = prime * result + ((this.preferredGenres == null) ? 0 : this.preferredGenres.hashCode());
        result = prime * result + ((this.contractTypeId == null) ? 0 : this.contractTypeId.hashCode());
        result = prime * result + ((this.venueListingPda == null) ? 0 : this.venueListingPda.hashCode());
        result = prime * result + ((this.walletPubkey == null) ? 0 : this.walletPubkey.hashCode());
        result = prime * result + ((this.listingStatus == null) ? 0 : this.listingStatus.hashCode());
        result = prime * result + ((this.registerTxSignature == null) ? 0 : this.registerTxSignature.hashCode());
        result = prime * result + ((this.approveTxSignature == null) ? 0 : this.approveTxSignature.hashCode());
        result = prime * result + ((this.approvedByWallet == null) ? 0 : this.approvedByWallet.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Venue (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(city);
        sb.append(", ").append(countryCode);
        sb.append(", ").append(capacity);
        sb.append(", ").append(suggestedTicketUsdc);
        sb.append(", ").append(latitude);
        sb.append(", ").append(longitude);
        sb.append(", ").append(pinStatus);
        sb.append(", ").append(isPartner);
        sb.append(", ").append(eh8sRating);
        sb.append(", ").append(soundIncluded);
        sb.append(", ").append(preferredGenres);
        sb.append(", ").append(contractTypeId);
        sb.append(", ").append(venueListingPda);
        sb.append(", ").append(walletPubkey);
        sb.append(", ").append(listingStatus);
        sb.append(", ").append(registerTxSignature);
        sb.append(", ").append(approveTxSignature);
        sb.append(", ").append(approvedByWallet);

        sb.append(")");
        return sb.toString();
    }
}
