/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables;


import com.eh8s.eh8s.database.jooq.eh8s_catalog.Eh8sCatalog;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.ChannelFormat.ChannelFormatPath;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.records.ChannelPieceRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChannelPiece extends TableImpl<ChannelPieceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_catalog.channel_piece</code>
     */
    public static final ChannelPiece CHANNEL_PIECE = new ChannelPiece();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChannelPieceRecord> getRecordType() {
        return ChannelPieceRecord.class;
    }

    /**
     * The column <code>eh8s_catalog.channel_piece.id</code>.
     */
    public final TableField<ChannelPieceRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s_catalog.channel_piece.channel_format_id</code>.
     */
    public final TableField<ChannelPieceRecord, Long> CHANNEL_FORMAT_ID = createField(DSL.name("channel_format_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.channel_piece.title</code>.
     */
    public final TableField<ChannelPieceRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(160).nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.channel_piece.artist_share_bps</code>.
     */
    public final TableField<ChannelPieceRecord, Integer> ARTIST_SHARE_BPS = createField(DSL.name("artist_share_bps"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.channel_piece.eh8s_share_bps</code>.
     */
    public final TableField<ChannelPieceRecord, Integer> EH8S_SHARE_BPS = createField(DSL.name("eh8s_share_bps"), SQLDataType.INTEGER.nullable(false), this, "");

    private ChannelPiece(Name alias, Table<ChannelPieceRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ChannelPiece(Name alias, Table<ChannelPieceRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_catalog.channel_piece</code> table reference
     */
    public ChannelPiece(String alias) {
        this(DSL.name(alias), CHANNEL_PIECE);
    }

    /**
     * Create an aliased <code>eh8s_catalog.channel_piece</code> table reference
     */
    public ChannelPiece(Name alias) {
        this(alias, CHANNEL_PIECE);
    }

    /**
     * Create a <code>eh8s_catalog.channel_piece</code> table reference
     */
    public ChannelPiece() {
        this(DSL.name("channel_piece"), null);
    }

    public <O extends Record> ChannelPiece(Table<O> path, ForeignKey<O, ChannelPieceRecord> childPath, InverseForeignKey<O, ChannelPieceRecord> parentPath) {
        super(path, childPath, parentPath, CHANNEL_PIECE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChannelPiecePath extends ChannelPiece implements Path<ChannelPieceRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ChannelPiecePath(Table<O> path, ForeignKey<O, ChannelPieceRecord> childPath, InverseForeignKey<O, ChannelPieceRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ChannelPiecePath(Name alias, Table<ChannelPieceRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChannelPiecePath as(String alias) {
            return new ChannelPiecePath(DSL.name(alias), this);
        }

        @Override
        public ChannelPiecePath as(Name alias) {
            return new ChannelPiecePath(alias, this);
        }

        @Override
        public ChannelPiecePath as(Table<?> alias) {
            return new ChannelPiecePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sCatalog.EH8S_CATALOG;
    }

    @Override
    public Identity<ChannelPieceRecord, Long> getIdentity() {
        return (Identity<ChannelPieceRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ChannelPieceRecord> getPrimaryKey() {
        return Keys.KEY_CHANNEL_PIECE_PRIMARY;
    }

    @Override
    public List<ForeignKey<ChannelPieceRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_PIECE_FORMAT);
    }

    private transient ChannelFormatPath _channelFormat;

    /**
     * Get the implicit join path to the
     * <code>eh8s_catalog.channel_format</code> table.
     */
    public ChannelFormatPath channelFormat() {
        if (_channelFormat == null)
            _channelFormat = new ChannelFormatPath(this, Keys.FK_PIECE_FORMAT, null);

        return _channelFormat;
    }

    @Override
    public ChannelPiece as(String alias) {
        return new ChannelPiece(DSL.name(alias), this);
    }

    @Override
    public ChannelPiece as(Name alias) {
        return new ChannelPiece(alias, this);
    }

    @Override
    public ChannelPiece as(Table<?> alias) {
        return new ChannelPiece(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChannelPiece rename(String name) {
        return new ChannelPiece(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChannelPiece rename(Name name) {
        return new ChannelPiece(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChannelPiece rename(Table<?> name) {
        return new ChannelPiece(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChannelPiece where(Condition condition) {
        return new ChannelPiece(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChannelPiece where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChannelPiece where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChannelPiece where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChannelPiece where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChannelPiece where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChannelPiece where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ChannelPiece where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChannelPiece whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ChannelPiece whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
