/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables;


import com.eh8s.eh8s.database.jooq.eh8s_catalog.Eh8sCatalog;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.RoyaltyDeposit.RoyaltyDepositPath;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.RoyaltySplit.RoyaltySplitPath;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.records.RoyaltyTypeRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoyaltyType extends TableImpl<RoyaltyTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_catalog.royalty_type</code>
     */
    public static final RoyaltyType ROYALTY_TYPE = new RoyaltyType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoyaltyTypeRecord> getRecordType() {
        return RoyaltyTypeRecord.class;
    }

    /**
     * The column <code>eh8s_catalog.royalty_type.id</code>.
     */
    public final TableField<RoyaltyTypeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s_catalog.royalty_type.code</code>.
     */
    public final TableField<RoyaltyTypeRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.royalty_type.name</code>.
     */
    public final TableField<RoyaltyTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    private RoyaltyType(Name alias, Table<RoyaltyTypeRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RoyaltyType(Name alias, Table<RoyaltyTypeRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_catalog.royalty_type</code> table reference
     */
    public RoyaltyType(String alias) {
        this(DSL.name(alias), ROYALTY_TYPE);
    }

    /**
     * Create an aliased <code>eh8s_catalog.royalty_type</code> table reference
     */
    public RoyaltyType(Name alias) {
        this(alias, ROYALTY_TYPE);
    }

    /**
     * Create a <code>eh8s_catalog.royalty_type</code> table reference
     */
    public RoyaltyType() {
        this(DSL.name("royalty_type"), null);
    }

    public <O extends Record> RoyaltyType(Table<O> path, ForeignKey<O, RoyaltyTypeRecord> childPath, InverseForeignKey<O, RoyaltyTypeRecord> parentPath) {
        super(path, childPath, parentPath, ROYALTY_TYPE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RoyaltyTypePath extends RoyaltyType implements Path<RoyaltyTypeRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RoyaltyTypePath(Table<O> path, ForeignKey<O, RoyaltyTypeRecord> childPath, InverseForeignKey<O, RoyaltyTypeRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RoyaltyTypePath(Name alias, Table<RoyaltyTypeRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RoyaltyTypePath as(String alias) {
            return new RoyaltyTypePath(DSL.name(alias), this);
        }

        @Override
        public RoyaltyTypePath as(Name alias) {
            return new RoyaltyTypePath(alias, this);
        }

        @Override
        public RoyaltyTypePath as(Table<?> alias) {
            return new RoyaltyTypePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sCatalog.EH8S_CATALOG;
    }

    @Override
    public Identity<RoyaltyTypeRecord, Long> getIdentity() {
        return (Identity<RoyaltyTypeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<RoyaltyTypeRecord> getPrimaryKey() {
        return Keys.KEY_ROYALTY_TYPE_PRIMARY;
    }

    @Override
    public List<UniqueKey<RoyaltyTypeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_ROYALTY_TYPE_UK_ROYALTY_TYPE_CODE);
    }

    private transient RoyaltyDepositPath _royaltyDeposit;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s_catalog.royalty_deposit</code> table
     */
    public RoyaltyDepositPath royaltyDeposit() {
        if (_royaltyDeposit == null)
            _royaltyDeposit = new RoyaltyDepositPath(this, null, Keys.FK_DEPOSIT_TYPE.getInverseKey());

        return _royaltyDeposit;
    }

    private transient RoyaltySplitPath _royaltySplit;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s_catalog.royalty_split</code> table
     */
    public RoyaltySplitPath royaltySplit() {
        if (_royaltySplit == null)
            _royaltySplit = new RoyaltySplitPath(this, null, Keys.FK_SPLIT_TYPE.getInverseKey());

        return _royaltySplit;
    }

    @Override
    public RoyaltyType as(String alias) {
        return new RoyaltyType(DSL.name(alias), this);
    }

    @Override
    public RoyaltyType as(Name alias) {
        return new RoyaltyType(alias, this);
    }

    @Override
    public RoyaltyType as(Table<?> alias) {
        return new RoyaltyType(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoyaltyType rename(String name) {
        return new RoyaltyType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoyaltyType rename(Name name) {
        return new RoyaltyType(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoyaltyType rename(Table<?> name) {
        return new RoyaltyType(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoyaltyType where(Condition condition) {
        return new RoyaltyType(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoyaltyType where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoyaltyType where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoyaltyType where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoyaltyType where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoyaltyType where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoyaltyType where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RoyaltyType where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoyaltyType whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RoyaltyType whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
