/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables;


import com.eh8s.eh8s.database.jooq.eh8s_catalog.Eh8sCatalog;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.Indexes;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.Track.TrackPath;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.records.SyncLicenseDealRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SyncLicenseDeal extends TableImpl<SyncLicenseDealRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_catalog.sync_license_deal</code>
     */
    public static final SyncLicenseDeal SYNC_LICENSE_DEAL = new SyncLicenseDeal();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SyncLicenseDealRecord> getRecordType() {
        return SyncLicenseDealRecord.class;
    }

    /**
     * The column <code>eh8s_catalog.sync_license_deal.id</code>.
     */
    public final TableField<SyncLicenseDealRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.track_id</code>.
     */
    public final TableField<SyncLicenseDealRecord, Long> TRACK_ID = createField(DSL.name("track_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.licensee_name</code>.
     */
    public final TableField<SyncLicenseDealRecord, String> LICENSEE_NAME = createField(DSL.name("licensee_name"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.use_description</code>.
     */
    public final TableField<SyncLicenseDealRecord, String> USE_DESCRIPTION = createField(DSL.name("use_description"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.amount_usdc</code>.
     */
    public final TableField<SyncLicenseDealRecord, BigDecimal> AMOUNT_USDC = createField(DSL.name("amount_usdc"), SQLDataType.DECIMAL(12, 2).nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.artist_usdc</code>.
     */
    public final TableField<SyncLicenseDealRecord, BigDecimal> ARTIST_USDC = createField(DSL.name("artist_usdc"), SQLDataType.DECIMAL(12, 2).nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.eh8s_usdc</code>.
     */
    public final TableField<SyncLicenseDealRecord, BigDecimal> EH8S_USDC = createField(DSL.name("eh8s_usdc"), SQLDataType.DECIMAL(12, 2).nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.status</code>.
     */
    public final TableField<SyncLicenseDealRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'proposed'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>eh8s_catalog.sync_license_deal.licensee_wallet_pubkey</code>.
     */
    public final TableField<SyncLicenseDealRecord, String> LICENSEE_WALLET_PUBKEY = createField(DSL.name("licensee_wallet_pubkey"), SQLDataType.VARCHAR(44).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.sync_license_pda</code>.
     */
    public final TableField<SyncLicenseDealRecord, String> SYNC_LICENSE_PDA = createField(DSL.name("sync_license_pda"), SQLDataType.VARCHAR(44).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.pay_tx_signature</code>.
     */
    public final TableField<SyncLicenseDealRecord, String> PAY_TX_SIGNATURE = createField(DSL.name("pay_tx_signature"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.paid_at</code>.
     */
    public final TableField<SyncLicenseDealRecord, LocalDateTime> PAID_AT = createField(DSL.name("paid_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>eh8s_catalog.sync_license_deal.created_at</code>.
     */
    public final TableField<SyncLicenseDealRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private SyncLicenseDeal(Name alias, Table<SyncLicenseDealRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SyncLicenseDeal(Name alias, Table<SyncLicenseDealRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_catalog.sync_license_deal</code> table
     * reference
     */
    public SyncLicenseDeal(String alias) {
        this(DSL.name(alias), SYNC_LICENSE_DEAL);
    }

    /**
     * Create an aliased <code>eh8s_catalog.sync_license_deal</code> table
     * reference
     */
    public SyncLicenseDeal(Name alias) {
        this(alias, SYNC_LICENSE_DEAL);
    }

    /**
     * Create a <code>eh8s_catalog.sync_license_deal</code> table reference
     */
    public SyncLicenseDeal() {
        this(DSL.name("sync_license_deal"), null);
    }

    public <O extends Record> SyncLicenseDeal(Table<O> path, ForeignKey<O, SyncLicenseDealRecord> childPath, InverseForeignKey<O, SyncLicenseDealRecord> parentPath) {
        super(path, childPath, parentPath, SYNC_LICENSE_DEAL);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SyncLicenseDealPath extends SyncLicenseDeal implements Path<SyncLicenseDealRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SyncLicenseDealPath(Table<O> path, ForeignKey<O, SyncLicenseDealRecord> childPath, InverseForeignKey<O, SyncLicenseDealRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SyncLicenseDealPath(Name alias, Table<SyncLicenseDealRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SyncLicenseDealPath as(String alias) {
            return new SyncLicenseDealPath(DSL.name(alias), this);
        }

        @Override
        public SyncLicenseDealPath as(Name alias) {
            return new SyncLicenseDealPath(alias, this);
        }

        @Override
        public SyncLicenseDealPath as(Table<?> alias) {
            return new SyncLicenseDealPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sCatalog.EH8S_CATALOG;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SYNC_LICENSE_DEAL_IDX_SYNC_DEAL_TRACK);
    }

    @Override
    public Identity<SyncLicenseDealRecord, Long> getIdentity() {
        return (Identity<SyncLicenseDealRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SyncLicenseDealRecord> getPrimaryKey() {
        return Keys.KEY_SYNC_LICENSE_DEAL_PRIMARY;
    }

    @Override
    public List<UniqueKey<SyncLicenseDealRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_SYNC_LICENSE_DEAL_UK_SYNC_DEAL_PDA, Keys.KEY_SYNC_LICENSE_DEAL_UK_SYNC_DEAL_TX);
    }

    @Override
    public List<ForeignKey<SyncLicenseDealRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_SYNC_DEAL_TRACK);
    }

    private transient TrackPath _track;

    /**
     * Get the implicit join path to the <code>eh8s_catalog.track</code> table.
     */
    public TrackPath track() {
        if (_track == null)
            _track = new TrackPath(this, Keys.FK_SYNC_DEAL_TRACK, null);

        return _track;
    }

    @Override
    public SyncLicenseDeal as(String alias) {
        return new SyncLicenseDeal(DSL.name(alias), this);
    }

    @Override
    public SyncLicenseDeal as(Name alias) {
        return new SyncLicenseDeal(alias, this);
    }

    @Override
    public SyncLicenseDeal as(Table<?> alias) {
        return new SyncLicenseDeal(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SyncLicenseDeal rename(String name) {
        return new SyncLicenseDeal(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SyncLicenseDeal rename(Name name) {
        return new SyncLicenseDeal(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SyncLicenseDeal rename(Table<?> name) {
        return new SyncLicenseDeal(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SyncLicenseDeal where(Condition condition) {
        return new SyncLicenseDeal(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SyncLicenseDeal where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SyncLicenseDeal where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SyncLicenseDeal where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SyncLicenseDeal where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SyncLicenseDeal where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SyncLicenseDeal where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SyncLicenseDeal where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SyncLicenseDeal whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SyncLicenseDeal whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
