/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables;


import com.eh8s.eh8s.database.jooq.eh8s.tables.Band.BandPath;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.Eh8sCatalog;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.RoyaltyDeposit.RoyaltyDepositPath;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.RoyaltySplit.RoyaltySplitPath;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.SyncLicenseDeal.SyncLicenseDealPath;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.records.TrackRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Track extends TableImpl<TrackRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_catalog.track</code>
     */
    public static final Track TRACK = new Track();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TrackRecord> getRecordType() {
        return TrackRecord.class;
    }

    /**
     * The column <code>eh8s_catalog.track.id</code>.
     */
    public final TableField<TrackRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s_catalog.track.band_id</code>.
     */
    public final TableField<TrackRecord, Long> BAND_ID = createField(DSL.name("band_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.track.title</code>.
     */
    public final TableField<TrackRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.VARCHAR(160).nullable(false), this, "");

    /**
     * The column <code>eh8s_catalog.track.isrc</code>.
     */
    public final TableField<TrackRecord, String> ISRC = createField(DSL.name("isrc"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_catalog.track.provider</code>.
     */
    public final TableField<TrackRecord, String> PROVIDER = createField(DSL.name("provider"), SQLDataType.VARCHAR(32).nullable(false).defaultValue(DSL.field(DSL.raw("'distrokid'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_catalog.track.royalty_pool_pda</code>.
     */
    public final TableField<TrackRecord, String> ROYALTY_POOL_PDA = createField(DSL.name("royalty_pool_pda"), SQLDataType.VARCHAR(44).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_catalog.track.pool_splits_json</code>.
     */
    public final TableField<TrackRecord, String> POOL_SPLITS_JSON = createField(DSL.name("pool_splits_json"), SQLDataType.CLOB(65535).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>eh8s_catalog.track.pool_tx_signature</code>.
     */
    public final TableField<TrackRecord, String> POOL_TX_SIGNATURE = createField(DSL.name("pool_tx_signature"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_catalog.track.pool_activated_at</code>.
     */
    public final TableField<TrackRecord, LocalDateTime> POOL_ACTIVATED_AT = createField(DSL.name("pool_activated_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    private Track(Name alias, Table<TrackRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Track(Name alias, Table<TrackRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_catalog.track</code> table reference
     */
    public Track(String alias) {
        this(DSL.name(alias), TRACK);
    }

    /**
     * Create an aliased <code>eh8s_catalog.track</code> table reference
     */
    public Track(Name alias) {
        this(alias, TRACK);
    }

    /**
     * Create a <code>eh8s_catalog.track</code> table reference
     */
    public Track() {
        this(DSL.name("track"), null);
    }

    public <O extends Record> Track(Table<O> path, ForeignKey<O, TrackRecord> childPath, InverseForeignKey<O, TrackRecord> parentPath) {
        super(path, childPath, parentPath, TRACK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TrackPath extends Track implements Path<TrackRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> TrackPath(Table<O> path, ForeignKey<O, TrackRecord> childPath, InverseForeignKey<O, TrackRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TrackPath(Name alias, Table<TrackRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TrackPath as(String alias) {
            return new TrackPath(DSL.name(alias), this);
        }

        @Override
        public TrackPath as(Name alias) {
            return new TrackPath(alias, this);
        }

        @Override
        public TrackPath as(Table<?> alias) {
            return new TrackPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sCatalog.EH8S_CATALOG;
    }

    @Override
    public Identity<TrackRecord, Long> getIdentity() {
        return (Identity<TrackRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TrackRecord> getPrimaryKey() {
        return Keys.KEY_TRACK_PRIMARY;
    }

    @Override
    public List<UniqueKey<TrackRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_TRACK_UK_TRACK_POOL_TX);
    }

    @Override
    public List<ForeignKey<TrackRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_TRACK_BAND);
    }

    private transient BandPath _band;

    /**
     * Get the implicit join path to the <code>eh8s.band</code> table.
     */
    public BandPath band() {
        if (_band == null)
            _band = new BandPath(this, Keys.FK_TRACK_BAND, null);

        return _band;
    }

    private transient RoyaltyDepositPath _royaltyDeposit;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s_catalog.royalty_deposit</code> table
     */
    public RoyaltyDepositPath royaltyDeposit() {
        if (_royaltyDeposit == null)
            _royaltyDeposit = new RoyaltyDepositPath(this, null, Keys.FK_DEPOSIT_TRACK.getInverseKey());

        return _royaltyDeposit;
    }

    private transient RoyaltySplitPath _royaltySplit;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s_catalog.royalty_split</code> table
     */
    public RoyaltySplitPath royaltySplit() {
        if (_royaltySplit == null)
            _royaltySplit = new RoyaltySplitPath(this, null, Keys.FK_SPLIT_TRACK.getInverseKey());

        return _royaltySplit;
    }

    private transient SyncLicenseDealPath _syncLicenseDeal;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s_catalog.sync_license_deal</code> table
     */
    public SyncLicenseDealPath syncLicenseDeal() {
        if (_syncLicenseDeal == null)
            _syncLicenseDeal = new SyncLicenseDealPath(this, null, Keys.FK_SYNC_DEAL_TRACK.getInverseKey());

        return _syncLicenseDeal;
    }

    @Override
    public Track as(String alias) {
        return new Track(DSL.name(alias), this);
    }

    @Override
    public Track as(Name alias) {
        return new Track(alias, this);
    }

    @Override
    public Track as(Table<?> alias) {
        return new Track(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Track rename(String name) {
        return new Track(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Track rename(Name name) {
        return new Track(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Track rename(Table<?> name) {
        return new Track(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track where(Condition condition) {
        return new Track(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Track where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Track where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Track where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Track where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Track whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
