/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_ops.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AgentAuthority implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long opsAgentId;
    private String agentWalletPubkey;
    private Byte permissions;
    private String agentAuthorityPda;
    private String ownerWalletPubkey;
    private String txSignature;
    private LocalDateTime createdAt;

    public AgentAuthority() {}

    public AgentAuthority(AgentAuthority value) {
        this.id = value.id;
        this.opsAgentId = value.opsAgentId;
        this.agentWalletPubkey = value.agentWalletPubkey;
        this.permissions = value.permissions;
        this.agentAuthorityPda = value.agentAuthorityPda;
        this.ownerWalletPubkey = value.ownerWalletPubkey;
        this.txSignature = value.txSignature;
        this.createdAt = value.createdAt;
    }

    public AgentAuthority(
        Long id,
        Long opsAgentId,
        String agentWalletPubkey,
        Byte permissions,
        String agentAuthorityPda,
        String ownerWalletPubkey,
        String txSignature,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.opsAgentId = opsAgentId;
        this.agentWalletPubkey = agentWalletPubkey;
        this.permissions = permissions;
        this.agentAuthorityPda = agentAuthorityPda;
        this.ownerWalletPubkey = ownerWalletPubkey;
        this.txSignature = txSignature;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>eh8s_ops.agent_authority.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s_ops.agent_authority.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s_ops.agent_authority.ops_agent_id</code>.
     */
    public Long getOpsAgentId() {
        return this.opsAgentId;
    }

    /**
     * Setter for <code>eh8s_ops.agent_authority.ops_agent_id</code>.
     */
    public void setOpsAgentId(Long opsAgentId) {
        this.opsAgentId = opsAgentId;
    }

    /**
     * Getter for <code>eh8s_ops.agent_authority.agent_wallet_pubkey</code>.
     */
    public String getAgentWalletPubkey() {
        return this.agentWalletPubkey;
    }

    /**
     * Setter for <code>eh8s_ops.agent_authority.agent_wallet_pubkey</code>.
     */
    public void setAgentWalletPubkey(String agentWalletPubkey) {
        this.agentWalletPubkey = agentWalletPubkey;
    }

    /**
     * Getter for <code>eh8s_ops.agent_authority.permissions</code>.
     */
    public Byte getPermissions() {
        return this.permissions;
    }

    /**
     * Setter for <code>eh8s_ops.agent_authority.permissions</code>.
     */
    public void setPermissions(Byte permissions) {
        this.permissions = permissions;
    }

    /**
     * Getter for <code>eh8s_ops.agent_authority.agent_authority_pda</code>.
     */
    public String getAgentAuthorityPda() {
        return this.agentAuthorityPda;
    }

    /**
     * Setter for <code>eh8s_ops.agent_authority.agent_authority_pda</code>.
     */
    public void setAgentAuthorityPda(String agentAuthorityPda) {
        this.agentAuthorityPda = agentAuthorityPda;
    }

    /**
     * Getter for <code>eh8s_ops.agent_authority.owner_wallet_pubkey</code>.
     */
    public String getOwnerWalletPubkey() {
        return this.ownerWalletPubkey;
    }

    /**
     * Setter for <code>eh8s_ops.agent_authority.owner_wallet_pubkey</code>.
     */
    public void setOwnerWalletPubkey(String ownerWalletPubkey) {
        this.ownerWalletPubkey = ownerWalletPubkey;
    }

    /**
     * Getter for <code>eh8s_ops.agent_authority.tx_signature</code>.
     */
    public String getTxSignature() {
        return this.txSignature;
    }

    /**
     * Setter for <code>eh8s_ops.agent_authority.tx_signature</code>.
     */
    public void setTxSignature(String txSignature) {
        this.txSignature = txSignature;
    }

    /**
     * Getter for <code>eh8s_ops.agent_authority.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>eh8s_ops.agent_authority.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AgentAuthority other = (AgentAuthority) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.opsAgentId == null) {
            if (other.opsAgentId != null)
                return false;
        }
        else if (!this.opsAgentId.equals(other.opsAgentId))
            return false;
        if (this.agentWalletPubkey == null) {
            if (other.agentWalletPubkey != null)
                return false;
        }
        else if (!this.agentWalletPubkey.equals(other.agentWalletPubkey))
            return false;
        if (this.permissions == null) {
            if (other.permissions != null)
                return false;
        }
        else if (!this.permissions.equals(other.permissions))
            return false;
        if (this.agentAuthorityPda == null) {
            if (other.agentAuthorityPda != null)
                return false;
        }
        else if (!this.agentAuthorityPda.equals(other.agentAuthorityPda))
            return false;
        if (this.ownerWalletPubkey == null) {
            if (other.ownerWalletPubkey != null)
                return false;
        }
        else if (!this.ownerWalletPubkey.equals(other.ownerWalletPubkey))
            return false;
        if (this.txSignature == null) {
            if (other.txSignature != null)
                return false;
        }
        else if (!this.txSignature.equals(other.txSignature))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.opsAgentId == null) ? 0 : this.opsAgentId.hashCode());
        result = prime * result + ((this.agentWalletPubkey == null) ? 0 : this.agentWalletPubkey.hashCode());
        result = prime * result + ((this.permissions == null) ? 0 : this.permissions.hashCode());
        result = prime * result + ((this.agentAuthorityPda == null) ? 0 : this.agentAuthorityPda.hashCode());
        result = prime * result + ((this.ownerWalletPubkey == null) ? 0 : this.ownerWalletPubkey.hashCode());
        result = prime * result + ((this.txSignature == null) ? 0 : this.txSignature.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AgentAuthority (");

        sb.append(id);
        sb.append(", ").append(opsAgentId);
        sb.append(", ").append(agentWalletPubkey);
        sb.append(", ").append(permissions);
        sb.append(", ").append(agentAuthorityPda);
        sb.append(", ").append(ownerWalletPubkey);
        sb.append(", ").append(txSignature);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
