/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_ops.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OwnerDigest implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String ownerWalletPubkey;
    private String model;
    private String metricsJson;
    private String body;
    private Integer inputTokens;
    private Integer outputTokens;
    private String slackStatus;
    private LocalDateTime createdAt;

    public OwnerDigest() {}

    public OwnerDigest(OwnerDigest value) {
        this.id = value.id;
        this.ownerWalletPubkey = value.ownerWalletPubkey;
        this.model = value.model;
        this.metricsJson = value.metricsJson;
        this.body = value.body;
        this.inputTokens = value.inputTokens;
        this.outputTokens = value.outputTokens;
        this.slackStatus = value.slackStatus;
        this.createdAt = value.createdAt;
    }

    public OwnerDigest(
        Long id,
        String ownerWalletPubkey,
        String model,
        String metricsJson,
        String body,
        Integer inputTokens,
        Integer outputTokens,
        String slackStatus,
        LocalDateTime createdAt
    ) {
        this.id = id;
        this.ownerWalletPubkey = ownerWalletPubkey;
        this.model = model;
        this.metricsJson = metricsJson;
        this.body = body;
        this.inputTokens = inputTokens;
        this.outputTokens = outputTokens;
        this.slackStatus = slackStatus;
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.owner_wallet_pubkey</code>.
     */
    public String getOwnerWalletPubkey() {
        return this.ownerWalletPubkey;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.owner_wallet_pubkey</code>.
     */
    public void setOwnerWalletPubkey(String ownerWalletPubkey) {
        this.ownerWalletPubkey = ownerWalletPubkey;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.model</code>.
     */
    public String getModel() {
        return this.model;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.model</code>.
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.metrics_json</code>.
     */
    public String getMetricsJson() {
        return this.metricsJson;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.metrics_json</code>.
     */
    public void setMetricsJson(String metricsJson) {
        this.metricsJson = metricsJson;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.body</code>.
     */
    public String getBody() {
        return this.body;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.body</code>.
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.input_tokens</code>.
     */
    public Integer getInputTokens() {
        return this.inputTokens;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.input_tokens</code>.
     */
    public void setInputTokens(Integer inputTokens) {
        this.inputTokens = inputTokens;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.output_tokens</code>.
     */
    public Integer getOutputTokens() {
        return this.outputTokens;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.output_tokens</code>.
     */
    public void setOutputTokens(Integer outputTokens) {
        this.outputTokens = outputTokens;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.slack_status</code>.
     */
    public String getSlackStatus() {
        return this.slackStatus;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.slack_status</code>.
     */
    public void setSlackStatus(String slackStatus) {
        this.slackStatus = slackStatus;
    }

    /**
     * Getter for <code>eh8s_ops.owner_digest.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>eh8s_ops.owner_digest.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OwnerDigest other = (OwnerDigest) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ownerWalletPubkey == null) {
            if (other.ownerWalletPubkey != null)
                return false;
        }
        else if (!this.ownerWalletPubkey.equals(other.ownerWalletPubkey))
            return false;
        if (this.model == null) {
            if (other.model != null)
                return false;
        }
        else if (!this.model.equals(other.model))
            return false;
        if (this.metricsJson == null) {
            if (other.metricsJson != null)
                return false;
        }
        else if (!this.metricsJson.equals(other.metricsJson))
            return false;
        if (this.body == null) {
            if (other.body != null)
                return false;
        }
        else if (!this.body.equals(other.body))
            return false;
        if (this.inputTokens == null) {
            if (other.inputTokens != null)
                return false;
        }
        else if (!this.inputTokens.equals(other.inputTokens))
            return false;
        if (this.outputTokens == null) {
            if (other.outputTokens != null)
                return false;
        }
        else if (!this.outputTokens.equals(other.outputTokens))
            return false;
        if (this.slackStatus == null) {
            if (other.slackStatus != null)
                return false;
        }
        else if (!this.slackStatus.equals(other.slackStatus))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ownerWalletPubkey == null) ? 0 : this.ownerWalletPubkey.hashCode());
        result = prime * result + ((this.model == null) ? 0 : this.model.hashCode());
        result = prime * result + ((this.metricsJson == null) ? 0 : this.metricsJson.hashCode());
        result = prime * result + ((this.body == null) ? 0 : this.body.hashCode());
        result = prime * result + ((this.inputTokens == null) ? 0 : this.inputTokens.hashCode());
        result = prime * result + ((this.outputTokens == null) ? 0 : this.outputTokens.hashCode());
        result = prime * result + ((this.slackStatus == null) ? 0 : this.slackStatus.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OwnerDigest (");

        sb.append(id);
        sb.append(", ").append(ownerWalletPubkey);
        sb.append(", ").append(model);
        sb.append(", ").append(metricsJson);
        sb.append(", ").append(body);
        sb.append(", ").append(inputTokens);
        sb.append(", ").append(outputTokens);
        sb.append(", ").append(slackStatus);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
