/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_ops.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OwnerDecision implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long opsAgentId;
    private String title;
    private String semaphore;
    private String payload;
    private String status;
    private String rejectReason;
    private LocalDateTime resolvedAt;
    private String answeredVia;
    private String answeredBy;
    private Long relatedBookingId;

    public OwnerDecision() {}

    public OwnerDecision(OwnerDecision value) {
        this.id = value.id;
        this.opsAgentId = value.opsAgentId;
        this.title = value.title;
        this.semaphore = value.semaphore;
        this.payload = value.payload;
        this.status = value.status;
        this.rejectReason = value.rejectReason;
        this.resolvedAt = value.resolvedAt;
        this.answeredVia = value.answeredVia;
        this.answeredBy = value.answeredBy;
        this.relatedBookingId = value.relatedBookingId;
    }

    public OwnerDecision(
        Long id,
        Long opsAgentId,
        String title,
        String semaphore,
        String payload,
        String status,
        String rejectReason,
        LocalDateTime resolvedAt,
        String answeredVia,
        String answeredBy,
        Long relatedBookingId
    ) {
        this.id = id;
        this.opsAgentId = opsAgentId;
        this.title = title;
        this.semaphore = semaphore;
        this.payload = payload;
        this.status = status;
        this.rejectReason = rejectReason;
        this.resolvedAt = resolvedAt;
        this.answeredVia = answeredVia;
        this.answeredBy = answeredBy;
        this.relatedBookingId = relatedBookingId;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.ops_agent_id</code>.
     */
    public Long getOpsAgentId() {
        return this.opsAgentId;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.ops_agent_id</code>.
     */
    public void setOpsAgentId(Long opsAgentId) {
        this.opsAgentId = opsAgentId;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.semaphore</code>.
     */
    public String getSemaphore() {
        return this.semaphore;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.semaphore</code>.
     */
    public void setSemaphore(String semaphore) {
        this.semaphore = semaphore;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.payload</code>.
     */
    public String getPayload() {
        return this.payload;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.payload</code>.
     */
    public void setPayload(String payload) {
        this.payload = payload;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.reject_reason</code>.
     */
    public String getRejectReason() {
        return this.rejectReason;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.reject_reason</code>.
     */
    public void setRejectReason(String rejectReason) {
        this.rejectReason = rejectReason;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.resolved_at</code>.
     */
    public LocalDateTime getResolvedAt() {
        return this.resolvedAt;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.resolved_at</code>.
     */
    public void setResolvedAt(LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.answered_via</code>.
     */
    public String getAnsweredVia() {
        return this.answeredVia;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.answered_via</code>.
     */
    public void setAnsweredVia(String answeredVia) {
        this.answeredVia = answeredVia;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.answered_by</code>.
     */
    public String getAnsweredBy() {
        return this.answeredBy;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.answered_by</code>.
     */
    public void setAnsweredBy(String answeredBy) {
        this.answeredBy = answeredBy;
    }

    /**
     * Getter for <code>eh8s_ops.owner_decision.related_booking_id</code>.
     */
    public Long getRelatedBookingId() {
        return this.relatedBookingId;
    }

    /**
     * Setter for <code>eh8s_ops.owner_decision.related_booking_id</code>.
     */
    public void setRelatedBookingId(Long relatedBookingId) {
        this.relatedBookingId = relatedBookingId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OwnerDecision other = (OwnerDecision) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.opsAgentId == null) {
            if (other.opsAgentId != null)
                return false;
        }
        else if (!this.opsAgentId.equals(other.opsAgentId))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.semaphore == null) {
            if (other.semaphore != null)
                return false;
        }
        else if (!this.semaphore.equals(other.semaphore))
            return false;
        if (this.payload == null) {
            if (other.payload != null)
                return false;
        }
        else if (!this.payload.equals(other.payload))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.rejectReason == null) {
            if (other.rejectReason != null)
                return false;
        }
        else if (!this.rejectReason.equals(other.rejectReason))
            return false;
        if (this.resolvedAt == null) {
            if (other.resolvedAt != null)
                return false;
        }
        else if (!this.resolvedAt.equals(other.resolvedAt))
            return false;
        if (this.answeredVia == null) {
            if (other.answeredVia != null)
                return false;
        }
        else if (!this.answeredVia.equals(other.answeredVia))
            return false;
        if (this.answeredBy == null) {
            if (other.answeredBy != null)
                return false;
        }
        else if (!this.answeredBy.equals(other.answeredBy))
            return false;
        if (this.relatedBookingId == null) {
            if (other.relatedBookingId != null)
                return false;
        }
        else if (!this.relatedBookingId.equals(other.relatedBookingId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.opsAgentId == null) ? 0 : this.opsAgentId.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.semaphore == null) ? 0 : this.semaphore.hashCode());
        result = prime * result + ((this.payload == null) ? 0 : this.payload.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.rejectReason == null) ? 0 : this.rejectReason.hashCode());
        result = prime * result + ((this.resolvedAt == null) ? 0 : this.resolvedAt.hashCode());
        result = prime * result + ((this.answeredVia == null) ? 0 : this.answeredVia.hashCode());
        result = prime * result + ((this.answeredBy == null) ? 0 : this.answeredBy.hashCode());
        result = prime * result + ((this.relatedBookingId == null) ? 0 : this.relatedBookingId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OwnerDecision (");

        sb.append(id);
        sb.append(", ").append(opsAgentId);
        sb.append(", ").append(title);
        sb.append(", ").append(semaphore);
        sb.append(", ").append(payload);
        sb.append(", ").append(status);
        sb.append(", ").append(rejectReason);
        sb.append(", ").append(resolvedAt);
        sb.append(", ").append(answeredVia);
        sb.append(", ").append(answeredBy);
        sb.append(", ").append(relatedBookingId);

        sb.append(")");
        return sb.toString();
    }
}
