/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_ops.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SlackDeliveryLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long ownerDecisionId;
    private Long agentEventId;
    private String ownerWalletPubkey;
    private String requesterWalletPubkey;
    private String bridgeMode;
    private String channelHint;
    private String payloadPreview;
    private String status;
    private Integer httpStatus;
    private String errorMessage;
    private LocalDateTime deliveredAt;

    public SlackDeliveryLog() {}

    public SlackDeliveryLog(SlackDeliveryLog value) {
        this.id = value.id;
        this.ownerDecisionId = value.ownerDecisionId;
        this.agentEventId = value.agentEventId;
        this.ownerWalletPubkey = value.ownerWalletPubkey;
        this.requesterWalletPubkey = value.requesterWalletPubkey;
        this.bridgeMode = value.bridgeMode;
        this.channelHint = value.channelHint;
        this.payloadPreview = value.payloadPreview;
        this.status = value.status;
        this.httpStatus = value.httpStatus;
        this.errorMessage = value.errorMessage;
        this.deliveredAt = value.deliveredAt;
    }

    public SlackDeliveryLog(
        Long id,
        Long ownerDecisionId,
        Long agentEventId,
        String ownerWalletPubkey,
        String requesterWalletPubkey,
        String bridgeMode,
        String channelHint,
        String payloadPreview,
        String status,
        Integer httpStatus,
        String errorMessage,
        LocalDateTime deliveredAt
    ) {
        this.id = id;
        this.ownerDecisionId = ownerDecisionId;
        this.agentEventId = agentEventId;
        this.ownerWalletPubkey = ownerWalletPubkey;
        this.requesterWalletPubkey = requesterWalletPubkey;
        this.bridgeMode = bridgeMode;
        this.channelHint = channelHint;
        this.payloadPreview = payloadPreview;
        this.status = status;
        this.httpStatus = httpStatus;
        this.errorMessage = errorMessage;
        this.deliveredAt = deliveredAt;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.owner_decision_id</code>.
     */
    public Long getOwnerDecisionId() {
        return this.ownerDecisionId;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.owner_decision_id</code>.
     */
    public void setOwnerDecisionId(Long ownerDecisionId) {
        this.ownerDecisionId = ownerDecisionId;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.agent_event_id</code>.
     */
    public Long getAgentEventId() {
        return this.agentEventId;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.agent_event_id</code>.
     */
    public void setAgentEventId(Long agentEventId) {
        this.agentEventId = agentEventId;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.owner_wallet_pubkey</code>.
     */
    public String getOwnerWalletPubkey() {
        return this.ownerWalletPubkey;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.owner_wallet_pubkey</code>.
     */
    public void setOwnerWalletPubkey(String ownerWalletPubkey) {
        this.ownerWalletPubkey = ownerWalletPubkey;
    }

    /**
     * Getter for
     * <code>eh8s_ops.slack_delivery_log.requester_wallet_pubkey</code>.
     */
    public String getRequesterWalletPubkey() {
        return this.requesterWalletPubkey;
    }

    /**
     * Setter for
     * <code>eh8s_ops.slack_delivery_log.requester_wallet_pubkey</code>.
     */
    public void setRequesterWalletPubkey(String requesterWalletPubkey) {
        this.requesterWalletPubkey = requesterWalletPubkey;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.bridge_mode</code>.
     */
    public String getBridgeMode() {
        return this.bridgeMode;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.bridge_mode</code>.
     */
    public void setBridgeMode(String bridgeMode) {
        this.bridgeMode = bridgeMode;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.channel_hint</code>.
     */
    public String getChannelHint() {
        return this.channelHint;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.channel_hint</code>.
     */
    public void setChannelHint(String channelHint) {
        this.channelHint = channelHint;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.payload_preview</code>.
     */
    public String getPayloadPreview() {
        return this.payloadPreview;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.payload_preview</code>.
     */
    public void setPayloadPreview(String payloadPreview) {
        this.payloadPreview = payloadPreview;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.http_status</code>.
     */
    public Integer getHttpStatus() {
        return this.httpStatus;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.http_status</code>.
     */
    public void setHttpStatus(Integer httpStatus) {
        this.httpStatus = httpStatus;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.error_message</code>.
     */
    public String getErrorMessage() {
        return this.errorMessage;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.error_message</code>.
     */
    public void setErrorMessage(String errorMessage) {
        this.errorMessage = errorMessage;
    }

    /**
     * Getter for <code>eh8s_ops.slack_delivery_log.delivered_at</code>.
     */
    public LocalDateTime getDeliveredAt() {
        return this.deliveredAt;
    }

    /**
     * Setter for <code>eh8s_ops.slack_delivery_log.delivered_at</code>.
     */
    public void setDeliveredAt(LocalDateTime deliveredAt) {
        this.deliveredAt = deliveredAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SlackDeliveryLog other = (SlackDeliveryLog) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ownerDecisionId == null) {
            if (other.ownerDecisionId != null)
                return false;
        }
        else if (!this.ownerDecisionId.equals(other.ownerDecisionId))
            return false;
        if (this.agentEventId == null) {
            if (other.agentEventId != null)
                return false;
        }
        else if (!this.agentEventId.equals(other.agentEventId))
            return false;
        if (this.ownerWalletPubkey == null) {
            if (other.ownerWalletPubkey != null)
                return false;
        }
        else if (!this.ownerWalletPubkey.equals(other.ownerWalletPubkey))
            return false;
        if (this.requesterWalletPubkey == null) {
            if (other.requesterWalletPubkey != null)
                return false;
        }
        else if (!this.requesterWalletPubkey.equals(other.requesterWalletPubkey))
            return false;
        if (this.bridgeMode == null) {
            if (other.bridgeMode != null)
                return false;
        }
        else if (!this.bridgeMode.equals(other.bridgeMode))
            return false;
        if (this.channelHint == null) {
            if (other.channelHint != null)
                return false;
        }
        else if (!this.channelHint.equals(other.channelHint))
            return false;
        if (this.payloadPreview == null) {
            if (other.payloadPreview != null)
                return false;
        }
        else if (!this.payloadPreview.equals(other.payloadPreview))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        if (this.httpStatus == null) {
            if (other.httpStatus != null)
                return false;
        }
        else if (!this.httpStatus.equals(other.httpStatus))
            return false;
        if (this.errorMessage == null) {
            if (other.errorMessage != null)
                return false;
        }
        else if (!this.errorMessage.equals(other.errorMessage))
            return false;
        if (this.deliveredAt == null) {
            if (other.deliveredAt != null)
                return false;
        }
        else if (!this.deliveredAt.equals(other.deliveredAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ownerDecisionId == null) ? 0 : this.ownerDecisionId.hashCode());
        result = prime * result + ((this.agentEventId == null) ? 0 : this.agentEventId.hashCode());
        result = prime * result + ((this.ownerWalletPubkey == null) ? 0 : this.ownerWalletPubkey.hashCode());
        result = prime * result + ((this.requesterWalletPubkey == null) ? 0 : this.requesterWalletPubkey.hashCode());
        result = prime * result + ((this.bridgeMode == null) ? 0 : this.bridgeMode.hashCode());
        result = prime * result + ((this.channelHint == null) ? 0 : this.channelHint.hashCode());
        result = prime * result + ((this.payloadPreview == null) ? 0 : this.payloadPreview.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.httpStatus == null) ? 0 : this.httpStatus.hashCode());
        result = prime * result + ((this.errorMessage == null) ? 0 : this.errorMessage.hashCode());
        result = prime * result + ((this.deliveredAt == null) ? 0 : this.deliveredAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SlackDeliveryLog (");

        sb.append(id);
        sb.append(", ").append(ownerDecisionId);
        sb.append(", ").append(agentEventId);
        sb.append(", ").append(ownerWalletPubkey);
        sb.append(", ").append(requesterWalletPubkey);
        sb.append(", ").append(bridgeMode);
        sb.append(", ").append(channelHint);
        sb.append(", ").append(payloadPreview);
        sb.append(", ").append(status);
        sb.append(", ").append(httpStatus);
        sb.append(", ").append(errorMessage);
        sb.append(", ").append(deliveredAt);

        sb.append(")");
        return sb.toString();
    }
}
