/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables;


import com.eh8s.eh8s.database.jooq.eh8s.Eh8s;
import com.eh8s.eh8s.database.jooq.eh8s.Keys;
import com.eh8s.eh8s.database.jooq.eh8s.tables.Band.BandPath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.MusicianProfile.MusicianProfilePath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.BandMemberRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BandMember extends TableImpl<BandMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s.band_member</code>
     */
    public static final BandMember BAND_MEMBER = new BandMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BandMemberRecord> getRecordType() {
        return BandMemberRecord.class;
    }

    /**
     * The column <code>eh8s.band_member.id</code>.
     */
    public final TableField<BandMemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s.band_member.band_id</code>.
     */
    public final TableField<BandMemberRecord, Long> BAND_ID = createField(DSL.name("band_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s.band_member.musician_profile_id</code>.
     */
    public final TableField<BandMemberRecord, Long> MUSICIAN_PROFILE_ID = createField(DSL.name("musician_profile_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s.band_member.role_in_band</code>.
     */
    public final TableField<BandMemberRecord, String> ROLE_IN_BAND = createField(DSL.name("role_in_band"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>eh8s.band_member.joined_at</code>.
     */
    public final TableField<BandMemberRecord, LocalDate> JOINED_AT = createField(DSL.name("joined_at"), SQLDataType.LOCALDATE.nullable(false), this, "");

    private BandMember(Name alias, Table<BandMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BandMember(Name alias, Table<BandMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s.band_member</code> table reference
     */
    public BandMember(String alias) {
        this(DSL.name(alias), BAND_MEMBER);
    }

    /**
     * Create an aliased <code>eh8s.band_member</code> table reference
     */
    public BandMember(Name alias) {
        this(alias, BAND_MEMBER);
    }

    /**
     * Create a <code>eh8s.band_member</code> table reference
     */
    public BandMember() {
        this(DSL.name("band_member"), null);
    }

    public <O extends Record> BandMember(Table<O> path, ForeignKey<O, BandMemberRecord> childPath, InverseForeignKey<O, BandMemberRecord> parentPath) {
        super(path, childPath, parentPath, BAND_MEMBER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BandMemberPath extends BandMember implements Path<BandMemberRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BandMemberPath(Table<O> path, ForeignKey<O, BandMemberRecord> childPath, InverseForeignKey<O, BandMemberRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BandMemberPath(Name alias, Table<BandMemberRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BandMemberPath as(String alias) {
            return new BandMemberPath(DSL.name(alias), this);
        }

        @Override
        public BandMemberPath as(Name alias) {
            return new BandMemberPath(alias, this);
        }

        @Override
        public BandMemberPath as(Table<?> alias) {
            return new BandMemberPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8s.EH8S;
    }

    @Override
    public Identity<BandMemberRecord, Long> getIdentity() {
        return (Identity<BandMemberRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BandMemberRecord> getPrimaryKey() {
        return Keys.KEY_BAND_MEMBER_PRIMARY;
    }

    @Override
    public List<UniqueKey<BandMemberRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_BAND_MEMBER_UK_BAND_MEMBER);
    }

    @Override
    public List<ForeignKey<BandMemberRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_MEMBER_BAND, Keys.FK_MEMBER_MUSICIAN);
    }

    private transient BandPath _band;

    /**
     * Get the implicit join path to the <code>eh8s.band</code> table.
     */
    public BandPath band() {
        if (_band == null)
            _band = new BandPath(this, Keys.FK_MEMBER_BAND, null);

        return _band;
    }

    private transient MusicianProfilePath _musicianProfile;

    /**
     * Get the implicit join path to the <code>eh8s.musician_profile</code>
     * table.
     */
    public MusicianProfilePath musicianProfile() {
        if (_musicianProfile == null)
            _musicianProfile = new MusicianProfilePath(this, Keys.FK_MEMBER_MUSICIAN, null);

        return _musicianProfile;
    }

    @Override
    public BandMember as(String alias) {
        return new BandMember(DSL.name(alias), this);
    }

    @Override
    public BandMember as(Name alias) {
        return new BandMember(alias, this);
    }

    @Override
    public BandMember as(Table<?> alias) {
        return new BandMember(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BandMember rename(String name) {
        return new BandMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BandMember rename(Name name) {
        return new BandMember(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BandMember rename(Table<?> name) {
        return new BandMember(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandMember where(Condition condition) {
        return new BandMember(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandMember where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandMember where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandMember where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BandMember where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BandMember where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BandMember where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BandMember where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandMember whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BandMember whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
