/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables;


import com.eh8s.eh8s.database.jooq.eh8s.Eh8s;
import com.eh8s.eh8s.database.jooq.eh8s.Keys;
import com.eh8s.eh8s.database.jooq.eh8s.tables.MusicianProfile.MusicianProfilePath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.RehearsalSession.RehearsalSessionPath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.CreativeRatingRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Check;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CreativeRating extends TableImpl<CreativeRatingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s.creative_rating</code>
     */
    public static final CreativeRating CREATIVE_RATING = new CreativeRating();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CreativeRatingRecord> getRecordType() {
        return CreativeRatingRecord.class;
    }

    /**
     * The column <code>eh8s.creative_rating.id</code>.
     */
    public final TableField<CreativeRatingRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s.creative_rating.rehearsal_session_id</code>.
     */
    public final TableField<CreativeRatingRecord, Long> REHEARSAL_SESSION_ID = createField(DSL.name("rehearsal_session_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s.creative_rating.rater_profile_id</code>.
     */
    public final TableField<CreativeRatingRecord, Long> RATER_PROFILE_ID = createField(DSL.name("rater_profile_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s.creative_rating.ratee_profile_id</code>.
     */
    public final TableField<CreativeRatingRecord, Long> RATEE_PROFILE_ID = createField(DSL.name("ratee_profile_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s.creative_rating.score</code>.
     */
    public final TableField<CreativeRatingRecord, Byte> SCORE = createField(DSL.name("score"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>eh8s.creative_rating.created_at</code>.
     */
    public final TableField<CreativeRatingRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private CreativeRating(Name alias, Table<CreativeRatingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CreativeRating(Name alias, Table<CreativeRatingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s.creative_rating</code> table reference
     */
    public CreativeRating(String alias) {
        this(DSL.name(alias), CREATIVE_RATING);
    }

    /**
     * Create an aliased <code>eh8s.creative_rating</code> table reference
     */
    public CreativeRating(Name alias) {
        this(alias, CREATIVE_RATING);
    }

    /**
     * Create a <code>eh8s.creative_rating</code> table reference
     */
    public CreativeRating() {
        this(DSL.name("creative_rating"), null);
    }

    public <O extends Record> CreativeRating(Table<O> path, ForeignKey<O, CreativeRatingRecord> childPath, InverseForeignKey<O, CreativeRatingRecord> parentPath) {
        super(path, childPath, parentPath, CREATIVE_RATING);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class CreativeRatingPath extends CreativeRating implements Path<CreativeRatingRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> CreativeRatingPath(Table<O> path, ForeignKey<O, CreativeRatingRecord> childPath, InverseForeignKey<O, CreativeRatingRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private CreativeRatingPath(Name alias, Table<CreativeRatingRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public CreativeRatingPath as(String alias) {
            return new CreativeRatingPath(DSL.name(alias), this);
        }

        @Override
        public CreativeRatingPath as(Name alias) {
            return new CreativeRatingPath(alias, this);
        }

        @Override
        public CreativeRatingPath as(Table<?> alias) {
            return new CreativeRatingPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8s.EH8S;
    }

    @Override
    public Identity<CreativeRatingRecord, Long> getIdentity() {
        return (Identity<CreativeRatingRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<CreativeRatingRecord> getPrimaryKey() {
        return Keys.KEY_CREATIVE_RATING_PRIMARY;
    }

    @Override
    public List<UniqueKey<CreativeRatingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_CREATIVE_RATING_UK_CREATIVE_RATING);
    }

    @Override
    public List<ForeignKey<CreativeRatingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_CREATIVE_RATING_RATEE, Keys.FK_CREATIVE_RATING_RATER, Keys.FK_CREATIVE_RATING_SESSION);
    }

    private transient MusicianProfilePath _fkCreativeRatingRatee;

    /**
     * Get the implicit join path to the <code>eh8s.musician_profile</code>
     * table, via the <code>fk_creative_rating_ratee</code> key.
     */
    public MusicianProfilePath fkCreativeRatingRatee() {
        if (_fkCreativeRatingRatee == null)
            _fkCreativeRatingRatee = new MusicianProfilePath(this, Keys.FK_CREATIVE_RATING_RATEE, null);

        return _fkCreativeRatingRatee;
    }

    private transient MusicianProfilePath _fkCreativeRatingRater;

    /**
     * Get the implicit join path to the <code>eh8s.musician_profile</code>
     * table, via the <code>fk_creative_rating_rater</code> key.
     */
    public MusicianProfilePath fkCreativeRatingRater() {
        if (_fkCreativeRatingRater == null)
            _fkCreativeRatingRater = new MusicianProfilePath(this, Keys.FK_CREATIVE_RATING_RATER, null);

        return _fkCreativeRatingRater;
    }

    private transient RehearsalSessionPath _rehearsalSession;

    /**
     * Get the implicit join path to the <code>eh8s.rehearsal_session</code>
     * table.
     */
    public RehearsalSessionPath rehearsalSession() {
        if (_rehearsalSession == null)
            _rehearsalSession = new RehearsalSessionPath(this, Keys.FK_CREATIVE_RATING_SESSION, null);

        return _rehearsalSession;
    }

    @Override
    public List<Check<CreativeRatingRecord>> getChecks() {
        return Arrays.asList(
            Internal.createCheck(this, DSL.name("ck_creative_rating_score"), "`score` between 1 and 5", true),
            Internal.createCheck(this, DSL.name("ck_creative_rating_self"), "`rater_profile_id` <> `ratee_profile_id`", true)
        );
    }

    @Override
    public CreativeRating as(String alias) {
        return new CreativeRating(DSL.name(alias), this);
    }

    @Override
    public CreativeRating as(Name alias) {
        return new CreativeRating(alias, this);
    }

    @Override
    public CreativeRating as(Table<?> alias) {
        return new CreativeRating(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CreativeRating rename(String name) {
        return new CreativeRating(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CreativeRating rename(Name name) {
        return new CreativeRating(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CreativeRating rename(Table<?> name) {
        return new CreativeRating(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreativeRating where(Condition condition) {
        return new CreativeRating(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreativeRating where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreativeRating where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreativeRating where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CreativeRating where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CreativeRating where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CreativeRating where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CreativeRating where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreativeRating whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CreativeRating whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
