/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables;


import com.eh8s.eh8s.database.jooq.eh8s.Eh8s;
import com.eh8s.eh8s.database.jooq.eh8s.Keys;
import com.eh8s.eh8s.database.jooq.eh8s.tables.Booking.BookingPath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.Concert.ConcertPath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.ContractType.ContractTypePath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.VenueAvailability.VenueAvailabilityPath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.VenueRecord;
import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.TourPlanStop.TourPlanStopPath;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Venue extends TableImpl<VenueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s.venue</code>
     */
    public static final Venue VENUE = new Venue();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VenueRecord> getRecordType() {
        return VenueRecord.class;
    }

    /**
     * The column <code>eh8s.venue.id</code>.
     */
    public final TableField<VenueRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s.venue.code</code>.
     */
    public final TableField<VenueRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.name</code>.
     */
    public final TableField<VenueRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(120).nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.city</code>.
     */
    public final TableField<VenueRecord, String> CITY = createField(DSL.name("city"), SQLDataType.VARCHAR(80).nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.country_code</code>.
     */
    public final TableField<VenueRecord, String> COUNTRY_CODE = createField(DSL.name("country_code"), SQLDataType.CHAR(3).nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.capacity</code>.
     */
    public final TableField<VenueRecord, Integer> CAPACITY = createField(DSL.name("capacity"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.suggested_ticket_usdc</code>.
     */
    public final TableField<VenueRecord, BigDecimal> SUGGESTED_TICKET_USDC = createField(DSL.name("suggested_ticket_usdc"), SQLDataType.DECIMAL(12, 2).nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.latitude</code>.
     */
    public final TableField<VenueRecord, BigDecimal> LATITUDE = createField(DSL.name("latitude"), SQLDataType.DECIMAL(10, 7).nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.longitude</code>.
     */
    public final TableField<VenueRecord, BigDecimal> LONGITUDE = createField(DSL.name("longitude"), SQLDataType.DECIMAL(10, 7).nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.pin_status</code>.
     */
    public final TableField<VenueRecord, String> PIN_STATUS = createField(DSL.name("pin_status"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.is_partner</code>.
     */
    public final TableField<VenueRecord, Byte> IS_PARTNER = createField(DSL.name("is_partner"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>eh8s.venue.eh8s_rating</code>.
     */
    public final TableField<VenueRecord, Byte> EH8S_RATING = createField(DSL.name("eh8s_rating"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("5"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>eh8s.venue.sound_included</code>.
     */
    public final TableField<VenueRecord, Byte> SOUND_INCLUDED = createField(DSL.name("sound_included"), SQLDataType.TINYINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>eh8s.venue.preferred_genres</code>.
     */
    public final TableField<VenueRecord, String> PREFERRED_GENRES = createField(DSL.name("preferred_genres"), SQLDataType.VARCHAR(160).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s.venue.contract_type_id</code>.
     */
    public final TableField<VenueRecord, Long> CONTRACT_TYPE_ID = createField(DSL.name("contract_type_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s.venue.venue_listing_pda</code>.
     */
    public final TableField<VenueRecord, String> VENUE_LISTING_PDA = createField(DSL.name("venue_listing_pda"), SQLDataType.VARCHAR(44).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s.venue.wallet_pubkey</code>.
     */
    public final TableField<VenueRecord, String> WALLET_PUBKEY = createField(DSL.name("wallet_pubkey"), SQLDataType.VARCHAR(44).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s.venue.listing_status</code>.
     */
    public final TableField<VenueRecord, String> LISTING_STATUS = createField(DSL.name("listing_status"), SQLDataType.VARCHAR(16).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s.venue.register_tx_signature</code>.
     */
    public final TableField<VenueRecord, String> REGISTER_TX_SIGNATURE = createField(DSL.name("register_tx_signature"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s.venue.approve_tx_signature</code>.
     */
    public final TableField<VenueRecord, String> APPROVE_TX_SIGNATURE = createField(DSL.name("approve_tx_signature"), SQLDataType.VARCHAR(128).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s.venue.approved_by_wallet</code>.
     */
    public final TableField<VenueRecord, String> APPROVED_BY_WALLET = createField(DSL.name("approved_by_wallet"), SQLDataType.VARCHAR(44).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    private Venue(Name alias, Table<VenueRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Venue(Name alias, Table<VenueRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s.venue</code> table reference
     */
    public Venue(String alias) {
        this(DSL.name(alias), VENUE);
    }

    /**
     * Create an aliased <code>eh8s.venue</code> table reference
     */
    public Venue(Name alias) {
        this(alias, VENUE);
    }

    /**
     * Create a <code>eh8s.venue</code> table reference
     */
    public Venue() {
        this(DSL.name("venue"), null);
    }

    public <O extends Record> Venue(Table<O> path, ForeignKey<O, VenueRecord> childPath, InverseForeignKey<O, VenueRecord> parentPath) {
        super(path, childPath, parentPath, VENUE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class VenuePath extends Venue implements Path<VenueRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> VenuePath(Table<O> path, ForeignKey<O, VenueRecord> childPath, InverseForeignKey<O, VenueRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private VenuePath(Name alias, Table<VenueRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public VenuePath as(String alias) {
            return new VenuePath(DSL.name(alias), this);
        }

        @Override
        public VenuePath as(Name alias) {
            return new VenuePath(alias, this);
        }

        @Override
        public VenuePath as(Table<?> alias) {
            return new VenuePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8s.EH8S;
    }

    @Override
    public Identity<VenueRecord, Long> getIdentity() {
        return (Identity<VenueRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VenueRecord> getPrimaryKey() {
        return Keys.KEY_VENUE_PRIMARY;
    }

    @Override
    public List<UniqueKey<VenueRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_VENUE_UK_VENUE_APPROVE_TX, Keys.KEY_VENUE_UK_VENUE_CODE, Keys.KEY_VENUE_UK_VENUE_REGISTER_TX);
    }

    @Override
    public List<ForeignKey<VenueRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_VENUE_CONTRACT);
    }

    private transient ContractTypePath _contractType;

    /**
     * Get the implicit join path to the <code>eh8s.contract_type</code> table.
     */
    public ContractTypePath contractType() {
        if (_contractType == null)
            _contractType = new ContractTypePath(this, Keys.FK_VENUE_CONTRACT, null);

        return _contractType;
    }

    private transient VenueAvailabilityPath _venueAvailability;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s.venue_availability</code> table
     */
    public VenueAvailabilityPath venueAvailability() {
        if (_venueAvailability == null)
            _venueAvailability = new VenueAvailabilityPath(this, null, Keys.FK_AVAILABILITY_VENUE.getInverseKey());

        return _venueAvailability;
    }

    private transient BookingPath _booking;

    /**
     * Get the implicit to-many join path to the <code>eh8s.booking</code> table
     */
    public BookingPath booking() {
        if (_booking == null)
            _booking = new BookingPath(this, null, Keys.FK_BOOKING_VENUE.getInverseKey());

        return _booking;
    }

    private transient ConcertPath _concert;

    /**
     * Get the implicit to-many join path to the <code>eh8s.concert</code> table
     */
    public ConcertPath concert() {
        if (_concert == null)
            _concert = new ConcertPath(this, null, Keys.FK_CONCERT_VENUE.getInverseKey());

        return _concert;
    }

    private transient TourPlanStopPath _tourPlanStop;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s_catalog.tour_plan_stop</code> table
     */
    public TourPlanStopPath tourPlanStop() {
        if (_tourPlanStop == null)
            _tourPlanStop = new TourPlanStopPath(this, null, com.eh8s.eh8s.database.jooq.eh8s_catalog.Keys.FK_TOUR_STOP_VENUE.getInverseKey());

        return _tourPlanStop;
    }

    @Override
    public Venue as(String alias) {
        return new Venue(DSL.name(alias), this);
    }

    @Override
    public Venue as(Name alias) {
        return new Venue(alias, this);
    }

    @Override
    public Venue as(Table<?> alias) {
        return new Venue(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Venue rename(String name) {
        return new Venue(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Venue rename(Name name) {
        return new Venue(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Venue rename(Table<?> name) {
        return new Venue(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Venue where(Condition condition) {
        return new Venue(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Venue where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Venue where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Venue where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Venue where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Venue where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Venue where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Venue where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Venue whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Venue whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
