/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_role.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_role.tables.AccountRole;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRoleRecord extends UpdatableRecordImpl<AccountRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_role.account_role.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_role.account_role.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_role.account_role.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_role.account_role.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s_role.account_role.role</code>.
     */
    public void setRole(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_role.account_role.role</code>.
     */
    public String getRole() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s_role.account_role.granted_at</code>.
     */
    public void setGrantedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_role.account_role.granted_at</code>.
     */
    public LocalDateTime getGrantedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>eh8s_role.account_role.application_id</code>.
     */
    public void setApplicationId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_role.account_role.application_id</code>.
     */
    public Long getApplicationId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRoleRecord
     */
    public AccountRoleRecord() {
        super(AccountRole.ACCOUNT_ROLE);
    }

    /**
     * Create a detached, initialised AccountRoleRecord
     */
    public AccountRoleRecord(Long id, Long accountId, String role, LocalDateTime grantedAt, Long applicationId) {
        super(AccountRole.ACCOUNT_ROLE);

        setId(id);
        setAccountId(accountId);
        setRole(role);
        setGrantedAt(grantedAt);
        setApplicationId(applicationId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountRoleRecord
     */
    public AccountRoleRecord(com.eh8s.eh8s.database.jooq.eh8s_role.tables.pojos.AccountRole value) {
        super(AccountRole.ACCOUNT_ROLE);

        if (value != null) {
            setId(value.getId());
            setAccountId(value.getAccountId());
            setRole(value.getRole());
            setGrantedAt(value.getGrantedAt());
            setApplicationId(value.getApplicationId());
            resetChangedOnNotNull();
        }
    }
}
