/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_ops.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_ops.tables.OpsAgent;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OpsAgentRecord extends UpdatableRecordImpl<OpsAgentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_ops.ops_agent.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_ops.ops_agent.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>eh8s_ops.ops_agent.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s_ops.ops_agent.role_summary</code>.
     */
    public void setRoleSummary(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.role_summary</code>.
     */
    public String getRoleSummary() {
        return (String) get(3);
    }

    /**
     * Setter for <code>eh8s_ops.ops_agent.semaphore</code>.
     */
    public void setSemaphore(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.semaphore</code>.
     */
    public String getSemaphore() {
        return (String) get(4);
    }

    /**
     * Setter for <code>eh8s_ops.ops_agent.task_status</code>.
     */
    public void setTaskStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.task_status</code>.
     */
    public String getTaskStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eh8s_ops.ops_agent.on_chain_permission</code>.
     */
    public void setOnChainPermission(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.on_chain_permission</code>.
     */
    public Byte getOnChainPermission() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>eh8s_ops.ops_agent.permission_bits</code>.
     */
    public void setPermissionBits(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.permission_bits</code>.
     */
    public Byte getPermissionBits() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>eh8s_ops.ops_agent.wallet_pubkey</code>.
     */
    public void setWalletPubkey(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>eh8s_ops.ops_agent.wallet_pubkey</code>.
     */
    public String getWalletPubkey() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OpsAgentRecord
     */
    public OpsAgentRecord() {
        super(OpsAgent.OPS_AGENT);
    }

    /**
     * Create a detached, initialised OpsAgentRecord
     */
    public OpsAgentRecord(Long id, String code, String name, String roleSummary, String semaphore, String taskStatus, Byte onChainPermission, Byte permissionBits, String walletPubkey) {
        super(OpsAgent.OPS_AGENT);

        setId(id);
        setCode(code);
        setName(name);
        setRoleSummary(roleSummary);
        setSemaphore(semaphore);
        setTaskStatus(taskStatus);
        setOnChainPermission(onChainPermission);
        setPermissionBits(permissionBits);
        setWalletPubkey(walletPubkey);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised OpsAgentRecord
     */
    public OpsAgentRecord(com.eh8s.eh8s.database.jooq.eh8s_ops.tables.pojos.OpsAgent value) {
        super(OpsAgent.OPS_AGENT);

        if (value != null) {
            setId(value.getId());
            setCode(value.getCode());
            setName(value.getName());
            setRoleSummary(value.getRoleSummary());
            setSemaphore(value.getSemaphore());
            setTaskStatus(value.getTaskStatus());
            setOnChainPermission(value.getOnChainPermission());
            setPermissionBits(value.getPermissionBits());
            setWalletPubkey(value.getWalletPubkey());
            resetChangedOnNotNull();
        }
    }
}
