/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain;


import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.GovernanceApproval;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.GovernanceProposal;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in eh8s_onchain.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GOVERNANCE_APPROVAL_IDX_GOVERNANCE_APPROVAL_TX = Internal.createIndex(DSL.name("idx_governance_approval_tx"), GovernanceApproval.GOVERNANCE_APPROVAL, new OrderField[] { GovernanceApproval.GOVERNANCE_APPROVAL.TX_SIGNATURE }, false);
    public static final Index GOVERNANCE_PROPOSAL_IDX_GOVERNANCE_PROPOSAL_STATUS = Internal.createIndex(DSL.name("idx_governance_proposal_status"), GovernanceProposal.GOVERNANCE_PROPOSAL, new OrderField[] { GovernanceProposal.GOVERNANCE_PROPOSAL.STATUS }, false);
}
