/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain;


import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.ChainConfig;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.DevnetPayMarker;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.Governance;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.GovernanceApproval;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.GovernanceProposal;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.GovernanceSigner;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.TreasuryWithdrawal;


/**
 * Convenience access to all tables in eh8s_onchain.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>eh8s_onchain.chain_config</code>.
     */
    public static final ChainConfig CHAIN_CONFIG = ChainConfig.CHAIN_CONFIG;

    /**
     * The table <code>eh8s_onchain.devnet_pay_marker</code>.
     */
    public static final DevnetPayMarker DEVNET_PAY_MARKER = DevnetPayMarker.DEVNET_PAY_MARKER;

    /**
     * The table <code>eh8s_onchain.governance</code>.
     */
    public static final Governance GOVERNANCE = Governance.GOVERNANCE;

    /**
     * The table <code>eh8s_onchain.governance_approval</code>.
     */
    public static final GovernanceApproval GOVERNANCE_APPROVAL = GovernanceApproval.GOVERNANCE_APPROVAL;

    /**
     * The table <code>eh8s_onchain.governance_proposal</code>.
     */
    public static final GovernanceProposal GOVERNANCE_PROPOSAL = GovernanceProposal.GOVERNANCE_PROPOSAL;

    /**
     * The table <code>eh8s_onchain.governance_signer</code>.
     */
    public static final GovernanceSigner GOVERNANCE_SIGNER = GovernanceSigner.GOVERNANCE_SIGNER;

    /**
     * The table <code>eh8s_onchain.treasury_withdrawal</code>.
     */
    public static final TreasuryWithdrawal TREASURY_WITHDRAWAL = TreasuryWithdrawal.TREASURY_WITHDRAWAL;
}
