/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s.tables.Account;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s.account.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s.account.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s.account.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s.account.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>eh8s.account.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s.account.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s.account.role</code>.
     */
    public void setRole(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s.account.role</code>.
     */
    public String getRole() {
        return (String) get(3);
    }

    /**
     * Setter for <code>eh8s.account.country_code</code>.
     */
    public void setCountryCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s.account.country_code</code>.
     */
    public String getCountryCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>eh8s.account.wallet_pubkey</code>.
     */
    public void setWalletPubkey(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s.account.wallet_pubkey</code>.
     */
    public String getWalletPubkey() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eh8s.account.last_seen_at</code>.
     */
    public void setLastSeenAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s.account.last_seen_at</code>.
     */
    public LocalDateTime getLastSeenAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>eh8s.account.last_lat</code>.
     */
    public void setLastLat(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s.account.last_lat</code>.
     */
    public BigDecimal getLastLat() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>eh8s.account.last_lng</code>.
     */
    public void setLastLng(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>eh8s.account.last_lng</code>.
     */
    public BigDecimal getLastLng() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>eh8s.account.last_geo_at</code>.
     */
    public void setLastGeoAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>eh8s.account.last_geo_at</code>.
     */
    public LocalDateTime getLastGeoAt() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>eh8s.account.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>eh8s.account.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(10);
    }

    /**
     * Setter for <code>eh8s.account.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>eh8s.account.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(Long id, String email, String displayName, String role, String countryCode, String walletPubkey, LocalDateTime lastSeenAt, BigDecimal lastLat, BigDecimal lastLng, LocalDateTime lastGeoAt, String passwordHash, LocalDateTime createdAt) {
        super(Account.ACCOUNT);

        setId(id);
        setEmail(email);
        setDisplayName(displayName);
        setRole(role);
        setCountryCode(countryCode);
        setWalletPubkey(walletPubkey);
        setLastSeenAt(lastSeenAt);
        setLastLat(lastLat);
        setLastLng(lastLng);
        setLastGeoAt(lastGeoAt);
        setPasswordHash(passwordHash);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(com.eh8s.eh8s.database.jooq.eh8s.tables.pojos.Account value) {
        super(Account.ACCOUNT);

        if (value != null) {
            setId(value.getId());
            setEmail(value.getEmail());
            setDisplayName(value.getDisplayName());
            setRole(value.getRole());
            setCountryCode(value.getCountryCode());
            setWalletPubkey(value.getWalletPubkey());
            setLastSeenAt(value.getLastSeenAt());
            setLastLat(value.getLastLat());
            setLastLng(value.getLastLng());
            setLastGeoAt(value.getLastGeoAt());
            setPasswordHash(value.getPasswordHash());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
