/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s.tables.Booking;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookingRecord extends UpdatableRecordImpl<BookingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s.booking.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s.booking.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s.booking.venue_id</code>.
     */
    public void setVenueId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s.booking.venue_id</code>.
     */
    public Long getVenueId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s.booking.band_id</code>.
     */
    public void setBandId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s.booking.band_id</code>.
     */
    public Long getBandId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>eh8s.booking.show_date</code>.
     */
    public void setShowDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s.booking.show_date</code>.
     */
    public LocalDate getShowDate() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>eh8s.booking.pipeline_week</code>.
     */
    public void setPipelineWeek(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s.booking.pipeline_week</code>.
     */
    public Byte getPipelineWeek() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>eh8s.booking.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s.booking.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eh8s.booking.venue_access_token_pda</code>.
     */
    public void setVenueAccessTokenPda(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s.booking.venue_access_token_pda</code>.
     */
    public String getVenueAccessTokenPda() {
        return (String) get(6);
    }

    /**
     * Setter for <code>eh8s.booking.contract_hash</code>.
     */
    public void setContractHash(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s.booking.contract_hash</code>.
     */
    public String getContractHash() {
        return (String) get(7);
    }

    /**
     * Setter for <code>eh8s.booking.onchain_concert_id</code>.
     */
    public void setOnchainConcertId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>eh8s.booking.onchain_concert_id</code>.
     */
    public Long getOnchainConcertId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>eh8s.booking.gross_usdc</code>.
     */
    public void setGrossUsdc(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>eh8s.booking.gross_usdc</code>.
     */
    public BigDecimal getGrossUsdc() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>eh8s.booking.escrow_pda</code>.
     */
    public void setEscrowPda(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>eh8s.booking.escrow_pda</code>.
     */
    public String getEscrowPda() {
        return (String) get(10);
    }

    /**
     * Setter for <code>eh8s.booking.contract_text</code>.
     */
    public void setContractText(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>eh8s.booking.contract_text</code>.
     */
    public String getContractText() {
        return (String) get(11);
    }

    /**
     * Setter for <code>eh8s.booking.onchain_status</code>.
     */
    public void setOnchainStatus(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>eh8s.booking.onchain_status</code>.
     */
    public String getOnchainStatus() {
        return (String) get(12);
    }

    /**
     * Setter for <code>eh8s.booking.propose_tx_signature</code>.
     */
    public void setProposeTxSignature(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>eh8s.booking.propose_tx_signature</code>.
     */
    public String getProposeTxSignature() {
        return (String) get(13);
    }

    /**
     * Setter for <code>eh8s.booking.confirm_tx_signature</code>.
     */
    public void setConfirmTxSignature(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>eh8s.booking.confirm_tx_signature</code>.
     */
    public String getConfirmTxSignature() {
        return (String) get(14);
    }

    /**
     * Setter for <code>eh8s.booking.cancel_tx_signature</code>.
     */
    public void setCancelTxSignature(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>eh8s.booking.cancel_tx_signature</code>.
     */
    public String getCancelTxSignature() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookingRecord
     */
    public BookingRecord() {
        super(Booking.BOOKING);
    }

    /**
     * Create a detached, initialised BookingRecord
     */
    public BookingRecord(Long id, Long venueId, Long bandId, LocalDate showDate, Byte pipelineWeek, String status, String venueAccessTokenPda, String contractHash, Long onchainConcertId, BigDecimal grossUsdc, String escrowPda, String contractText, String onchainStatus, String proposeTxSignature, String confirmTxSignature, String cancelTxSignature) {
        super(Booking.BOOKING);

        setId(id);
        setVenueId(venueId);
        setBandId(bandId);
        setShowDate(showDate);
        setPipelineWeek(pipelineWeek);
        setStatus(status);
        setVenueAccessTokenPda(venueAccessTokenPda);
        setContractHash(contractHash);
        setOnchainConcertId(onchainConcertId);
        setGrossUsdc(grossUsdc);
        setEscrowPda(escrowPda);
        setContractText(contractText);
        setOnchainStatus(onchainStatus);
        setProposeTxSignature(proposeTxSignature);
        setConfirmTxSignature(confirmTxSignature);
        setCancelTxSignature(cancelTxSignature);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised BookingRecord
     */
    public BookingRecord(com.eh8s.eh8s.database.jooq.eh8s.tables.pojos.Booking value) {
        super(Booking.BOOKING);

        if (value != null) {
            setId(value.getId());
            setVenueId(value.getVenueId());
            setBandId(value.getBandId());
            setShowDate(value.getShowDate());
            setPipelineWeek(value.getPipelineWeek());
            setStatus(value.getStatus());
            setVenueAccessTokenPda(value.getVenueAccessTokenPda());
            setContractHash(value.getContractHash());
            setOnchainConcertId(value.getOnchainConcertId());
            setGrossUsdc(value.getGrossUsdc());
            setEscrowPda(value.getEscrowPda());
            setContractText(value.getContractText());
            setOnchainStatus(value.getOnchainStatus());
            setProposeTxSignature(value.getProposeTxSignature());
            setConfirmTxSignature(value.getConfirmTxSignature());
            setCancelTxSignature(value.getCancelTxSignature());
            resetChangedOnNotNull();
        }
    }
}
