/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s.tables.EnigmaLevel;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnigmaLevelRecord extends UpdatableRecordImpl<EnigmaLevelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s.enigma_level.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s.enigma_level.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s.enigma_level.level_number</code>.
     */
    public void setLevelNumber(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s.enigma_level.level_number</code>.
     */
    public Byte getLevelNumber() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>eh8s.enigma_level.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s.enigma_level.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s.enigma_level.duration_note</code>.
     */
    public void setDurationNote(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s.enigma_level.duration_note</code>.
     */
    public String getDurationNote() {
        return (String) get(3);
    }

    /**
     * Setter for <code>eh8s.enigma_level.milestone</code>.
     */
    public void setMilestone(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s.enigma_level.milestone</code>.
     */
    public String getMilestone() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EnigmaLevelRecord
     */
    public EnigmaLevelRecord() {
        super(EnigmaLevel.ENIGMA_LEVEL);
    }

    /**
     * Create a detached, initialised EnigmaLevelRecord
     */
    public EnigmaLevelRecord(Long id, Byte levelNumber, String name, String durationNote, String milestone) {
        super(EnigmaLevel.ENIGMA_LEVEL);

        setId(id);
        setLevelNumber(levelNumber);
        setName(name);
        setDurationNote(durationNote);
        setMilestone(milestone);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised EnigmaLevelRecord
     */
    public EnigmaLevelRecord(com.eh8s.eh8s.database.jooq.eh8s.tables.pojos.EnigmaLevel value) {
        super(EnigmaLevel.ENIGMA_LEVEL);

        if (value != null) {
            setId(value.getId());
            setLevelNumber(value.getLevelNumber());
            setName(value.getName());
            setDurationNote(value.getDurationNote());
            setMilestone(value.getMilestone());
            resetChangedOnNotNull();
        }
    }
}
