/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s.tables.MusicianLevelChange;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MusicianLevelChangeRecord extends UpdatableRecordImpl<MusicianLevelChangeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s.musician_level_change.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s.musician_level_change.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s.musician_level_change.musician_profile_id</code>.
     */
    public void setMusicianProfileId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s.musician_level_change.musician_profile_id</code>.
     */
    public Long getMusicianProfileId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s.musician_level_change.agent_wallet_pubkey</code>.
     */
    public void setAgentWalletPubkey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s.musician_level_change.agent_wallet_pubkey</code>.
     */
    public String getAgentWalletPubkey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s.musician_level_change.old_level</code>.
     */
    public void setOldLevel(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s.musician_level_change.old_level</code>.
     */
    public Byte getOldLevel() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>eh8s.musician_level_change.new_level</code>.
     */
    public void setNewLevel(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s.musician_level_change.new_level</code>.
     */
    public Byte getNewLevel() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>eh8s.musician_level_change.tx_signature</code>.
     */
    public void setTxSignature(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s.musician_level_change.tx_signature</code>.
     */
    public String getTxSignature() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eh8s.musician_level_change.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s.musician_level_change.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MusicianLevelChangeRecord
     */
    public MusicianLevelChangeRecord() {
        super(MusicianLevelChange.MUSICIAN_LEVEL_CHANGE);
    }

    /**
     * Create a detached, initialised MusicianLevelChangeRecord
     */
    public MusicianLevelChangeRecord(Long id, Long musicianProfileId, String agentWalletPubkey, Byte oldLevel, Byte newLevel, String txSignature, LocalDateTime createdAt) {
        super(MusicianLevelChange.MUSICIAN_LEVEL_CHANGE);

        setId(id);
        setMusicianProfileId(musicianProfileId);
        setAgentWalletPubkey(agentWalletPubkey);
        setOldLevel(oldLevel);
        setNewLevel(newLevel);
        setTxSignature(txSignature);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised MusicianLevelChangeRecord
     */
    public MusicianLevelChangeRecord(com.eh8s.eh8s.database.jooq.eh8s.tables.pojos.MusicianLevelChange value) {
        super(MusicianLevelChange.MUSICIAN_LEVEL_CHANGE);

        if (value != null) {
            setId(value.getId());
            setMusicianProfileId(value.getMusicianProfileId());
            setAgentWalletPubkey(value.getAgentWalletPubkey());
            setOldLevel(value.getOldLevel());
            setNewLevel(value.getNewLevel());
            setTxSignature(value.getTxSignature());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
