/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain.tables;


import com.eh8s.eh8s.database.jooq.eh8s_onchain.Eh8sOnchain;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.Governance.GovernancePath;
import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.records.GovernanceSignerRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GovernanceSigner extends TableImpl<GovernanceSignerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_onchain.governance_signer</code>
     */
    public static final GovernanceSigner GOVERNANCE_SIGNER = new GovernanceSigner();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GovernanceSignerRecord> getRecordType() {
        return GovernanceSignerRecord.class;
    }

    /**
     * The column <code>eh8s_onchain.governance_signer.id</code>.
     */
    public final TableField<GovernanceSignerRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s_onchain.governance_signer.governance_id</code>.
     */
    public final TableField<GovernanceSignerRecord, Long> GOVERNANCE_ID = createField(DSL.name("governance_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_onchain.governance_signer.wallet_pubkey</code>.
     */
    public final TableField<GovernanceSignerRecord, String> WALLET_PUBKEY = createField(DSL.name("wallet_pubkey"), SQLDataType.VARCHAR(44).nullable(false), this, "");

    /**
     * The column <code>eh8s_onchain.governance_signer.position</code>.
     */
    public final TableField<GovernanceSignerRecord, Byte> POSITION = createField(DSL.name("position"), SQLDataType.TINYINT.nullable(false), this, "");

    private GovernanceSigner(Name alias, Table<GovernanceSignerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GovernanceSigner(Name alias, Table<GovernanceSignerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_onchain.governance_signer</code> table
     * reference
     */
    public GovernanceSigner(String alias) {
        this(DSL.name(alias), GOVERNANCE_SIGNER);
    }

    /**
     * Create an aliased <code>eh8s_onchain.governance_signer</code> table
     * reference
     */
    public GovernanceSigner(Name alias) {
        this(alias, GOVERNANCE_SIGNER);
    }

    /**
     * Create a <code>eh8s_onchain.governance_signer</code> table reference
     */
    public GovernanceSigner() {
        this(DSL.name("governance_signer"), null);
    }

    public <O extends Record> GovernanceSigner(Table<O> path, ForeignKey<O, GovernanceSignerRecord> childPath, InverseForeignKey<O, GovernanceSignerRecord> parentPath) {
        super(path, childPath, parentPath, GOVERNANCE_SIGNER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GovernanceSignerPath extends GovernanceSigner implements Path<GovernanceSignerRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> GovernanceSignerPath(Table<O> path, ForeignKey<O, GovernanceSignerRecord> childPath, InverseForeignKey<O, GovernanceSignerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private GovernanceSignerPath(Name alias, Table<GovernanceSignerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GovernanceSignerPath as(String alias) {
            return new GovernanceSignerPath(DSL.name(alias), this);
        }

        @Override
        public GovernanceSignerPath as(Name alias) {
            return new GovernanceSignerPath(alias, this);
        }

        @Override
        public GovernanceSignerPath as(Table<?> alias) {
            return new GovernanceSignerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sOnchain.EH8S_ONCHAIN;
    }

    @Override
    public Identity<GovernanceSignerRecord, Long> getIdentity() {
        return (Identity<GovernanceSignerRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<GovernanceSignerRecord> getPrimaryKey() {
        return Keys.KEY_GOVERNANCE_SIGNER_PRIMARY;
    }

    @Override
    public List<UniqueKey<GovernanceSignerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_GOVERNANCE_SIGNER_UK_GOVERNANCE_SIGNER);
    }

    @Override
    public List<ForeignKey<GovernanceSignerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_GOVERNANCE_SIGNER_GOVERNANCE);
    }

    private transient GovernancePath _governance;

    /**
     * Get the implicit join path to the <code>eh8s_onchain.governance</code>
     * table.
     */
    public GovernancePath governance() {
        if (_governance == null)
            _governance = new GovernancePath(this, Keys.FK_GOVERNANCE_SIGNER_GOVERNANCE, null);

        return _governance;
    }

    @Override
    public GovernanceSigner as(String alias) {
        return new GovernanceSigner(DSL.name(alias), this);
    }

    @Override
    public GovernanceSigner as(Name alias) {
        return new GovernanceSigner(alias, this);
    }

    @Override
    public GovernanceSigner as(Table<?> alias) {
        return new GovernanceSigner(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public GovernanceSigner rename(String name) {
        return new GovernanceSigner(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GovernanceSigner rename(Name name) {
        return new GovernanceSigner(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public GovernanceSigner rename(Table<?> name) {
        return new GovernanceSigner(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GovernanceSigner where(Condition condition) {
        return new GovernanceSigner(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GovernanceSigner where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GovernanceSigner where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GovernanceSigner where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GovernanceSigner where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GovernanceSigner where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GovernanceSigner where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public GovernanceSigner where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GovernanceSigner whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public GovernanceSigner whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
