/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GeographicSubscription implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long bandId;
    private Long geoTierId;
    private Long geoRegionId;
    private LocalDate startsAt;
    private LocalDate expiresAt;
    private Byte months;
    private String geoCode;
    private String geographicSubscriptionPda;
    private String intendedInstruction;
    private String payTxSignature;
    private LocalDateTime paidAt;
    private String payerWalletPubkey;
    private String onChainStatus;
    private LocalDateTime onchainExpiresAt;

    public GeographicSubscription() {}

    public GeographicSubscription(GeographicSubscription value) {
        this.id = value.id;
        this.bandId = value.bandId;
        this.geoTierId = value.geoTierId;
        this.geoRegionId = value.geoRegionId;
        this.startsAt = value.startsAt;
        this.expiresAt = value.expiresAt;
        this.months = value.months;
        this.geoCode = value.geoCode;
        this.geographicSubscriptionPda = value.geographicSubscriptionPda;
        this.intendedInstruction = value.intendedInstruction;
        this.payTxSignature = value.payTxSignature;
        this.paidAt = value.paidAt;
        this.payerWalletPubkey = value.payerWalletPubkey;
        this.onChainStatus = value.onChainStatus;
        this.onchainExpiresAt = value.onchainExpiresAt;
    }

    public GeographicSubscription(
        Long id,
        Long bandId,
        Long geoTierId,
        Long geoRegionId,
        LocalDate startsAt,
        LocalDate expiresAt,
        Byte months,
        String geoCode,
        String geographicSubscriptionPda,
        String intendedInstruction,
        String payTxSignature,
        LocalDateTime paidAt,
        String payerWalletPubkey,
        String onChainStatus,
        LocalDateTime onchainExpiresAt
    ) {
        this.id = id;
        this.bandId = bandId;
        this.geoTierId = geoTierId;
        this.geoRegionId = geoRegionId;
        this.startsAt = startsAt;
        this.expiresAt = expiresAt;
        this.months = months;
        this.geoCode = geoCode;
        this.geographicSubscriptionPda = geographicSubscriptionPda;
        this.intendedInstruction = intendedInstruction;
        this.payTxSignature = payTxSignature;
        this.paidAt = paidAt;
        this.payerWalletPubkey = payerWalletPubkey;
        this.onChainStatus = onChainStatus;
        this.onchainExpiresAt = onchainExpiresAt;
    }

    /**
     * Getter for <code>eh8s_catalog.geographic_subscription.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s_catalog.geographic_subscription.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s_catalog.geographic_subscription.band_id</code>.
     */
    public Long getBandId() {
        return this.bandId;
    }

    /**
     * Setter for <code>eh8s_catalog.geographic_subscription.band_id</code>.
     */
    public void setBandId(Long bandId) {
        this.bandId = bandId;
    }

    /**
     * Getter for <code>eh8s_catalog.geographic_subscription.geo_tier_id</code>.
     */
    public Long getGeoTierId() {
        return this.geoTierId;
    }

    /**
     * Setter for <code>eh8s_catalog.geographic_subscription.geo_tier_id</code>.
     */
    public void setGeoTierId(Long geoTierId) {
        this.geoTierId = geoTierId;
    }

    /**
     * Getter for
     * <code>eh8s_catalog.geographic_subscription.geo_region_id</code>.
     */
    public Long getGeoRegionId() {
        return this.geoRegionId;
    }

    /**
     * Setter for
     * <code>eh8s_catalog.geographic_subscription.geo_region_id</code>.
     */
    public void setGeoRegionId(Long geoRegionId) {
        this.geoRegionId = geoRegionId;
    }

    /**
     * Getter for <code>eh8s_catalog.geographic_subscription.starts_at</code>.
     */
    public LocalDate getStartsAt() {
        return this.startsAt;
    }

    /**
     * Setter for <code>eh8s_catalog.geographic_subscription.starts_at</code>.
     */
    public void setStartsAt(LocalDate startsAt) {
        this.startsAt = startsAt;
    }

    /**
     * Getter for <code>eh8s_catalog.geographic_subscription.expires_at</code>.
     */
    public LocalDate getExpiresAt() {
        return this.expiresAt;
    }

    /**
     * Setter for <code>eh8s_catalog.geographic_subscription.expires_at</code>.
     */
    public void setExpiresAt(LocalDate expiresAt) {
        this.expiresAt = expiresAt;
    }

    /**
     * Getter for <code>eh8s_catalog.geographic_subscription.months</code>.
     */
    public Byte getMonths() {
        return this.months;
    }

    /**
     * Setter for <code>eh8s_catalog.geographic_subscription.months</code>.
     */
    public void setMonths(Byte months) {
        this.months = months;
    }

    /**
     * Getter for <code>eh8s_catalog.geographic_subscription.geo_code</code>.
     */
    public String getGeoCode() {
        return this.geoCode;
    }

    /**
     * Setter for <code>eh8s_catalog.geographic_subscription.geo_code</code>.
     */
    public void setGeoCode(String geoCode) {
        this.geoCode = geoCode;
    }

    /**
     * Getter for
     * <code>eh8s_catalog.geographic_subscription.geographic_subscription_pda</code>.
     */
    public String getGeographicSubscriptionPda() {
        return this.geographicSubscriptionPda;
    }

    /**
     * Setter for
     * <code>eh8s_catalog.geographic_subscription.geographic_subscription_pda</code>.
     */
    public void setGeographicSubscriptionPda(String geographicSubscriptionPda) {
        this.geographicSubscriptionPda = geographicSubscriptionPda;
    }

    /**
     * Getter for
     * <code>eh8s_catalog.geographic_subscription.intended_instruction</code>.
     */
    public String getIntendedInstruction() {
        return this.intendedInstruction;
    }

    /**
     * Setter for
     * <code>eh8s_catalog.geographic_subscription.intended_instruction</code>.
     */
    public void setIntendedInstruction(String intendedInstruction) {
        this.intendedInstruction = intendedInstruction;
    }

    /**
     * Getter for
     * <code>eh8s_catalog.geographic_subscription.pay_tx_signature</code>.
     */
    public String getPayTxSignature() {
        return this.payTxSignature;
    }

    /**
     * Setter for
     * <code>eh8s_catalog.geographic_subscription.pay_tx_signature</code>.
     */
    public void setPayTxSignature(String payTxSignature) {
        this.payTxSignature = payTxSignature;
    }

    /**
     * Getter for <code>eh8s_catalog.geographic_subscription.paid_at</code>.
     */
    public LocalDateTime getPaidAt() {
        return this.paidAt;
    }

    /**
     * Setter for <code>eh8s_catalog.geographic_subscription.paid_at</code>.
     */
    public void setPaidAt(LocalDateTime paidAt) {
        this.paidAt = paidAt;
    }

    /**
     * Getter for
     * <code>eh8s_catalog.geographic_subscription.payer_wallet_pubkey</code>.
     */
    public String getPayerWalletPubkey() {
        return this.payerWalletPubkey;
    }

    /**
     * Setter for
     * <code>eh8s_catalog.geographic_subscription.payer_wallet_pubkey</code>.
     */
    public void setPayerWalletPubkey(String payerWalletPubkey) {
        this.payerWalletPubkey = payerWalletPubkey;
    }

    /**
     * Getter for
     * <code>eh8s_catalog.geographic_subscription.on_chain_status</code>.
     */
    public String getOnChainStatus() {
        return this.onChainStatus;
    }

    /**
     * Setter for
     * <code>eh8s_catalog.geographic_subscription.on_chain_status</code>.
     */
    public void setOnChainStatus(String onChainStatus) {
        this.onChainStatus = onChainStatus;
    }

    /**
     * Getter for
     * <code>eh8s_catalog.geographic_subscription.onchain_expires_at</code>.
     */
    public LocalDateTime getOnchainExpiresAt() {
        return this.onchainExpiresAt;
    }

    /**
     * Setter for
     * <code>eh8s_catalog.geographic_subscription.onchain_expires_at</code>.
     */
    public void setOnchainExpiresAt(LocalDateTime onchainExpiresAt) {
        this.onchainExpiresAt = onchainExpiresAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GeographicSubscription other = (GeographicSubscription) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.bandId == null) {
            if (other.bandId != null)
                return false;
        }
        else if (!this.bandId.equals(other.bandId))
            return false;
        if (this.geoTierId == null) {
            if (other.geoTierId != null)
                return false;
        }
        else if (!this.geoTierId.equals(other.geoTierId))
            return false;
        if (this.geoRegionId == null) {
            if (other.geoRegionId != null)
                return false;
        }
        else if (!this.geoRegionId.equals(other.geoRegionId))
            return false;
        if (this.startsAt == null) {
            if (other.startsAt != null)
                return false;
        }
        else if (!this.startsAt.equals(other.startsAt))
            return false;
        if (this.expiresAt == null) {
            if (other.expiresAt != null)
                return false;
        }
        else if (!this.expiresAt.equals(other.expiresAt))
            return false;
        if (this.months == null) {
            if (other.months != null)
                return false;
        }
        else if (!this.months.equals(other.months))
            return false;
        if (this.geoCode == null) {
            if (other.geoCode != null)
                return false;
        }
        else if (!this.geoCode.equals(other.geoCode))
            return false;
        if (this.geographicSubscriptionPda == null) {
            if (other.geographicSubscriptionPda != null)
                return false;
        }
        else if (!this.geographicSubscriptionPda.equals(other.geographicSubscriptionPda))
            return false;
        if (this.intendedInstruction == null) {
            if (other.intendedInstruction != null)
                return false;
        }
        else if (!this.intendedInstruction.equals(other.intendedInstruction))
            return false;
        if (this.payTxSignature == null) {
            if (other.payTxSignature != null)
                return false;
        }
        else if (!this.payTxSignature.equals(other.payTxSignature))
            return false;
        if (this.paidAt == null) {
            if (other.paidAt != null)
                return false;
        }
        else if (!this.paidAt.equals(other.paidAt))
            return false;
        if (this.payerWalletPubkey == null) {
            if (other.payerWalletPubkey != null)
                return false;
        }
        else if (!this.payerWalletPubkey.equals(other.payerWalletPubkey))
            return false;
        if (this.onChainStatus == null) {
            if (other.onChainStatus != null)
                return false;
        }
        else if (!this.onChainStatus.equals(other.onChainStatus))
            return false;
        if (this.onchainExpiresAt == null) {
            if (other.onchainExpiresAt != null)
                return false;
        }
        else if (!this.onchainExpiresAt.equals(other.onchainExpiresAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.bandId == null) ? 0 : this.bandId.hashCode());
        result = prime * result + ((this.geoTierId == null) ? 0 : this.geoTierId.hashCode());
        result = prime * result + ((this.geoRegionId == null) ? 0 : this.geoRegionId.hashCode());
        result = prime * result + ((this.startsAt == null) ? 0 : this.startsAt.hashCode());
        result = prime * result + ((this.expiresAt == null) ? 0 : this.expiresAt.hashCode());
        result = prime * result + ((this.months == null) ? 0 : this.months.hashCode());
        result = prime * result + ((this.geoCode == null) ? 0 : this.geoCode.hashCode());
        result = prime * result + ((this.geographicSubscriptionPda == null) ? 0 : this.geographicSubscriptionPda.hashCode());
        result = prime * result + ((this.intendedInstruction == null) ? 0 : this.intendedInstruction.hashCode());
        result = prime * result + ((this.payTxSignature == null) ? 0 : this.payTxSignature.hashCode());
        result = prime * result + ((this.paidAt == null) ? 0 : this.paidAt.hashCode());
        result = prime * result + ((this.payerWalletPubkey == null) ? 0 : this.payerWalletPubkey.hashCode());
        result = prime * result + ((this.onChainStatus == null) ? 0 : this.onChainStatus.hashCode());
        result = prime * result + ((this.onchainExpiresAt == null) ? 0 : this.onchainExpiresAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GeographicSubscription (");

        sb.append(id);
        sb.append(", ").append(bandId);
        sb.append(", ").append(geoTierId);
        sb.append(", ").append(geoRegionId);
        sb.append(", ").append(startsAt);
        sb.append(", ").append(expiresAt);
        sb.append(", ").append(months);
        sb.append(", ").append(geoCode);
        sb.append(", ").append(geographicSubscriptionPda);
        sb.append(", ").append(intendedInstruction);
        sb.append(", ").append(payTxSignature);
        sb.append(", ").append(paidAt);
        sb.append(", ").append(payerWalletPubkey);
        sb.append(", ").append(onChainStatus);
        sb.append(", ").append(onchainExpiresAt);

        sb.append(")");
        return sb.toString();
    }
}
