/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GeoRegion implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String code;
    private String name;
    private String onchainGeoCode;
    private String countryCode;
    private String city;

    public GeoRegion() {}

    public GeoRegion(GeoRegion value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
        this.onchainGeoCode = value.onchainGeoCode;
        this.countryCode = value.countryCode;
        this.city = value.city;
    }

    public GeoRegion(
        Long id,
        String code,
        String name,
        String onchainGeoCode,
        String countryCode,
        String city
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.onchainGeoCode = onchainGeoCode;
        this.countryCode = countryCode;
        this.city = city;
    }

    /**
     * Getter for <code>eh8s_catalog.geo_region.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>eh8s_catalog.geo_region.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>eh8s_catalog.geo_region.code</code>.
     */
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for <code>eh8s_catalog.geo_region.code</code>.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for <code>eh8s_catalog.geo_region.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>eh8s_catalog.geo_region.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>eh8s_catalog.geo_region.onchain_geo_code</code>.
     */
    public String getOnchainGeoCode() {
        return this.onchainGeoCode;
    }

    /**
     * Setter for <code>eh8s_catalog.geo_region.onchain_geo_code</code>.
     */
    public void setOnchainGeoCode(String onchainGeoCode) {
        this.onchainGeoCode = onchainGeoCode;
    }

    /**
     * Getter for <code>eh8s_catalog.geo_region.country_code</code>.
     */
    public String getCountryCode() {
        return this.countryCode;
    }

    /**
     * Setter for <code>eh8s_catalog.geo_region.country_code</code>.
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    /**
     * Getter for <code>eh8s_catalog.geo_region.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>eh8s_catalog.geo_region.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final GeoRegion other = (GeoRegion) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.code == null) {
            if (other.code != null)
                return false;
        }
        else if (!this.code.equals(other.code))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.onchainGeoCode == null) {
            if (other.onchainGeoCode != null)
                return false;
        }
        else if (!this.onchainGeoCode.equals(other.onchainGeoCode))
            return false;
        if (this.countryCode == null) {
            if (other.countryCode != null)
                return false;
        }
        else if (!this.countryCode.equals(other.countryCode))
            return false;
        if (this.city == null) {
            if (other.city != null)
                return false;
        }
        else if (!this.city.equals(other.city))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.code == null) ? 0 : this.code.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.onchainGeoCode == null) ? 0 : this.onchainGeoCode.hashCode());
        result = prime * result + ((this.countryCode == null) ? 0 : this.countryCode.hashCode());
        result = prime * result + ((this.city == null) ? 0 : this.city.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GeoRegion (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);
        sb.append(", ").append(onchainGeoCode);
        sb.append(", ").append(countryCode);
        sb.append(", ").append(city);

        sb.append(")");
        return sb.toString();
    }
}
