/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_academy;


import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.AcademySubscription;
import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.Course;
import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.CourseSection;
import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.Lesson;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in eh8s_academy.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACADEMY_SUBSCRIPTION_IDX_ACADEMY_SUBSCRIPTION_PDA = Internal.createIndex(DSL.name("idx_academy_subscription_pda"), AcademySubscription.ACADEMY_SUBSCRIPTION, new OrderField[] { AcademySubscription.ACADEMY_SUBSCRIPTION.ACADEMY_SUBSCRIPTION_PDA }, false);
    public static final Index COURSE_IDX_COURSE_REVIEW = Internal.createIndex(DSL.name("idx_course_review"), Course.COURSE, new OrderField[] { Course.COURSE.REVIEW_STATUS, Course.COURSE.SUBMITTED_AT }, false);
    public static final Index COURSE_SECTION_IDX_COURSE_SECTION_ORDER = Internal.createIndex(DSL.name("idx_course_section_order"), CourseSection.COURSE_SECTION, new OrderField[] { CourseSection.COURSE_SECTION.COURSE_ID, CourseSection.COURSE_SECTION.SORT_ORDER }, false);
    public static final Index COURSE_IDX_COURSE_STATUS_SORT = Internal.createIndex(DSL.name("idx_course_status_sort"), Course.COURSE, new OrderField[] { Course.COURSE.STATUS, Course.COURSE.SORT_ORDER }, false);
    public static final Index LESSON_IDX_LESSON_ORDER = Internal.createIndex(DSL.name("idx_lesson_order"), Lesson.LESSON, new OrderField[] { Lesson.LESSON.SECTION_ID, Lesson.LESSON.SORT_ORDER }, false);
}
