/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.DevnetPayMarker;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DevnetPayMarkerRecord extends UpdatableRecordImpl<DevnetPayMarkerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.kind</code>.
     */
    public void setKind(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.kind</code>.
     */
    public String getKind() {
        return (String) get(1);
    }

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.wallet_pubkey</code>.
     */
    public void setWalletPubkey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.wallet_pubkey</code>.
     */
    public String getWalletPubkey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.amount_usdc</code>.
     */
    public void setAmountUsdc(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.amount_usdc</code>.
     */
    public BigDecimal getAmountUsdc() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.related_claim_id</code>.
     */
    public void setRelatedClaimId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.related_claim_id</code>.
     */
    public Long getRelatedClaimId() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>eh8s_onchain.devnet_pay_marker.related_subscription_id</code>.
     */
    public void setRelatedSubscriptionId(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>eh8s_onchain.devnet_pay_marker.related_subscription_id</code>.
     */
    public Long getRelatedSubscriptionId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.tx_signature</code>.
     */
    public void setTxSignature(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.tx_signature</code>.
     */
    public String getTxSignature() {
        return (String) get(6);
    }

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for
     * <code>eh8s_onchain.devnet_pay_marker.intended_instruction</code>.
     */
    public void setIntendedInstruction(String value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>eh8s_onchain.devnet_pay_marker.intended_instruction</code>.
     */
    public String getIntendedInstruction() {
        return (String) get(8);
    }

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.note</code>.
     */
    public void setNote(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.note</code>.
     */
    public String getNote() {
        return (String) get(9);
    }

    /**
     * Setter for <code>eh8s_onchain.devnet_pay_marker.recorded_at</code>.
     */
    public void setRecordedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>eh8s_onchain.devnet_pay_marker.recorded_at</code>.
     */
    public LocalDateTime getRecordedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DevnetPayMarkerRecord
     */
    public DevnetPayMarkerRecord() {
        super(DevnetPayMarker.DEVNET_PAY_MARKER);
    }

    /**
     * Create a detached, initialised DevnetPayMarkerRecord
     */
    public DevnetPayMarkerRecord(Long id, String kind, String walletPubkey, BigDecimal amountUsdc, Long relatedClaimId, Long relatedSubscriptionId, String txSignature, String status, String intendedInstruction, String note, LocalDateTime recordedAt) {
        super(DevnetPayMarker.DEVNET_PAY_MARKER);

        setId(id);
        setKind(kind);
        setWalletPubkey(walletPubkey);
        setAmountUsdc(amountUsdc);
        setRelatedClaimId(relatedClaimId);
        setRelatedSubscriptionId(relatedSubscriptionId);
        setTxSignature(txSignature);
        setStatus(status);
        setIntendedInstruction(intendedInstruction);
        setNote(note);
        setRecordedAt(recordedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised DevnetPayMarkerRecord
     */
    public DevnetPayMarkerRecord(com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.pojos.DevnetPayMarker value) {
        super(DevnetPayMarker.DEVNET_PAY_MARKER);

        if (value != null) {
            setId(value.getId());
            setKind(value.getKind());
            setWalletPubkey(value.getWalletPubkey());
            setAmountUsdc(value.getAmountUsdc());
            setRelatedClaimId(value.getRelatedClaimId());
            setRelatedSubscriptionId(value.getRelatedSubscriptionId());
            setTxSignature(value.getTxSignature());
            setStatus(value.getStatus());
            setIntendedInstruction(value.getIntendedInstruction());
            setNote(value.getNote());
            setRecordedAt(value.getRecordedAt());
            resetChangedOnNotNull();
        }
    }
}
