/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.Governance;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GovernanceRecord extends UpdatableRecordImpl<GovernanceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_onchain.governance.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_onchain.governance.program_id</code>.
     */
    public void setProgramId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.program_id</code>.
     */
    public String getProgramId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>eh8s_onchain.governance.governance_pda</code>.
     */
    public void setGovernancePda(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.governance_pda</code>.
     */
    public String getGovernancePda() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s_onchain.governance.threshold</code>.
     */
    public void setThreshold(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.threshold</code>.
     */
    public Byte getThreshold() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>eh8s_onchain.governance.epoch</code>.
     */
    public void setEpoch(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.epoch</code>.
     */
    public Integer getEpoch() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>eh8s_onchain.governance.initialized_by_wallet</code>.
     */
    public void setInitializedByWallet(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.initialized_by_wallet</code>.
     */
    public String getInitializedByWallet() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eh8s_onchain.governance.init_tx_signature</code>.
     */
    public void setInitTxSignature(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.init_tx_signature</code>.
     */
    public String getInitTxSignature() {
        return (String) get(6);
    }

    /**
     * Setter for <code>eh8s_onchain.governance.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>eh8s_onchain.governance.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GovernanceRecord
     */
    public GovernanceRecord() {
        super(Governance.GOVERNANCE);
    }

    /**
     * Create a detached, initialised GovernanceRecord
     */
    public GovernanceRecord(Long id, String programId, String governancePda, Byte threshold, Integer epoch, String initializedByWallet, String initTxSignature, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Governance.GOVERNANCE);

        setId(id);
        setProgramId(programId);
        setGovernancePda(governancePda);
        setThreshold(threshold);
        setEpoch(epoch);
        setInitializedByWallet(initializedByWallet);
        setInitTxSignature(initTxSignature);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GovernanceRecord
     */
    public GovernanceRecord(com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.pojos.Governance value) {
        super(Governance.GOVERNANCE);

        if (value != null) {
            setId(value.getId());
            setProgramId(value.getProgramId());
            setGovernancePda(value.getGovernancePda());
            setThreshold(value.getThreshold());
            setEpoch(value.getEpoch());
            setInitializedByWallet(value.getInitializedByWallet());
            setInitTxSignature(value.getInitTxSignature());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
