/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.GovernanceProposal;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GovernanceProposalRecord extends UpdatableRecordImpl<GovernanceProposalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.governance_id</code>.
     */
    public void setGovernanceId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.governance_id</code>.
     */
    public Long getGovernanceId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>eh8s_onchain.governance_proposal.onchain_proposal_id</code>.
     */
    public void setOnchainProposalId(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>eh8s_onchain.governance_proposal.onchain_proposal_id</code>.
     */
    public Long getOnchainProposalId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.proposal_pda</code>.
     */
    public void setProposalPda(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.proposal_pda</code>.
     */
    public String getProposalPda() {
        return (String) get(3);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.epoch</code>.
     */
    public void setEpoch(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.epoch</code>.
     */
    public Integer getEpoch() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.kind</code>.
     */
    public void setKind(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.kind</code>.
     */
    public String getKind() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.proposer_wallet</code>.
     */
    public void setProposerWallet(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.proposer_wallet</code>.
     */
    public String getProposerWallet() {
        return (String) get(6);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.amount_usdc</code>.
     */
    public void setAmountUsdc(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.amount_usdc</code>.
     */
    public BigDecimal getAmountUsdc() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.target_pubkey</code>.
     */
    public void setTargetPubkey(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.target_pubkey</code>.
     */
    public String getTargetPubkey() {
        return (String) get(8);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.permissions</code>.
     */
    public void setPermissions(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.permissions</code>.
     */
    public Byte getPermissions() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.agent_code</code>.
     */
    public void setAgentCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.agent_code</code>.
     */
    public String getAgentCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.new_signers_csv</code>.
     */
    public void setNewSignersCsv(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.new_signers_csv</code>.
     */
    public String getNewSignersCsv() {
        return (String) get(11);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.new_threshold</code>.
     */
    public void setNewThreshold(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.new_threshold</code>.
     */
    public Byte getNewThreshold() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.status</code>.
     */
    public void setStatus(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.status</code>.
     */
    public String getStatus() {
        return (String) get(13);
    }

    /**
     * Setter for
     * <code>eh8s_onchain.governance_proposal.propose_tx_signature</code>.
     */
    public void setProposeTxSignature(String value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>eh8s_onchain.governance_proposal.propose_tx_signature</code>.
     */
    public String getProposeTxSignature() {
        return (String) get(14);
    }

    /**
     * Setter for
     * <code>eh8s_onchain.governance_proposal.execute_tx_signature</code>.
     */
    public void setExecuteTxSignature(String value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>eh8s_onchain.governance_proposal.execute_tx_signature</code>.
     */
    public String getExecuteTxSignature() {
        return (String) get(15);
    }

    /**
     * Setter for
     * <code>eh8s_onchain.governance_proposal.executed_by_wallet</code>.
     */
    public void setExecutedByWallet(String value) {
        set(16, value);
    }

    /**
     * Getter for
     * <code>eh8s_onchain.governance_proposal.executed_by_wallet</code>.
     */
    public String getExecutedByWallet() {
        return (String) get(16);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>eh8s_onchain.governance_proposal.executed_at</code>.
     */
    public void setExecutedAt(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>eh8s_onchain.governance_proposal.executed_at</code>.
     */
    public LocalDateTime getExecutedAt() {
        return (LocalDateTime) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GovernanceProposalRecord
     */
    public GovernanceProposalRecord() {
        super(GovernanceProposal.GOVERNANCE_PROPOSAL);
    }

    /**
     * Create a detached, initialised GovernanceProposalRecord
     */
    public GovernanceProposalRecord(Long id, Long governanceId, Long onchainProposalId, String proposalPda, Integer epoch, String kind, String proposerWallet, BigDecimal amountUsdc, String targetPubkey, Byte permissions, String agentCode, String newSignersCsv, Byte newThreshold, String status, String proposeTxSignature, String executeTxSignature, String executedByWallet, LocalDateTime createdAt, LocalDateTime executedAt) {
        super(GovernanceProposal.GOVERNANCE_PROPOSAL);

        setId(id);
        setGovernanceId(governanceId);
        setOnchainProposalId(onchainProposalId);
        setProposalPda(proposalPda);
        setEpoch(epoch);
        setKind(kind);
        setProposerWallet(proposerWallet);
        setAmountUsdc(amountUsdc);
        setTargetPubkey(targetPubkey);
        setPermissions(permissions);
        setAgentCode(agentCode);
        setNewSignersCsv(newSignersCsv);
        setNewThreshold(newThreshold);
        setStatus(status);
        setProposeTxSignature(proposeTxSignature);
        setExecuteTxSignature(executeTxSignature);
        setExecutedByWallet(executedByWallet);
        setCreatedAt(createdAt);
        setExecutedAt(executedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GovernanceProposalRecord
     */
    public GovernanceProposalRecord(com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.pojos.GovernanceProposal value) {
        super(GovernanceProposal.GOVERNANCE_PROPOSAL);

        if (value != null) {
            setId(value.getId());
            setGovernanceId(value.getGovernanceId());
            setOnchainProposalId(value.getOnchainProposalId());
            setProposalPda(value.getProposalPda());
            setEpoch(value.getEpoch());
            setKind(value.getKind());
            setProposerWallet(value.getProposerWallet());
            setAmountUsdc(value.getAmountUsdc());
            setTargetPubkey(value.getTargetPubkey());
            setPermissions(value.getPermissions());
            setAgentCode(value.getAgentCode());
            setNewSignersCsv(value.getNewSignersCsv());
            setNewThreshold(value.getNewThreshold());
            setStatus(value.getStatus());
            setProposeTxSignature(value.getProposeTxSignature());
            setExecuteTxSignature(value.getExecuteTxSignature());
            setExecutedByWallet(value.getExecutedByWallet());
            setCreatedAt(value.getCreatedAt());
            setExecutedAt(value.getExecutedAt());
            resetChangedOnNotNull();
        }
    }
}
