/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.TreasuryWithdrawal;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TreasuryWithdrawalRecord extends UpdatableRecordImpl<TreasuryWithdrawalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_onchain.treasury_withdrawal.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_onchain.treasury_withdrawal.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>eh8s_onchain.treasury_withdrawal.owner_wallet_pubkey</code>.
     */
    public void setOwnerWalletPubkey(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>eh8s_onchain.treasury_withdrawal.owner_wallet_pubkey</code>.
     */
    public String getOwnerWalletPubkey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>eh8s_onchain.treasury_withdrawal.amount_usdc</code>.
     */
    public void setAmountUsdc(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_onchain.treasury_withdrawal.amount_usdc</code>.
     */
    public BigDecimal getAmountUsdc() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>eh8s_onchain.treasury_withdrawal.tx_signature</code>.
     */
    public void setTxSignature(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_onchain.treasury_withdrawal.tx_signature</code>.
     */
    public String getTxSignature() {
        return (String) get(3);
    }

    /**
     * Setter for <code>eh8s_onchain.treasury_withdrawal.proposal_id</code>.
     */
    public void setProposalId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_onchain.treasury_withdrawal.proposal_id</code>.
     */
    public Long getProposalId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>eh8s_onchain.treasury_withdrawal.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_onchain.treasury_withdrawal.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TreasuryWithdrawalRecord
     */
    public TreasuryWithdrawalRecord() {
        super(TreasuryWithdrawal.TREASURY_WITHDRAWAL);
    }

    /**
     * Create a detached, initialised TreasuryWithdrawalRecord
     */
    public TreasuryWithdrawalRecord(Long id, String ownerWalletPubkey, BigDecimal amountUsdc, String txSignature, Long proposalId, LocalDateTime createdAt) {
        super(TreasuryWithdrawal.TREASURY_WITHDRAWAL);

        setId(id);
        setOwnerWalletPubkey(ownerWalletPubkey);
        setAmountUsdc(amountUsdc);
        setTxSignature(txSignature);
        setProposalId(proposalId);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TreasuryWithdrawalRecord
     */
    public TreasuryWithdrawalRecord(com.eh8s.eh8s.database.jooq.eh8s_onchain.tables.pojos.TreasuryWithdrawal value) {
        super(TreasuryWithdrawal.TREASURY_WITHDRAWAL);

        if (value != null) {
            setId(value.getId());
            setOwnerWalletPubkey(value.getOwnerWalletPubkey());
            setAmountUsdc(value.getAmountUsdc());
            setTxSignature(value.getTxSignature());
            setProposalId(value.getProposalId());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
