/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_academy.tables;


import com.eh8s.eh8s.database.jooq.eh8s.tables.Account.AccountPath;
import com.eh8s.eh8s.database.jooq.eh8s.tables.MusicianProfile.MusicianProfilePath;
import com.eh8s.eh8s.database.jooq.eh8s_academy.Eh8sAcademy;
import com.eh8s.eh8s.database.jooq.eh8s_academy.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.Lesson.LessonPath;
import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.records.EnigmaEvaluationRecord;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class EnigmaEvaluation extends TableImpl<EnigmaEvaluationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_academy.enigma_evaluation</code>
     */
    public static final EnigmaEvaluation ENIGMA_EVALUATION = new EnigmaEvaluation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EnigmaEvaluationRecord> getRecordType() {
        return EnigmaEvaluationRecord.class;
    }

    /**
     * The column <code>eh8s_academy.enigma_evaluation.id</code>.
     */
    public final TableField<EnigmaEvaluationRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>eh8s_academy.enigma_evaluation.musician_profile_id</code>.
     */
    public final TableField<EnigmaEvaluationRecord, Long> MUSICIAN_PROFILE_ID = createField(DSL.name("musician_profile_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.lesson_id</code>.
     */
    public final TableField<EnigmaEvaluationRecord, Long> LESSON_ID = createField(DSL.name("lesson_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>eh8s_academy.enigma_evaluation.evaluator_account_id</code>.
     */
    public final TableField<EnigmaEvaluationRecord, Long> EVALUATOR_ACCOUNT_ID = createField(DSL.name("evaluator_account_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.week_start</code>.
     */
    public final TableField<EnigmaEvaluationRecord, LocalDate> WEEK_START = createField(DSL.name("week_start"), SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.score</code>.
     */
    public final TableField<EnigmaEvaluationRecord, Byte> SCORE = createField(DSL.name("score"), SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.notes</code>.
     */
    public final TableField<EnigmaEvaluationRecord, String> NOTES = createField(DSL.name("notes"), SQLDataType.VARCHAR(500).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.recording_url</code>.
     */
    public final TableField<EnigmaEvaluationRecord, String> RECORDING_URL = createField(DSL.name("recording_url"), SQLDataType.VARCHAR(400).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.rubric_json</code>.
     */
    public final TableField<EnigmaEvaluationRecord, String> RUBRIC_JSON = createField(DSL.name("rubric_json"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.strengths</code>.
     */
    public final TableField<EnigmaEvaluationRecord, String> STRENGTHS = createField(DSL.name("strengths"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.errors_found</code>.
     */
    public final TableField<EnigmaEvaluationRecord, String> ERRORS_FOUND = createField(DSL.name("errors_found"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.exercises</code>.
     */
    public final TableField<EnigmaEvaluationRecord, String> EXERCISES = createField(DSL.name("exercises"), SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.recommended_level</code>.
     */
    public final TableField<EnigmaEvaluationRecord, Byte> RECOMMENDED_LEVEL = createField(DSL.name("recommended_level"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.source</code>.
     */
    public final TableField<EnigmaEvaluationRecord, String> SOURCE = createField(DSL.name("source"), SQLDataType.VARCHAR(16).nullable(false).defaultValue(DSL.field(DSL.raw("'manual'"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.ai_model</code>.
     */
    public final TableField<EnigmaEvaluationRecord, String> AI_MODEL = createField(DSL.name("ai_model"), SQLDataType.VARCHAR(64).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.applied_at</code>.
     */
    public final TableField<EnigmaEvaluationRecord, LocalDateTime> APPLIED_AT = createField(DSL.name("applied_at"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>eh8s_academy.enigma_evaluation.created_at</code>.
     */
    public final TableField<EnigmaEvaluationRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("current_timestamp()"), SQLDataType.LOCALDATETIME)), this, "");

    private EnigmaEvaluation(Name alias, Table<EnigmaEvaluationRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private EnigmaEvaluation(Name alias, Table<EnigmaEvaluationRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_academy.enigma_evaluation</code> table
     * reference
     */
    public EnigmaEvaluation(String alias) {
        this(DSL.name(alias), ENIGMA_EVALUATION);
    }

    /**
     * Create an aliased <code>eh8s_academy.enigma_evaluation</code> table
     * reference
     */
    public EnigmaEvaluation(Name alias) {
        this(alias, ENIGMA_EVALUATION);
    }

    /**
     * Create a <code>eh8s_academy.enigma_evaluation</code> table reference
     */
    public EnigmaEvaluation() {
        this(DSL.name("enigma_evaluation"), null);
    }

    public <O extends Record> EnigmaEvaluation(Table<O> path, ForeignKey<O, EnigmaEvaluationRecord> childPath, InverseForeignKey<O, EnigmaEvaluationRecord> parentPath) {
        super(path, childPath, parentPath, ENIGMA_EVALUATION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class EnigmaEvaluationPath extends EnigmaEvaluation implements Path<EnigmaEvaluationRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> EnigmaEvaluationPath(Table<O> path, ForeignKey<O, EnigmaEvaluationRecord> childPath, InverseForeignKey<O, EnigmaEvaluationRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private EnigmaEvaluationPath(Name alias, Table<EnigmaEvaluationRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public EnigmaEvaluationPath as(String alias) {
            return new EnigmaEvaluationPath(DSL.name(alias), this);
        }

        @Override
        public EnigmaEvaluationPath as(Name alias) {
            return new EnigmaEvaluationPath(alias, this);
        }

        @Override
        public EnigmaEvaluationPath as(Table<?> alias) {
            return new EnigmaEvaluationPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sAcademy.EH8S_ACADEMY;
    }

    @Override
    public Identity<EnigmaEvaluationRecord, Long> getIdentity() {
        return (Identity<EnigmaEvaluationRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<EnigmaEvaluationRecord> getPrimaryKey() {
        return Keys.KEY_ENIGMA_EVALUATION_PRIMARY;
    }

    @Override
    public List<ForeignKey<EnigmaEvaluationRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_EVAL_EVALUATOR, Keys.FK_EVAL_LESSON, Keys.FK_EVAL_MUSICIAN);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>eh8s.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_EVAL_EVALUATOR, null);

        return _account;
    }

    private transient LessonPath _lesson;

    /**
     * Get the implicit join path to the <code>eh8s_academy.lesson</code> table.
     */
    public LessonPath lesson() {
        if (_lesson == null)
            _lesson = new LessonPath(this, Keys.FK_EVAL_LESSON, null);

        return _lesson;
    }

    private transient MusicianProfilePath _musicianProfile;

    /**
     * Get the implicit join path to the <code>eh8s.musician_profile</code>
     * table.
     */
    public MusicianProfilePath musicianProfile() {
        if (_musicianProfile == null)
            _musicianProfile = new MusicianProfilePath(this, Keys.FK_EVAL_MUSICIAN, null);

        return _musicianProfile;
    }

    @Override
    public EnigmaEvaluation as(String alias) {
        return new EnigmaEvaluation(DSL.name(alias), this);
    }

    @Override
    public EnigmaEvaluation as(Name alias) {
        return new EnigmaEvaluation(alias, this);
    }

    @Override
    public EnigmaEvaluation as(Table<?> alias) {
        return new EnigmaEvaluation(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public EnigmaEvaluation rename(String name) {
        return new EnigmaEvaluation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnigmaEvaluation rename(Name name) {
        return new EnigmaEvaluation(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public EnigmaEvaluation rename(Table<?> name) {
        return new EnigmaEvaluation(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnigmaEvaluation where(Condition condition) {
        return new EnigmaEvaluation(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnigmaEvaluation where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnigmaEvaluation where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnigmaEvaluation where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnigmaEvaluation where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnigmaEvaluation where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnigmaEvaluation where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public EnigmaEvaluation where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnigmaEvaluation whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public EnigmaEvaluation whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
