/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_academy.tables;


import com.eh8s.eh8s.database.jooq.eh8s.tables.Account.AccountPath;
import com.eh8s.eh8s.database.jooq.eh8s_academy.Eh8sAcademy;
import com.eh8s.eh8s.database.jooq.eh8s_academy.Keys;
import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.AcademySubscription.AcademySubscriptionPath;
import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.records.InstructorProfileRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class InstructorProfile extends TableImpl<InstructorProfileRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>eh8s_academy.instructor_profile</code>
     */
    public static final InstructorProfile INSTRUCTOR_PROFILE = new InstructorProfile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<InstructorProfileRecord> getRecordType() {
        return InstructorProfileRecord.class;
    }

    /**
     * The column <code>eh8s_academy.instructor_profile.id</code>.
     */
    public final TableField<InstructorProfileRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>eh8s_academy.instructor_profile.account_id</code>.
     */
    public final TableField<InstructorProfileRecord, Long> ACCOUNT_ID = createField(DSL.name("account_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private InstructorProfile(Name alias, Table<InstructorProfileRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private InstructorProfile(Name alias, Table<InstructorProfileRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>eh8s_academy.instructor_profile</code> table
     * reference
     */
    public InstructorProfile(String alias) {
        this(DSL.name(alias), INSTRUCTOR_PROFILE);
    }

    /**
     * Create an aliased <code>eh8s_academy.instructor_profile</code> table
     * reference
     */
    public InstructorProfile(Name alias) {
        this(alias, INSTRUCTOR_PROFILE);
    }

    /**
     * Create a <code>eh8s_academy.instructor_profile</code> table reference
     */
    public InstructorProfile() {
        this(DSL.name("instructor_profile"), null);
    }

    public <O extends Record> InstructorProfile(Table<O> path, ForeignKey<O, InstructorProfileRecord> childPath, InverseForeignKey<O, InstructorProfileRecord> parentPath) {
        super(path, childPath, parentPath, INSTRUCTOR_PROFILE);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class InstructorProfilePath extends InstructorProfile implements Path<InstructorProfileRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> InstructorProfilePath(Table<O> path, ForeignKey<O, InstructorProfileRecord> childPath, InverseForeignKey<O, InstructorProfileRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private InstructorProfilePath(Name alias, Table<InstructorProfileRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public InstructorProfilePath as(String alias) {
            return new InstructorProfilePath(DSL.name(alias), this);
        }

        @Override
        public InstructorProfilePath as(Name alias) {
            return new InstructorProfilePath(alias, this);
        }

        @Override
        public InstructorProfilePath as(Table<?> alias) {
            return new InstructorProfilePath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Eh8sAcademy.EH8S_ACADEMY;
    }

    @Override
    public Identity<InstructorProfileRecord, Long> getIdentity() {
        return (Identity<InstructorProfileRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<InstructorProfileRecord> getPrimaryKey() {
        return Keys.KEY_INSTRUCTOR_PROFILE_PRIMARY;
    }

    @Override
    public List<UniqueKey<InstructorProfileRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_INSTRUCTOR_PROFILE_UK_INSTRUCTOR_ACCOUNT);
    }

    @Override
    public List<ForeignKey<InstructorProfileRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FK_INSTRUCTOR_ACCOUNT);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>eh8s.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.FK_INSTRUCTOR_ACCOUNT, null);

        return _account;
    }

    private transient AcademySubscriptionPath _academySubscription;

    /**
     * Get the implicit to-many join path to the
     * <code>eh8s_academy.academy_subscription</code> table
     */
    public AcademySubscriptionPath academySubscription() {
        if (_academySubscription == null)
            _academySubscription = new AcademySubscriptionPath(this, null, Keys.FK_SUB_INSTRUCTOR.getInverseKey());

        return _academySubscription;
    }

    @Override
    public InstructorProfile as(String alias) {
        return new InstructorProfile(DSL.name(alias), this);
    }

    @Override
    public InstructorProfile as(Name alias) {
        return new InstructorProfile(alias, this);
    }

    @Override
    public InstructorProfile as(Table<?> alias) {
        return new InstructorProfile(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public InstructorProfile rename(String name) {
        return new InstructorProfile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstructorProfile rename(Name name) {
        return new InstructorProfile(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public InstructorProfile rename(Table<?> name) {
        return new InstructorProfile(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstructorProfile where(Condition condition) {
        return new InstructorProfile(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstructorProfile where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstructorProfile where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstructorProfile where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstructorProfile where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstructorProfile where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstructorProfile where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public InstructorProfile where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstructorProfile whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public InstructorProfile whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
