/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.ChannelPiece;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChannelPieceRecord extends UpdatableRecordImpl<ChannelPieceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_catalog.channel_piece.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_catalog.channel_piece.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_catalog.channel_piece.channel_format_id</code>.
     */
    public void setChannelFormatId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_catalog.channel_piece.channel_format_id</code>.
     */
    public Long getChannelFormatId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s_catalog.channel_piece.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_catalog.channel_piece.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s_catalog.channel_piece.artist_share_bps</code>.
     */
    public void setArtistShareBps(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_catalog.channel_piece.artist_share_bps</code>.
     */
    public Integer getArtistShareBps() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>eh8s_catalog.channel_piece.eh8s_share_bps</code>.
     */
    public void setEh8sShareBps(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_catalog.channel_piece.eh8s_share_bps</code>.
     */
    public Integer getEh8sShareBps() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelPieceRecord
     */
    public ChannelPieceRecord() {
        super(ChannelPiece.CHANNEL_PIECE);
    }

    /**
     * Create a detached, initialised ChannelPieceRecord
     */
    public ChannelPieceRecord(Long id, Long channelFormatId, String title, Integer artistShareBps, Integer eh8sShareBps) {
        super(ChannelPiece.CHANNEL_PIECE);

        setId(id);
        setChannelFormatId(channelFormatId);
        setTitle(title);
        setArtistShareBps(artistShareBps);
        setEh8sShareBps(eh8sShareBps);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ChannelPieceRecord
     */
    public ChannelPieceRecord(com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.pojos.ChannelPiece value) {
        super(ChannelPiece.CHANNEL_PIECE);

        if (value != null) {
            setId(value.getId());
            setChannelFormatId(value.getChannelFormatId());
            setTitle(value.getTitle());
            setArtistShareBps(value.getArtistShareBps());
            setEh8sShareBps(value.getEh8sShareBps());
            resetChangedOnNotNull();
        }
    }
}
