/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.RoyaltySplit;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RoyaltySplitRecord extends UpdatableRecordImpl<RoyaltySplitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_catalog.royalty_split.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_catalog.royalty_split.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_catalog.royalty_split.track_id</code>.
     */
    public void setTrackId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_catalog.royalty_split.track_id</code>.
     */
    public Long getTrackId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s_catalog.royalty_split.royalty_type_id</code>.
     */
    public void setRoyaltyTypeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_catalog.royalty_split.royalty_type_id</code>.
     */
    public Long getRoyaltyTypeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>eh8s_catalog.royalty_split.musician_profile_id</code>.
     */
    public void setMusicianProfileId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_catalog.royalty_split.musician_profile_id</code>.
     */
    public Long getMusicianProfileId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>eh8s_catalog.royalty_split.party</code>.
     */
    public void setParty(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_catalog.royalty_split.party</code>.
     */
    public String getParty() {
        return (String) get(4);
    }

    /**
     * Setter for <code>eh8s_catalog.royalty_split.share_bps</code>.
     */
    public void setShareBps(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_catalog.royalty_split.share_bps</code>.
     */
    public Integer getShareBps() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoyaltySplitRecord
     */
    public RoyaltySplitRecord() {
        super(RoyaltySplit.ROYALTY_SPLIT);
    }

    /**
     * Create a detached, initialised RoyaltySplitRecord
     */
    public RoyaltySplitRecord(Long id, Long trackId, Long royaltyTypeId, Long musicianProfileId, String party, Integer shareBps) {
        super(RoyaltySplit.ROYALTY_SPLIT);

        setId(id);
        setTrackId(trackId);
        setRoyaltyTypeId(royaltyTypeId);
        setMusicianProfileId(musicianProfileId);
        setParty(party);
        setShareBps(shareBps);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised RoyaltySplitRecord
     */
    public RoyaltySplitRecord(com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.pojos.RoyaltySplit value) {
        super(RoyaltySplit.ROYALTY_SPLIT);

        if (value != null) {
            setId(value.getId());
            setTrackId(value.getTrackId());
            setRoyaltyTypeId(value.getRoyaltyTypeId());
            setMusicianProfileId(value.getMusicianProfileId());
            setParty(value.getParty());
            setShareBps(value.getShareBps());
            resetChangedOnNotNull();
        }
    }
}
