/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.TourPlan;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TourPlanRecord extends UpdatableRecordImpl<TourPlanRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_catalog.tour_plan.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.band_id</code>.
     */
    public void setBandId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.band_id</code>.
     */
    public Long getBandId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.geo_region_id</code>.
     */
    public void setGeoRegionId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.geo_region_id</code>.
     */
    public Long getGeoRegionId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.route_note</code>.
     */
    public void setRouteNote(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.route_note</code>.
     */
    public String getRouteNote() {
        return (String) get(4);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.window_start</code>.
     */
    public void setWindowStart(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.window_start</code>.
     */
    public LocalDate getWindowStart() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.window_end</code>.
     */
    public void setWindowEnd(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.window_end</code>.
     */
    public LocalDate getWindowEnd() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.total_km</code>.
     */
    public void setTotalKm(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.total_km</code>.
     */
    public BigDecimal getTotalKm() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.projected_income_usdc</code>.
     */
    public void setProjectedIncomeUsdc(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.projected_income_usdc</code>.
     */
    public BigDecimal getProjectedIncomeUsdc() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.generated_by</code>.
     */
    public void setGeneratedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.generated_by</code>.
     */
    public String getGeneratedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TourPlanRecord
     */
    public TourPlanRecord() {
        super(TourPlan.TOUR_PLAN);
    }

    /**
     * Create a detached, initialised TourPlanRecord
     */
    public TourPlanRecord(Long id, Long bandId, Long geoRegionId, String title, String routeNote, LocalDate windowStart, LocalDate windowEnd, BigDecimal totalKm, BigDecimal projectedIncomeUsdc, String generatedBy, LocalDateTime createdAt) {
        super(TourPlan.TOUR_PLAN);

        setId(id);
        setBandId(bandId);
        setGeoRegionId(geoRegionId);
        setTitle(title);
        setRouteNote(routeNote);
        setWindowStart(windowStart);
        setWindowEnd(windowEnd);
        setTotalKm(totalKm);
        setProjectedIncomeUsdc(projectedIncomeUsdc);
        setGeneratedBy(generatedBy);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TourPlanRecord
     */
    public TourPlanRecord(com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.pojos.TourPlan value) {
        super(TourPlan.TOUR_PLAN);

        if (value != null) {
            setId(value.getId());
            setBandId(value.getBandId());
            setGeoRegionId(value.getGeoRegionId());
            setTitle(value.getTitle());
            setRouteNote(value.getRouteNote());
            setWindowStart(value.getWindowStart());
            setWindowEnd(value.getWindowEnd());
            setTotalKm(value.getTotalKm());
            setProjectedIncomeUsdc(value.getProjectedIncomeUsdc());
            setGeneratedBy(value.getGeneratedBy());
            setCreatedAt(value.getCreatedAt());
            resetChangedOnNotNull();
        }
    }
}
