/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.TourPlanStop;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TourPlanStopRecord extends UpdatableRecordImpl<TourPlanStopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_catalog.tour_plan_stop.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan_stop.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan_stop.tour_plan_id</code>.
     */
    public void setTourPlanId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan_stop.tour_plan_id</code>.
     */
    public Long getTourPlanId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan_stop.stop_order</code>.
     */
    public void setStopOrder(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan_stop.stop_order</code>.
     */
    public Byte getStopOrder() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan_stop.venue_id</code>.
     */
    public void setVenueId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan_stop.venue_id</code>.
     */
    public Long getVenueId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan_stop.show_date</code>.
     */
    public void setShowDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan_stop.show_date</code>.
     */
    public LocalDate getShowDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>eh8s_catalog.tour_plan_stop.leg_km</code>.
     */
    public void setLegKm(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_catalog.tour_plan_stop.leg_km</code>.
     */
    public BigDecimal getLegKm() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>eh8s_catalog.tour_plan_stop.projected_income_usdc</code>.
     */
    public void setProjectedIncomeUsdc(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>eh8s_catalog.tour_plan_stop.projected_income_usdc</code>.
     */
    public BigDecimal getProjectedIncomeUsdc() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TourPlanStopRecord
     */
    public TourPlanStopRecord() {
        super(TourPlanStop.TOUR_PLAN_STOP);
    }

    /**
     * Create a detached, initialised TourPlanStopRecord
     */
    public TourPlanStopRecord(Long id, Long tourPlanId, Byte stopOrder, Long venueId, LocalDate showDate, BigDecimal legKm, BigDecimal projectedIncomeUsdc) {
        super(TourPlanStop.TOUR_PLAN_STOP);

        setId(id);
        setTourPlanId(tourPlanId);
        setStopOrder(stopOrder);
        setVenueId(venueId);
        setShowDate(showDate);
        setLegKm(legKm);
        setProjectedIncomeUsdc(projectedIncomeUsdc);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised TourPlanStopRecord
     */
    public TourPlanStopRecord(com.eh8s.eh8s.database.jooq.eh8s_catalog.tables.pojos.TourPlanStop value) {
        super(TourPlanStop.TOUR_PLAN_STOP);

        if (value != null) {
            setId(value.getId());
            setTourPlanId(value.getTourPlanId());
            setStopOrder(value.getStopOrder());
            setVenueId(value.getVenueId());
            setShowDate(value.getShowDate());
            setLegKm(value.getLegKm());
            setProjectedIncomeUsdc(value.getProjectedIncomeUsdc());
            resetChangedOnNotNull();
        }
    }
}
