/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s;


import com.eh8s.eh8s.database.jooq.eh8s.tables.MusicianLevelChange;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in eh8s.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MUSICIAN_LEVEL_CHANGE_IDX_LEVEL_CHANGE_MUSICIAN = Internal.createIndex(DSL.name("idx_level_change_musician"), MusicianLevelChange.MUSICIAN_LEVEL_CHANGE, new OrderField[] { MusicianLevelChange.MUSICIAN_LEVEL_CHANGE.MUSICIAN_PROFILE_ID }, false);
}
