/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s;


import com.eh8s.eh8s.database.jooq.eh8s.tables.Account;
import com.eh8s.eh8s.database.jooq.eh8s.tables.AppMeta;
import com.eh8s.eh8s.database.jooq.eh8s.tables.Band;
import com.eh8s.eh8s.database.jooq.eh8s.tables.BandMatchSuggestion;
import com.eh8s.eh8s.database.jooq.eh8s.tables.BandMember;
import com.eh8s.eh8s.database.jooq.eh8s.tables.Booking;
import com.eh8s.eh8s.database.jooq.eh8s.tables.Concert;
import com.eh8s.eh8s.database.jooq.eh8s.tables.ConcertExpense;
import com.eh8s.eh8s.database.jooq.eh8s.tables.ConcertSetCheckin;
import com.eh8s.eh8s.database.jooq.eh8s.tables.ConcertSettlement;
import com.eh8s.eh8s.database.jooq.eh8s.tables.ContractType;
import com.eh8s.eh8s.database.jooq.eh8s.tables.CreativeRating;
import com.eh8s.eh8s.database.jooq.eh8s.tables.EnigmaLevel;
import com.eh8s.eh8s.database.jooq.eh8s.tables.Instrument;
import com.eh8s.eh8s.database.jooq.eh8s.tables.MusicianLevelChange;
import com.eh8s.eh8s.database.jooq.eh8s.tables.MusicianProfile;
import com.eh8s.eh8s.database.jooq.eh8s.tables.PendingClaim;
import com.eh8s.eh8s.database.jooq.eh8s.tables.RehearsalCheckin;
import com.eh8s.eh8s.database.jooq.eh8s.tables.RehearsalSession;
import com.eh8s.eh8s.database.jooq.eh8s.tables.SppCycle;
import com.eh8s.eh8s.database.jooq.eh8s.tables.SppMemberScore;
import com.eh8s.eh8s.database.jooq.eh8s.tables.SppVariable;
import com.eh8s.eh8s.database.jooq.eh8s.tables.Venue;
import com.eh8s.eh8s.database.jooq.eh8s.tables.VenueAvailability;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.AccountRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.AppMetaRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.BandMatchSuggestionRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.BandMemberRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.BandRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.BookingRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.ConcertExpenseRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.ConcertRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.ConcertSetCheckinRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.ConcertSettlementRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.ContractTypeRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.CreativeRatingRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.EnigmaLevelRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.InstrumentRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.MusicianLevelChangeRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.MusicianProfileRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.PendingClaimRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.RehearsalCheckinRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.RehearsalSessionRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.SppCycleRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.SppMemberScoreRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.SppVariableRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.VenueAvailabilityRecord;
import com.eh8s.eh8s.database.jooq.eh8s.tables.records.VenueRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * eh8s.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_PRIMARY = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("KEY_account_PRIMARY"), new TableField[] { Account.ACCOUNT.ID }, true);
    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_UK_ACCOUNT_EMAIL = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("KEY_account_uk_account_email"), new TableField[] { Account.ACCOUNT.EMAIL }, true);
    public static final UniqueKey<AccountRecord> KEY_ACCOUNT_UK_ACCOUNT_WALLET = Internal.createUniqueKey(Account.ACCOUNT, DSL.name("KEY_account_uk_account_wallet"), new TableField[] { Account.ACCOUNT.WALLET_PUBKEY }, true);
    public static final UniqueKey<AppMetaRecord> KEY_APP_META_PRIMARY = Internal.createUniqueKey(AppMeta.APP_META, DSL.name("KEY_app_meta_PRIMARY"), new TableField[] { AppMeta.APP_META.META_KEY }, true);
    public static final UniqueKey<BandRecord> KEY_BAND_PRIMARY = Internal.createUniqueKey(Band.BAND, DSL.name("KEY_band_PRIMARY"), new TableField[] { Band.BAND.ID }, true);
    public static final UniqueKey<BandRecord> KEY_BAND_UK_BAND_CODE = Internal.createUniqueKey(Band.BAND, DSL.name("KEY_band_uk_band_code"), new TableField[] { Band.BAND.CODE }, true);
    public static final UniqueKey<BandRecord> KEY_BAND_UK_BAND_VAULT_PDA = Internal.createUniqueKey(Band.BAND, DSL.name("KEY_band_uk_band_vault_pda"), new TableField[] { Band.BAND.BAND_VAULT_PDA }, true);
    public static final UniqueKey<BandRecord> KEY_BAND_UK_BAND_VAULT_TX = Internal.createUniqueKey(Band.BAND, DSL.name("KEY_band_uk_band_vault_tx"), new TableField[] { Band.BAND.VAULT_TX_SIGNATURE }, true);
    public static final UniqueKey<BandMatchSuggestionRecord> KEY_BAND_MATCH_SUGGESTION_PRIMARY = Internal.createUniqueKey(BandMatchSuggestion.BAND_MATCH_SUGGESTION, DSL.name("KEY_band_match_suggestion_PRIMARY"), new TableField[] { BandMatchSuggestion.BAND_MATCH_SUGGESTION.ID }, true);
    public static final UniqueKey<BandMatchSuggestionRecord> KEY_BAND_MATCH_SUGGESTION_UK_BAND_MATCH = Internal.createUniqueKey(BandMatchSuggestion.BAND_MATCH_SUGGESTION, DSL.name("KEY_band_match_suggestion_uk_band_match"), new TableField[] { BandMatchSuggestion.BAND_MATCH_SUGGESTION.BAND_ID, BandMatchSuggestion.BAND_MATCH_SUGGESTION.MUSICIAN_PROFILE_ID }, true);
    public static final UniqueKey<BandMemberRecord> KEY_BAND_MEMBER_PRIMARY = Internal.createUniqueKey(BandMember.BAND_MEMBER, DSL.name("KEY_band_member_PRIMARY"), new TableField[] { BandMember.BAND_MEMBER.ID }, true);
    public static final UniqueKey<BandMemberRecord> KEY_BAND_MEMBER_UK_BAND_MEMBER = Internal.createUniqueKey(BandMember.BAND_MEMBER, DSL.name("KEY_band_member_uk_band_member"), new TableField[] { BandMember.BAND_MEMBER.BAND_ID, BandMember.BAND_MEMBER.MUSICIAN_PROFILE_ID }, true);
    public static final UniqueKey<BookingRecord> KEY_BOOKING_PRIMARY = Internal.createUniqueKey(Booking.BOOKING, DSL.name("KEY_booking_PRIMARY"), new TableField[] { Booking.BOOKING.ID }, true);
    public static final UniqueKey<BookingRecord> KEY_BOOKING_UK_BOOKING_ACCESS_PDA = Internal.createUniqueKey(Booking.BOOKING, DSL.name("KEY_booking_uk_booking_access_pda"), new TableField[] { Booking.BOOKING.VENUE_ACCESS_TOKEN_PDA }, true);
    public static final UniqueKey<BookingRecord> KEY_BOOKING_UK_BOOKING_CANCEL_TX = Internal.createUniqueKey(Booking.BOOKING, DSL.name("KEY_booking_uk_booking_cancel_tx"), new TableField[] { Booking.BOOKING.CANCEL_TX_SIGNATURE }, true);
    public static final UniqueKey<BookingRecord> KEY_BOOKING_UK_BOOKING_CONFIRM_TX = Internal.createUniqueKey(Booking.BOOKING, DSL.name("KEY_booking_uk_booking_confirm_tx"), new TableField[] { Booking.BOOKING.CONFIRM_TX_SIGNATURE }, true);
    public static final UniqueKey<BookingRecord> KEY_BOOKING_UK_BOOKING_ONCHAIN_CONCERT = Internal.createUniqueKey(Booking.BOOKING, DSL.name("KEY_booking_uk_booking_onchain_concert"), new TableField[] { Booking.BOOKING.VENUE_ID, Booking.BOOKING.ONCHAIN_CONCERT_ID }, true);
    public static final UniqueKey<BookingRecord> KEY_BOOKING_UK_BOOKING_PROPOSE_TX = Internal.createUniqueKey(Booking.BOOKING, DSL.name("KEY_booking_uk_booking_propose_tx"), new TableField[] { Booking.BOOKING.PROPOSE_TX_SIGNATURE }, true);
    public static final UniqueKey<BookingRecord> KEY_BOOKING_UK_BOOKING_SLOT = Internal.createUniqueKey(Booking.BOOKING, DSL.name("KEY_booking_uk_booking_slot"), new TableField[] { Booking.BOOKING.VENUE_ID, Booking.BOOKING.BAND_ID, Booking.BOOKING.SHOW_DATE }, true);
    public static final UniqueKey<ConcertRecord> KEY_CONCERT_PRIMARY = Internal.createUniqueKey(Concert.CONCERT, DSL.name("KEY_concert_PRIMARY"), new TableField[] { Concert.CONCERT.ID }, true);
    public static final UniqueKey<ConcertRecord> KEY_CONCERT_UK_CONCERT_BOOKING = Internal.createUniqueKey(Concert.CONCERT, DSL.name("KEY_concert_uk_concert_booking"), new TableField[] { Concert.CONCERT.BOOKING_ID }, true);
    public static final UniqueKey<ConcertExpenseRecord> KEY_CONCERT_EXPENSE_PRIMARY = Internal.createUniqueKey(ConcertExpense.CONCERT_EXPENSE, DSL.name("KEY_concert_expense_PRIMARY"), new TableField[] { ConcertExpense.CONCERT_EXPENSE.ID }, true);
    public static final UniqueKey<ConcertSetCheckinRecord> KEY_CONCERT_SET_CHECKIN_PRIMARY = Internal.createUniqueKey(ConcertSetCheckin.CONCERT_SET_CHECKIN, DSL.name("KEY_concert_set_checkin_PRIMARY"), new TableField[] { ConcertSetCheckin.CONCERT_SET_CHECKIN.ID }, true);
    public static final UniqueKey<ConcertSetCheckinRecord> KEY_CONCERT_SET_CHECKIN_UK_CONCERT_SET_CHECKIN = Internal.createUniqueKey(ConcertSetCheckin.CONCERT_SET_CHECKIN, DSL.name("KEY_concert_set_checkin_uk_concert_set_checkin"), new TableField[] { ConcertSetCheckin.CONCERT_SET_CHECKIN.CONCERT_ID, ConcertSetCheckin.CONCERT_SET_CHECKIN.MUSICIAN_PROFILE_ID }, true);
    public static final UniqueKey<ConcertSettlementRecord> KEY_CONCERT_SETTLEMENT_PRIMARY = Internal.createUniqueKey(ConcertSettlement.CONCERT_SETTLEMENT, DSL.name("KEY_concert_settlement_PRIMARY"), new TableField[] { ConcertSettlement.CONCERT_SETTLEMENT.ID }, true);
    public static final UniqueKey<ConcertSettlementRecord> KEY_CONCERT_SETTLEMENT_UK_SETTLEMENT_CONCERT = Internal.createUniqueKey(ConcertSettlement.CONCERT_SETTLEMENT, DSL.name("KEY_concert_settlement_uk_settlement_concert"), new TableField[] { ConcertSettlement.CONCERT_SETTLEMENT.CONCERT_ID }, true);
    public static final UniqueKey<ConcertSettlementRecord> KEY_CONCERT_SETTLEMENT_UK_SETTLEMENT_TX = Internal.createUniqueKey(ConcertSettlement.CONCERT_SETTLEMENT, DSL.name("KEY_concert_settlement_uk_settlement_tx"), new TableField[] { ConcertSettlement.CONCERT_SETTLEMENT.SETTLE_TX_SIGNATURE }, true);
    public static final UniqueKey<ContractTypeRecord> KEY_CONTRACT_TYPE_PRIMARY = Internal.createUniqueKey(ContractType.CONTRACT_TYPE, DSL.name("KEY_contract_type_PRIMARY"), new TableField[] { ContractType.CONTRACT_TYPE.ID }, true);
    public static final UniqueKey<ContractTypeRecord> KEY_CONTRACT_TYPE_UK_CONTRACT_TYPE_CODE = Internal.createUniqueKey(ContractType.CONTRACT_TYPE, DSL.name("KEY_contract_type_uk_contract_type_code"), new TableField[] { ContractType.CONTRACT_TYPE.CODE }, true);
    public static final UniqueKey<CreativeRatingRecord> KEY_CREATIVE_RATING_PRIMARY = Internal.createUniqueKey(CreativeRating.CREATIVE_RATING, DSL.name("KEY_creative_rating_PRIMARY"), new TableField[] { CreativeRating.CREATIVE_RATING.ID }, true);
    public static final UniqueKey<CreativeRatingRecord> KEY_CREATIVE_RATING_UK_CREATIVE_RATING = Internal.createUniqueKey(CreativeRating.CREATIVE_RATING, DSL.name("KEY_creative_rating_uk_creative_rating"), new TableField[] { CreativeRating.CREATIVE_RATING.REHEARSAL_SESSION_ID, CreativeRating.CREATIVE_RATING.RATER_PROFILE_ID, CreativeRating.CREATIVE_RATING.RATEE_PROFILE_ID }, true);
    public static final UniqueKey<EnigmaLevelRecord> KEY_ENIGMA_LEVEL_PRIMARY = Internal.createUniqueKey(EnigmaLevel.ENIGMA_LEVEL, DSL.name("KEY_enigma_level_PRIMARY"), new TableField[] { EnigmaLevel.ENIGMA_LEVEL.ID }, true);
    public static final UniqueKey<EnigmaLevelRecord> KEY_ENIGMA_LEVEL_UK_ENIGMA_LEVEL_NUMBER = Internal.createUniqueKey(EnigmaLevel.ENIGMA_LEVEL, DSL.name("KEY_enigma_level_uk_enigma_level_number"), new TableField[] { EnigmaLevel.ENIGMA_LEVEL.LEVEL_NUMBER }, true);
    public static final UniqueKey<InstrumentRecord> KEY_INSTRUMENT_PRIMARY = Internal.createUniqueKey(Instrument.INSTRUMENT, DSL.name("KEY_instrument_PRIMARY"), new TableField[] { Instrument.INSTRUMENT.ID }, true);
    public static final UniqueKey<InstrumentRecord> KEY_INSTRUMENT_UK_INSTRUMENT_CODE = Internal.createUniqueKey(Instrument.INSTRUMENT, DSL.name("KEY_instrument_uk_instrument_code"), new TableField[] { Instrument.INSTRUMENT.CODE }, true);
    public static final UniqueKey<MusicianLevelChangeRecord> KEY_MUSICIAN_LEVEL_CHANGE_PRIMARY = Internal.createUniqueKey(MusicianLevelChange.MUSICIAN_LEVEL_CHANGE, DSL.name("KEY_musician_level_change_PRIMARY"), new TableField[] { MusicianLevelChange.MUSICIAN_LEVEL_CHANGE.ID }, true);
    public static final UniqueKey<MusicianLevelChangeRecord> KEY_MUSICIAN_LEVEL_CHANGE_UK_LEVEL_CHANGE_TX = Internal.createUniqueKey(MusicianLevelChange.MUSICIAN_LEVEL_CHANGE, DSL.name("KEY_musician_level_change_uk_level_change_tx"), new TableField[] { MusicianLevelChange.MUSICIAN_LEVEL_CHANGE.TX_SIGNATURE }, true);
    public static final UniqueKey<MusicianProfileRecord> KEY_MUSICIAN_PROFILE_PRIMARY = Internal.createUniqueKey(MusicianProfile.MUSICIAN_PROFILE, DSL.name("KEY_musician_profile_PRIMARY"), new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final UniqueKey<MusicianProfileRecord> KEY_MUSICIAN_PROFILE_UK_MUSICIAN_ACCOUNT = Internal.createUniqueKey(MusicianProfile.MUSICIAN_PROFILE, DSL.name("KEY_musician_profile_uk_musician_account"), new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ACCOUNT_ID }, true);
    public static final UniqueKey<PendingClaimRecord> KEY_PENDING_CLAIM_PRIMARY = Internal.createUniqueKey(PendingClaim.PENDING_CLAIM, DSL.name("KEY_pending_claim_PRIMARY"), new TableField[] { PendingClaim.PENDING_CLAIM.ID }, true);
    public static final UniqueKey<PendingClaimRecord> KEY_PENDING_CLAIM_UK_CLAIM_PDA = Internal.createUniqueKey(PendingClaim.PENDING_CLAIM, DSL.name("KEY_pending_claim_uk_claim_pda"), new TableField[] { PendingClaim.PENDING_CLAIM.CLAIM_PDA }, true);
    public static final UniqueKey<PendingClaimRecord> KEY_PENDING_CLAIM_UK_CLAIM_SETTLEMENT_MUSICIAN = Internal.createUniqueKey(PendingClaim.PENDING_CLAIM, DSL.name("KEY_pending_claim_uk_claim_settlement_musician"), new TableField[] { PendingClaim.PENDING_CLAIM.CONCERT_SETTLEMENT_ID, PendingClaim.PENDING_CLAIM.MUSICIAN_PROFILE_ID }, true);
    public static final UniqueKey<PendingClaimRecord> KEY_PENDING_CLAIM_UK_CLAIM_TX = Internal.createUniqueKey(PendingClaim.PENDING_CLAIM, DSL.name("KEY_pending_claim_uk_claim_tx"), new TableField[] { PendingClaim.PENDING_CLAIM.TX_SIGNATURE }, true);
    public static final UniqueKey<RehearsalCheckinRecord> KEY_REHEARSAL_CHECKIN_PRIMARY = Internal.createUniqueKey(RehearsalCheckin.REHEARSAL_CHECKIN, DSL.name("KEY_rehearsal_checkin_PRIMARY"), new TableField[] { RehearsalCheckin.REHEARSAL_CHECKIN.ID }, true);
    public static final UniqueKey<RehearsalCheckinRecord> KEY_REHEARSAL_CHECKIN_UK_CHECKIN = Internal.createUniqueKey(RehearsalCheckin.REHEARSAL_CHECKIN, DSL.name("KEY_rehearsal_checkin_uk_checkin"), new TableField[] { RehearsalCheckin.REHEARSAL_CHECKIN.REHEARSAL_SESSION_ID, RehearsalCheckin.REHEARSAL_CHECKIN.MUSICIAN_PROFILE_ID }, true);
    public static final UniqueKey<RehearsalSessionRecord> KEY_REHEARSAL_SESSION_PRIMARY = Internal.createUniqueKey(RehearsalSession.REHEARSAL_SESSION, DSL.name("KEY_rehearsal_session_PRIMARY"), new TableField[] { RehearsalSession.REHEARSAL_SESSION.ID }, true);
    public static final UniqueKey<SppCycleRecord> KEY_SPP_CYCLE_PRIMARY = Internal.createUniqueKey(SppCycle.SPP_CYCLE, DSL.name("KEY_spp_cycle_PRIMARY"), new TableField[] { SppCycle.SPP_CYCLE.ID }, true);
    public static final UniqueKey<SppCycleRecord> KEY_SPP_CYCLE_UK_SPP_CYCLE_BAND_CODE = Internal.createUniqueKey(SppCycle.SPP_CYCLE, DSL.name("KEY_spp_cycle_uk_spp_cycle_band_code"), new TableField[] { SppCycle.SPP_CYCLE.BAND_ID, SppCycle.SPP_CYCLE.CODE }, true);
    public static final UniqueKey<SppMemberScoreRecord> KEY_SPP_MEMBER_SCORE_PRIMARY = Internal.createUniqueKey(SppMemberScore.SPP_MEMBER_SCORE, DSL.name("KEY_spp_member_score_PRIMARY"), new TableField[] { SppMemberScore.SPP_MEMBER_SCORE.ID }, true);
    public static final UniqueKey<SppMemberScoreRecord> KEY_SPP_MEMBER_SCORE_UK_SPP_SCORE = Internal.createUniqueKey(SppMemberScore.SPP_MEMBER_SCORE, DSL.name("KEY_spp_member_score_uk_spp_score"), new TableField[] { SppMemberScore.SPP_MEMBER_SCORE.SPP_CYCLE_ID, SppMemberScore.SPP_MEMBER_SCORE.MUSICIAN_PROFILE_ID }, true);
    public static final UniqueKey<SppVariableRecord> KEY_SPP_VARIABLE_PRIMARY = Internal.createUniqueKey(SppVariable.SPP_VARIABLE, DSL.name("KEY_spp_variable_PRIMARY"), new TableField[] { SppVariable.SPP_VARIABLE.ID }, true);
    public static final UniqueKey<SppVariableRecord> KEY_SPP_VARIABLE_UK_SPP_VARIABLE_CODE = Internal.createUniqueKey(SppVariable.SPP_VARIABLE, DSL.name("KEY_spp_variable_uk_spp_variable_code"), new TableField[] { SppVariable.SPP_VARIABLE.CODE }, true);
    public static final UniqueKey<VenueRecord> KEY_VENUE_PRIMARY = Internal.createUniqueKey(Venue.VENUE, DSL.name("KEY_venue_PRIMARY"), new TableField[] { Venue.VENUE.ID }, true);
    public static final UniqueKey<VenueRecord> KEY_VENUE_UK_VENUE_APPROVE_TX = Internal.createUniqueKey(Venue.VENUE, DSL.name("KEY_venue_uk_venue_approve_tx"), new TableField[] { Venue.VENUE.APPROVE_TX_SIGNATURE }, true);
    public static final UniqueKey<VenueRecord> KEY_VENUE_UK_VENUE_CODE = Internal.createUniqueKey(Venue.VENUE, DSL.name("KEY_venue_uk_venue_code"), new TableField[] { Venue.VENUE.CODE }, true);
    public static final UniqueKey<VenueRecord> KEY_VENUE_UK_VENUE_REGISTER_TX = Internal.createUniqueKey(Venue.VENUE, DSL.name("KEY_venue_uk_venue_register_tx"), new TableField[] { Venue.VENUE.REGISTER_TX_SIGNATURE }, true);
    public static final UniqueKey<VenueAvailabilityRecord> KEY_VENUE_AVAILABILITY_PRIMARY = Internal.createUniqueKey(VenueAvailability.VENUE_AVAILABILITY, DSL.name("KEY_venue_availability_PRIMARY"), new TableField[] { VenueAvailability.VENUE_AVAILABILITY.ID }, true);
    public static final UniqueKey<VenueAvailabilityRecord> KEY_VENUE_AVAILABILITY_UK_VENUE_AVAILABILITY = Internal.createUniqueKey(VenueAvailability.VENUE_AVAILABILITY, DSL.name("KEY_venue_availability_uk_venue_availability"), new TableField[] { VenueAvailability.VENUE_AVAILABILITY.VENUE_ID, VenueAvailability.VENUE_AVAILABILITY.AVAILABLE_DATE }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BandMatchSuggestionRecord, BandRecord> FK_BAND_MATCH_BAND = Internal.createForeignKey(BandMatchSuggestion.BAND_MATCH_SUGGESTION, DSL.name("fk_band_match_band"), new TableField[] { BandMatchSuggestion.BAND_MATCH_SUGGESTION.BAND_ID }, Keys.KEY_BAND_PRIMARY, new TableField[] { Band.BAND.ID }, true);
    public static final ForeignKey<BandMatchSuggestionRecord, MusicianProfileRecord> FK_BAND_MATCH_MUSICIAN = Internal.createForeignKey(BandMatchSuggestion.BAND_MATCH_SUGGESTION, DSL.name("fk_band_match_musician"), new TableField[] { BandMatchSuggestion.BAND_MATCH_SUGGESTION.MUSICIAN_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<BandMemberRecord, BandRecord> FK_MEMBER_BAND = Internal.createForeignKey(BandMember.BAND_MEMBER, DSL.name("fk_member_band"), new TableField[] { BandMember.BAND_MEMBER.BAND_ID }, Keys.KEY_BAND_PRIMARY, new TableField[] { Band.BAND.ID }, true);
    public static final ForeignKey<BandMemberRecord, MusicianProfileRecord> FK_MEMBER_MUSICIAN = Internal.createForeignKey(BandMember.BAND_MEMBER, DSL.name("fk_member_musician"), new TableField[] { BandMember.BAND_MEMBER.MUSICIAN_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<BookingRecord, BandRecord> FK_BOOKING_BAND = Internal.createForeignKey(Booking.BOOKING, DSL.name("fk_booking_band"), new TableField[] { Booking.BOOKING.BAND_ID }, Keys.KEY_BAND_PRIMARY, new TableField[] { Band.BAND.ID }, true);
    public static final ForeignKey<BookingRecord, VenueRecord> FK_BOOKING_VENUE = Internal.createForeignKey(Booking.BOOKING, DSL.name("fk_booking_venue"), new TableField[] { Booking.BOOKING.VENUE_ID }, Keys.KEY_VENUE_PRIMARY, new TableField[] { Venue.VENUE.ID }, true);
    public static final ForeignKey<ConcertRecord, BandRecord> FK_CONCERT_BAND = Internal.createForeignKey(Concert.CONCERT, DSL.name("fk_concert_band"), new TableField[] { Concert.CONCERT.BAND_ID }, Keys.KEY_BAND_PRIMARY, new TableField[] { Band.BAND.ID }, true);
    public static final ForeignKey<ConcertRecord, BookingRecord> FK_CONCERT_BOOKING = Internal.createForeignKey(Concert.CONCERT, DSL.name("fk_concert_booking"), new TableField[] { Concert.CONCERT.BOOKING_ID }, Keys.KEY_BOOKING_PRIMARY, new TableField[] { Booking.BOOKING.ID }, true);
    public static final ForeignKey<ConcertRecord, SppCycleRecord> FK_CONCERT_CYCLE = Internal.createForeignKey(Concert.CONCERT, DSL.name("fk_concert_cycle"), new TableField[] { Concert.CONCERT.SPP_CYCLE_ID }, Keys.KEY_SPP_CYCLE_PRIMARY, new TableField[] { SppCycle.SPP_CYCLE.ID }, true);
    public static final ForeignKey<ConcertRecord, VenueRecord> FK_CONCERT_VENUE = Internal.createForeignKey(Concert.CONCERT, DSL.name("fk_concert_venue"), new TableField[] { Concert.CONCERT.VENUE_ID }, Keys.KEY_VENUE_PRIMARY, new TableField[] { Venue.VENUE.ID }, true);
    public static final ForeignKey<ConcertExpenseRecord, ConcertRecord> FK_EXPENSE_CONCERT = Internal.createForeignKey(ConcertExpense.CONCERT_EXPENSE, DSL.name("fk_expense_concert"), new TableField[] { ConcertExpense.CONCERT_EXPENSE.CONCERT_ID }, Keys.KEY_CONCERT_PRIMARY, new TableField[] { Concert.CONCERT.ID }, true);
    public static final ForeignKey<ConcertSetCheckinRecord, ConcertRecord> FK_SET_CHECKIN_CONCERT = Internal.createForeignKey(ConcertSetCheckin.CONCERT_SET_CHECKIN, DSL.name("fk_set_checkin_concert"), new TableField[] { ConcertSetCheckin.CONCERT_SET_CHECKIN.CONCERT_ID }, Keys.KEY_CONCERT_PRIMARY, new TableField[] { Concert.CONCERT.ID }, true);
    public static final ForeignKey<ConcertSetCheckinRecord, MusicianProfileRecord> FK_SET_CHECKIN_MUSICIAN = Internal.createForeignKey(ConcertSetCheckin.CONCERT_SET_CHECKIN, DSL.name("fk_set_checkin_musician"), new TableField[] { ConcertSetCheckin.CONCERT_SET_CHECKIN.MUSICIAN_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<ConcertSettlementRecord, ConcertRecord> FK_SETTLEMENT_CONCERT = Internal.createForeignKey(ConcertSettlement.CONCERT_SETTLEMENT, DSL.name("fk_settlement_concert"), new TableField[] { ConcertSettlement.CONCERT_SETTLEMENT.CONCERT_ID }, Keys.KEY_CONCERT_PRIMARY, new TableField[] { Concert.CONCERT.ID }, true);
    public static final ForeignKey<CreativeRatingRecord, MusicianProfileRecord> FK_CREATIVE_RATING_RATEE = Internal.createForeignKey(CreativeRating.CREATIVE_RATING, DSL.name("fk_creative_rating_ratee"), new TableField[] { CreativeRating.CREATIVE_RATING.RATEE_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<CreativeRatingRecord, MusicianProfileRecord> FK_CREATIVE_RATING_RATER = Internal.createForeignKey(CreativeRating.CREATIVE_RATING, DSL.name("fk_creative_rating_rater"), new TableField[] { CreativeRating.CREATIVE_RATING.RATER_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<CreativeRatingRecord, RehearsalSessionRecord> FK_CREATIVE_RATING_SESSION = Internal.createForeignKey(CreativeRating.CREATIVE_RATING, DSL.name("fk_creative_rating_session"), new TableField[] { CreativeRating.CREATIVE_RATING.REHEARSAL_SESSION_ID }, Keys.KEY_REHEARSAL_SESSION_PRIMARY, new TableField[] { RehearsalSession.REHEARSAL_SESSION.ID }, true);
    public static final ForeignKey<MusicianLevelChangeRecord, MusicianProfileRecord> FK_LEVEL_CHANGE_MUSICIAN = Internal.createForeignKey(MusicianLevelChange.MUSICIAN_LEVEL_CHANGE, DSL.name("fk_level_change_musician"), new TableField[] { MusicianLevelChange.MUSICIAN_LEVEL_CHANGE.MUSICIAN_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<MusicianProfileRecord, AccountRecord> FK_MUSICIAN_ACCOUNT = Internal.createForeignKey(MusicianProfile.MUSICIAN_PROFILE, DSL.name("fk_musician_account"), new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ACCOUNT_ID }, Keys.KEY_ACCOUNT_PRIMARY, new TableField[] { Account.ACCOUNT.ID }, true);
    public static final ForeignKey<MusicianProfileRecord, InstrumentRecord> FK_MUSICIAN_INSTRUMENT = Internal.createForeignKey(MusicianProfile.MUSICIAN_PROFILE, DSL.name("fk_musician_instrument"), new TableField[] { MusicianProfile.MUSICIAN_PROFILE.INSTRUMENT_ID }, Keys.KEY_INSTRUMENT_PRIMARY, new TableField[] { Instrument.INSTRUMENT.ID }, true);
    public static final ForeignKey<MusicianProfileRecord, EnigmaLevelRecord> FK_MUSICIAN_LEVEL = Internal.createForeignKey(MusicianProfile.MUSICIAN_PROFILE, DSL.name("fk_musician_level"), new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ENIGMA_LEVEL_ID }, Keys.KEY_ENIGMA_LEVEL_PRIMARY, new TableField[] { EnigmaLevel.ENIGMA_LEVEL.ID }, true);
    public static final ForeignKey<PendingClaimRecord, MusicianProfileRecord> FK_CLAIM_MUSICIAN = Internal.createForeignKey(PendingClaim.PENDING_CLAIM, DSL.name("fk_claim_musician"), new TableField[] { PendingClaim.PENDING_CLAIM.MUSICIAN_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<PendingClaimRecord, ConcertSettlementRecord> FK_CLAIM_SETTLEMENT = Internal.createForeignKey(PendingClaim.PENDING_CLAIM, DSL.name("fk_claim_settlement"), new TableField[] { PendingClaim.PENDING_CLAIM.CONCERT_SETTLEMENT_ID }, Keys.KEY_CONCERT_SETTLEMENT_PRIMARY, new TableField[] { ConcertSettlement.CONCERT_SETTLEMENT.ID }, true);
    public static final ForeignKey<RehearsalCheckinRecord, MusicianProfileRecord> FK_CHECKIN_MUSICIAN = Internal.createForeignKey(RehearsalCheckin.REHEARSAL_CHECKIN, DSL.name("fk_checkin_musician"), new TableField[] { RehearsalCheckin.REHEARSAL_CHECKIN.MUSICIAN_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<RehearsalCheckinRecord, RehearsalSessionRecord> FK_CHECKIN_SESSION = Internal.createForeignKey(RehearsalCheckin.REHEARSAL_CHECKIN, DSL.name("fk_checkin_session"), new TableField[] { RehearsalCheckin.REHEARSAL_CHECKIN.REHEARSAL_SESSION_ID }, Keys.KEY_REHEARSAL_SESSION_PRIMARY, new TableField[] { RehearsalSession.REHEARSAL_SESSION.ID }, true);
    public static final ForeignKey<RehearsalSessionRecord, BandRecord> FK_REHEARSAL_BAND = Internal.createForeignKey(RehearsalSession.REHEARSAL_SESSION, DSL.name("fk_rehearsal_band"), new TableField[] { RehearsalSession.REHEARSAL_SESSION.BAND_ID }, Keys.KEY_BAND_PRIMARY, new TableField[] { Band.BAND.ID }, true);
    public static final ForeignKey<SppCycleRecord, BandRecord> FK_CYCLE_BAND = Internal.createForeignKey(SppCycle.SPP_CYCLE, DSL.name("fk_cycle_band"), new TableField[] { SppCycle.SPP_CYCLE.BAND_ID }, Keys.KEY_BAND_PRIMARY, new TableField[] { Band.BAND.ID }, true);
    public static final ForeignKey<SppMemberScoreRecord, SppCycleRecord> FK_SCORE_CYCLE = Internal.createForeignKey(SppMemberScore.SPP_MEMBER_SCORE, DSL.name("fk_score_cycle"), new TableField[] { SppMemberScore.SPP_MEMBER_SCORE.SPP_CYCLE_ID }, Keys.KEY_SPP_CYCLE_PRIMARY, new TableField[] { SppCycle.SPP_CYCLE.ID }, true);
    public static final ForeignKey<SppMemberScoreRecord, MusicianProfileRecord> FK_SCORE_MUSICIAN = Internal.createForeignKey(SppMemberScore.SPP_MEMBER_SCORE, DSL.name("fk_score_musician"), new TableField[] { SppMemberScore.SPP_MEMBER_SCORE.MUSICIAN_PROFILE_ID }, Keys.KEY_MUSICIAN_PROFILE_PRIMARY, new TableField[] { MusicianProfile.MUSICIAN_PROFILE.ID }, true);
    public static final ForeignKey<VenueRecord, ContractTypeRecord> FK_VENUE_CONTRACT = Internal.createForeignKey(Venue.VENUE, DSL.name("fk_venue_contract"), new TableField[] { Venue.VENUE.CONTRACT_TYPE_ID }, Keys.KEY_CONTRACT_TYPE_PRIMARY, new TableField[] { ContractType.CONTRACT_TYPE.ID }, true);
    public static final ForeignKey<VenueAvailabilityRecord, VenueRecord> FK_AVAILABILITY_VENUE = Internal.createForeignKey(VenueAvailability.VENUE_AVAILABILITY, DSL.name("fk_availability_venue"), new TableField[] { VenueAvailability.VENUE_AVAILABILITY.VENUE_ID }, Keys.KEY_VENUE_PRIMARY, new TableField[] { Venue.VENUE.ID }, true);
}
