/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_academy.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.AcademySubscription;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AcademySubscriptionRecord extends UpdatableRecordImpl<AcademySubscriptionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_academy.academy_subscription.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_academy.academy_subscription.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.musician_profile_id</code>.
     */
    public void setMusicianProfileId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.musician_profile_id</code>.
     */
    public Long getMusicianProfileId() {
        return (Long) get(1);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.academy_plan_id</code>.
     */
    public void setAcademyPlanId(Long value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.academy_plan_id</code>.
     */
    public Long getAcademyPlanId() {
        return (Long) get(2);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.instructor_profile_id</code>.
     */
    public void setInstructorProfileId(Long value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.instructor_profile_id</code>.
     */
    public Long getInstructorProfileId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>eh8s_academy.academy_subscription.starts_at</code>.
     */
    public void setStartsAt(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_academy.academy_subscription.starts_at</code>.
     */
    public LocalDate getStartsAt() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>eh8s_academy.academy_subscription.expires_at</code>.
     */
    public void setExpiresAt(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_academy.academy_subscription.expires_at</code>.
     */
    public LocalDate getExpiresAt() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>eh8s_academy.academy_subscription.months</code>.
     */
    public void setMonths(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s_academy.academy_subscription.months</code>.
     */
    public Byte getMonths() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>eh8s_academy.academy_subscription.treasury_usdc</code>.
     */
    public void setTreasuryUsdc(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s_academy.academy_subscription.treasury_usdc</code>.
     */
    public BigDecimal getTreasuryUsdc() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.instructor_usdc</code>.
     */
    public void setInstructorUsdc(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.instructor_usdc</code>.
     */
    public BigDecimal getInstructorUsdc() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.academy_subscription_pda</code>.
     */
    public void setAcademySubscriptionPda(String value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.academy_subscription_pda</code>.
     */
    public String getAcademySubscriptionPda() {
        return (String) get(9);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.intended_instruction</code>.
     */
    public void setIntendedInstruction(String value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.intended_instruction</code>.
     */
    public String getIntendedInstruction() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.pay_tx_signature</code>.
     */
    public void setPayTxSignature(String value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.pay_tx_signature</code>.
     */
    public String getPayTxSignature() {
        return (String) get(11);
    }

    /**
     * Setter for <code>eh8s_academy.academy_subscription.paid_at</code>.
     */
    public void setPaidAt(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>eh8s_academy.academy_subscription.paid_at</code>.
     */
    public LocalDateTime getPaidAt() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.payer_wallet_pubkey</code>.
     */
    public void setPayerWalletPubkey(String value) {
        set(13, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.payer_wallet_pubkey</code>.
     */
    public String getPayerWalletPubkey() {
        return (String) get(13);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.on_chain_status</code>.
     */
    public void setOnChainStatus(String value) {
        set(14, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.on_chain_status</code>.
     */
    public String getOnChainStatus() {
        return (String) get(14);
    }

    /**
     * Setter for
     * <code>eh8s_academy.academy_subscription.onchain_expires_at</code>.
     */
    public void setOnchainExpiresAt(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.academy_subscription.onchain_expires_at</code>.
     */
    public LocalDateTime getOnchainExpiresAt() {
        return (LocalDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AcademySubscriptionRecord
     */
    public AcademySubscriptionRecord() {
        super(AcademySubscription.ACADEMY_SUBSCRIPTION);
    }

    /**
     * Create a detached, initialised AcademySubscriptionRecord
     */
    public AcademySubscriptionRecord(Long id, Long musicianProfileId, Long academyPlanId, Long instructorProfileId, LocalDate startsAt, LocalDate expiresAt, Byte months, BigDecimal treasuryUsdc, BigDecimal instructorUsdc, String academySubscriptionPda, String intendedInstruction, String payTxSignature, LocalDateTime paidAt, String payerWalletPubkey, String onChainStatus, LocalDateTime onchainExpiresAt) {
        super(AcademySubscription.ACADEMY_SUBSCRIPTION);

        setId(id);
        setMusicianProfileId(musicianProfileId);
        setAcademyPlanId(academyPlanId);
        setInstructorProfileId(instructorProfileId);
        setStartsAt(startsAt);
        setExpiresAt(expiresAt);
        setMonths(months);
        setTreasuryUsdc(treasuryUsdc);
        setInstructorUsdc(instructorUsdc);
        setAcademySubscriptionPda(academySubscriptionPda);
        setIntendedInstruction(intendedInstruction);
        setPayTxSignature(payTxSignature);
        setPaidAt(paidAt);
        setPayerWalletPubkey(payerWalletPubkey);
        setOnChainStatus(onChainStatus);
        setOnchainExpiresAt(onchainExpiresAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised AcademySubscriptionRecord
     */
    public AcademySubscriptionRecord(com.eh8s.eh8s.database.jooq.eh8s_academy.tables.pojos.AcademySubscription value) {
        super(AcademySubscription.ACADEMY_SUBSCRIPTION);

        if (value != null) {
            setId(value.getId());
            setMusicianProfileId(value.getMusicianProfileId());
            setAcademyPlanId(value.getAcademyPlanId());
            setInstructorProfileId(value.getInstructorProfileId());
            setStartsAt(value.getStartsAt());
            setExpiresAt(value.getExpiresAt());
            setMonths(value.getMonths());
            setTreasuryUsdc(value.getTreasuryUsdc());
            setInstructorUsdc(value.getInstructorUsdc());
            setAcademySubscriptionPda(value.getAcademySubscriptionPda());
            setIntendedInstruction(value.getIntendedInstruction());
            setPayTxSignature(value.getPayTxSignature());
            setPaidAt(value.getPaidAt());
            setPayerWalletPubkey(value.getPayerWalletPubkey());
            setOnChainStatus(value.getOnChainStatus());
            setOnchainExpiresAt(value.getOnchainExpiresAt());
            resetChangedOnNotNull();
        }
    }
}
