/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_academy.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.CourseAccessGrant;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CourseAccessGrantRecord extends UpdatableRecordImpl<CourseAccessGrantRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_academy.course_access_grant.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_academy.course_access_grant.course_id</code>.
     */
    public void setCourseId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.course_id</code>.
     */
    public Long getCourseId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s_academy.course_access_grant.course_scope</code>.
     */
    public void setCourseScope(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.course_scope</code>.
     */
    public Long getCourseScope() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>eh8s_academy.course_access_grant.wallet_pubkey</code>.
     */
    public void setWalletPubkey(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.wallet_pubkey</code>.
     */
    public String getWalletPubkey() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>eh8s_academy.course_access_grant.granted_by_account_id</code>.
     */
    public void setGrantedByAccountId(Long value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>eh8s_academy.course_access_grant.granted_by_account_id</code>.
     */
    public Long getGrantedByAccountId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>eh8s_academy.course_access_grant.note</code>.
     */
    public void setNote(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.note</code>.
     */
    public String getNote() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eh8s_academy.course_access_grant.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.expires_at</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>eh8s_academy.course_access_grant.is_active</code>.
     */
    public void setIsActive(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>eh8s_academy.course_access_grant.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>eh8s_academy.course_access_grant.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>eh8s_academy.course_access_grant.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourseAccessGrantRecord
     */
    public CourseAccessGrantRecord() {
        super(CourseAccessGrant.COURSE_ACCESS_GRANT);
    }

    /**
     * Create a detached, initialised CourseAccessGrantRecord
     */
    public CourseAccessGrantRecord(Long id, Long courseId, Long courseScope, String walletPubkey, Long grantedByAccountId, String note, LocalDateTime expiresAt, Byte isActive, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(CourseAccessGrant.COURSE_ACCESS_GRANT);

        setId(id);
        setCourseId(courseId);
        setCourseScope(courseScope);
        setWalletPubkey(walletPubkey);
        setGrantedByAccountId(grantedByAccountId);
        setNote(note);
        setExpiresAt(expiresAt);
        setIsActive(isActive);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised CourseAccessGrantRecord
     */
    public CourseAccessGrantRecord(com.eh8s.eh8s.database.jooq.eh8s_academy.tables.pojos.CourseAccessGrant value) {
        super(CourseAccessGrant.COURSE_ACCESS_GRANT);

        if (value != null) {
            setId(value.getId());
            setCourseId(value.getCourseId());
            setCourseScope(value.getCourseScope());
            setWalletPubkey(value.getWalletPubkey());
            setGrantedByAccountId(value.getGrantedByAccountId());
            setNote(value.getNote());
            setExpiresAt(value.getExpiresAt());
            setIsActive(value.getIsActive());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
