/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_academy.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.LessonProgress;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LessonProgressRecord extends UpdatableRecordImpl<LessonProgressRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_academy.lesson_progress.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson_progress.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_academy.lesson_progress.account_id</code>.
     */
    public void setAccountId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson_progress.account_id</code>.
     */
    public Long getAccountId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s_academy.lesson_progress.lesson_id</code>.
     */
    public void setLessonId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson_progress.lesson_id</code>.
     */
    public Long getLessonId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>eh8s_academy.lesson_progress.last_position_sec</code>.
     */
    public void setLastPositionSec(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson_progress.last_position_sec</code>.
     */
    public Integer getLastPositionSec() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>eh8s_academy.lesson_progress.completed_at</code>.
     */
    public void setCompletedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson_progress.completed_at</code>.
     */
    public LocalDateTime getCompletedAt() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>eh8s_academy.lesson_progress.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson_progress.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LessonProgressRecord
     */
    public LessonProgressRecord() {
        super(LessonProgress.LESSON_PROGRESS);
    }

    /**
     * Create a detached, initialised LessonProgressRecord
     */
    public LessonProgressRecord(Long id, Long accountId, Long lessonId, Integer lastPositionSec, LocalDateTime completedAt, LocalDateTime updatedAt) {
        super(LessonProgress.LESSON_PROGRESS);

        setId(id);
        setAccountId(accountId);
        setLessonId(lessonId);
        setLastPositionSec(lastPositionSec);
        setCompletedAt(completedAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LessonProgressRecord
     */
    public LessonProgressRecord(com.eh8s.eh8s.database.jooq.eh8s_academy.tables.pojos.LessonProgress value) {
        super(LessonProgress.LESSON_PROGRESS);

        if (value != null) {
            setId(value.getId());
            setAccountId(value.getAccountId());
            setLessonId(value.getLessonId());
            setLastPositionSec(value.getLastPositionSec());
            setCompletedAt(value.getCompletedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
