/*
 * This file is generated by jOOQ.
 */
package com.eh8s.eh8s.database.jooq.eh8s_academy.tables.records;


import com.eh8s.eh8s.database.jooq.eh8s_academy.tables.Lesson;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LessonRecord extends UpdatableRecordImpl<LessonRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>eh8s_academy.lesson.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.section_id</code>.
     */
    public void setSectionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.section_id</code>.
     */
    public Long getSectionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.title</code>.
     */
    public void setTitle(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.title</code>.
     */
    public String getTitle() {
        return (String) get(2);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.video_provider</code>.
     */
    public void setVideoProvider(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.video_provider</code>.
     */
    public String getVideoProvider() {
        return (String) get(4);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.video_url</code>.
     */
    public void setVideoUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.video_url</code>.
     */
    public String getVideoUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.embed_url</code>.
     */
    public void setEmbedUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.embed_url</code>.
     */
    public String getEmbedUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.duration_sec</code>.
     */
    public void setDurationSec(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.duration_sec</code>.
     */
    public Integer getDurationSec() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.sort_order</code>.
     */
    public void setSortOrder(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.sort_order</code>.
     */
    public Integer getSortOrder() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.is_free_preview</code>.
     */
    public void setIsFreePreview(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.is_free_preview</code>.
     */
    public Byte getIsFreePreview() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.resources</code>.
     */
    public void setResources(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.resources</code>.
     */
    public String getResources() {
        return (String) get(10);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.practice_prompt</code>.
     */
    public void setPracticePrompt(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.practice_prompt</code>.
     */
    public String getPracticePrompt() {
        return (String) get(11);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.is_active</code>.
     */
    public void setIsActive(Byte value) {
        set(12, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(12);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>eh8s_academy.lesson.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>eh8s_academy.lesson.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LessonRecord
     */
    public LessonRecord() {
        super(Lesson.LESSON);
    }

    /**
     * Create a detached, initialised LessonRecord
     */
    public LessonRecord(Long id, Long sectionId, String title, String description, String videoProvider, String videoUrl, String embedUrl, Integer durationSec, Integer sortOrder, Byte isFreePreview, String resources, String practicePrompt, Byte isActive, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Lesson.LESSON);

        setId(id);
        setSectionId(sectionId);
        setTitle(title);
        setDescription(description);
        setVideoProvider(videoProvider);
        setVideoUrl(videoUrl);
        setEmbedUrl(embedUrl);
        setDurationSec(durationSec);
        setSortOrder(sortOrder);
        setIsFreePreview(isFreePreview);
        setResources(resources);
        setPracticePrompt(practicePrompt);
        setIsActive(isActive);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LessonRecord
     */
    public LessonRecord(com.eh8s.eh8s.database.jooq.eh8s_academy.tables.pojos.Lesson value) {
        super(Lesson.LESSON);

        if (value != null) {
            setId(value.getId());
            setSectionId(value.getSectionId());
            setTitle(value.getTitle());
            setDescription(value.getDescription());
            setVideoProvider(value.getVideoProvider());
            setVideoUrl(value.getVideoUrl());
            setEmbedUrl(value.getEmbedUrl());
            setDurationSec(value.getDurationSec());
            setSortOrder(value.getSortOrder());
            setIsFreePreview(value.getIsFreePreview());
            setResources(value.getResources());
            setPracticePrompt(value.getPracticePrompt());
            setIsActive(value.getIsActive());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
